### ISSUE TITLE
The design

### ISSUE THREAD

**Issue by Shougo** [Shougo/defx.nvim#1]
* Not depends on denite.nvim

* Vim8/neovim compatible(nvim-yarp is needed for Vim8)

* Implemented by Python3

* No double filer feature

* Column feature

* Source feature

* Options

* Highlight is defined by column

* Few commands (`:Defx` command only?)

* Extended rename

* Mark

* Windows supporters are needed

* The original trashbox feature

* No minimal features

* Subtree feature like vimfiler

* No default mappings

* No global variables

* No explorer feature(like `g:vimfiler_as_default_explorer`)

Release date: In 2018 someday

**Comment by petobens** [comment]
I think the double filer feature is really useful (i use it a lot). Also it would be nice to keep vimfiler's bookmark feature.

**Comment by wsdjeg** [comment]
@Shougo nice work, 

@petobens what is double filer feature?

**Comment by kirin123kirin** [comment]
@Shougo
待ってました。
いつ頃リリース予定ですか？

**Comment by kutsan** [comment]
@kirin123kirin According to my Google Translate, I am also wondering when will it be released.

**Comment by kirin123kirin** [comment]
Can I open UNC Path for windows platform.

**Comment by Shougo** [comment]
> I think the double filer feature is really useful (i use it a lot). Also it would be nice to keep vimfiler's bookmark feature.

It is useful.  But I think jump/mark feature is better.
bookmark feature is to be determined.

**Comment by Shougo** [comment]
> @petobens what is double filer feature?

`:VimFilerDouble`

You can copy/move the files to another vimfiler directory.

**Comment by Shougo** [comment]
> Can I open UNC Path for windows platform.

The support is very hard.
I don't want to support it.   You can add it though.

Please see:
https://github.com/Shougo/vimfiler.vim/issues/170

**Comment by Shougo** [comment]
@kirin123kirin The release will be in 2018 someday.

**Comment by Shougo** [comment]
> Column feature

Column means, "name", "type", "size", "date" should be customize-able more generic.
Users can add more columns like "git" column.

**Comment by lambdalisue** [comment]
It would be nice if it does not rely on filesystem.

For example, I would like to make a plugin which cooperate with this one to show a directory tree on a particular commit.
In that case, probably the INPUT for this plugin would be a tree dictionary with custom kind, actions, etc.

**Comment by Shougo** [comment]
It is already todo listed.

> Source feature

**Comment by Shougo** [comment]
The source feature is similar to denite source.
But it is not compatible.

**Comment by Shougo** [comment]
I have started the vaporware development.

https://github.com/Shougo/defx.nvim/commit/4b4dfae45c44933cc9c5e092e6c7e728e18d6fa9

**Comment by kutsan** [comment]
@Shougo Is there any way to set colors of items in the tree explorer according to `$LS_COLORS` env. variable?

Will you provide an API for [vim-devicons](https://github.com/ryanoasis/vim-devicons) symbols? Showing symbols on the right side of the explorer wasn't right choice. They should be just before the filename.

**Comment by Shougo** [comment]
> @Shougo Is there any way to set colors of items in the tree explorer according to $LS_COLORS env. variable (a.k.a. dircolors)?

No.

> Will you provide an API for vim-devicons symbols? Showing symbols on the right side of the explorer wasn't right choice. They should be just before the filename.

Yes.  The column feature will be improved than vimfiler.

**Comment by Shougo** [comment]
I have decided defx has no default mappings and no global variables.

**Comment by Shougo** [comment]
defx.nvim does not support explorer feature like `g:vimfiler_as_default_explorer`.

It is very buggy and hard to implement.

**Comment by amikai** [comment]
I think the design can work like "file manager".  Anything file related feature can be supported, not just explorer.
My suggestion is:
Inspire by Vscode.
Implement the special window which manages number of buffers.
The default buffer in this window is file explorer(like vscode).
The second buffer maybe is git related information(like vscode).
Then other buffer can be implemented by who they want other feature.

**Comment by Shougo** [comment]
I have re-started defx.nvim development.
You can test it.

Note:  Current defx.nvim is neovim only.

**Comment by amikai** [comment]
What does toggle_select do?

**Comment by Shougo** [comment]
> What does `toggle_select` do?

It changes candidate select state.
It same with denite.

**Comment by kristijanhusak** [comment]
@Shougo , when will custom column feature be available?

**Comment by Shougo** [comment]
It takes more time.

* More default columns
* Multiple buffers support
* Split defx buffer
* Copy, Move

Above features are hipriority than column customization.

**Comment by kristijanhusak** [comment]
Would you like to have git status column as part of the default columns? I have initial version of it.

**Comment by Shougo** [comment]
> Would you like to have git status column as part of the default columns?

No.

**Comment by Shougo** [comment]
> Copy, Move

Implemented.

**Comment by oblitum** [comment]
Is it in the plan to remove the yarp solution for supporting Vim? Having to depend on NeoVim for Vim to work isn't great.

**Comment by oblitum** [comment]
I moved to it, looks great :), but won't adopt a file manager plugin when on Vim, will use its own Netrw.

**Comment by Shougo** [comment]
> Is it in the plan to remove the yarp solution for supporting Vim? Having to depend on NeoVim for Vim to work isn't great.

No.

I use defx.nvim + nvim-yarp in Vim.  It is no problem.

**Comment by oblitum** [comment]
OK, thanks. I will stick to netrw for vim.

**Comment by oblitum** [comment]
I'm using the `drop` action for using it in "explorer" style, but how can I avoid opening a file when navigating directories? Since the same `open` action is used both for browsing as for opening files in the defx buffer?

**Comment by Shougo** [comment]
@oblitum I have added `open_directory` action for it.

**Comment by oblitum** [comment]
@Shougo thx!

**Comment by oblitum** [comment]
@Shougo `defx#do_action('open_directory')` is still opening files too though. I just tried.

**Comment by Shougo** [comment]
Fixed.

**Comment by oblitum** [comment]
Working :)

**Comment by pwntester** [comment]
Can you make `open_directory` similar to `open` in that it takes an optional argument with the directory path. I want to implement a custom action and need to receive the selected directory name and it should not trigger on regular files.

Thanks!

**Comment by Shougo** [comment]
I don't understand.
Please upload the example.

**Comment by pwntester** [comment]
I was trying to enable a mapping in the defx windows that when used on a directory, will run a command that takes the directory path as an argument. 

For example, if I enter `/` on the `/tmp/foo` directory, I want to run: `call esearch#init({'cwd': '/tmp/foo'})`

**Comment by Shougo** [comment]
OK.  I get it.
Please create the new issue for it.

**Comment by pwntester** [comment]
Thanks, filed https://github.com/Shougo/defx.nvim/issues/51

**Comment by woodyZootopia** [comment]
The time/date a directory is modified is not shown even when time option is enabled.
Is it an intentional design to hide the modification time of directories?

**Comment by woodyZootopia** [comment]
Also, when I do :Defx with unsaved file, the unsaved changes are discarded.
I think it would be better if we have something like --force option?

**Comment by woodyZootopia** [comment]
https://github.com/Shougo/defx.nvim/issues/1#issuecomment-446281173
I made a PR to it. If you don't like it, please discard.
https://github.com/Shougo/defx.nvim/pull/53

**Comment by Shougo** [comment]
> Also, when I do :Defx with unsaved file, the unsaved changes are discarded.
I think it would be better if we have something like --force option?

Please create the new issue for it.  I will test it later.
If not, I will ignore your issue.

**Comment by woodyZootopia** [comment]
@Shougo Thank you! I created new issue #55 and start working on it :)

**Comment by oblitum** [comment]
Mouse support, good to have? VimFiler had I think.

**Comment by kristijanhusak** [comment]
You can add mouse support yourself if you want:
```vimL
nnoremap <silent><buffer><expr> <2-LeftMouse> defx#do_action('drop')
```

**Comment by oblitum** [comment]
My recommendation:

```vim
  nnoremap <silent><buffer><expr> <2-LeftMouse> defx#do_action('drop')
  nnoremap <silent><buffer><expr> <RightMouse> defx#do_action('cd', ['..'])
```

**Comment by oblitum** [comment]
Seems dirvish supports that.

**Comment by Shougo** [comment]
@oblitum I don't add the feature.  Yes, dirvish already supports the feature.  But some feature don't like it.   I also don't like it.

Please see below issue.
https://github.com/justinmk/vim-dirvish/issues/110

**Comment by petobens** [comment]
Ok thanks. I did this here https://github.com/kmnk/denite-dirmark/issues/2
