### ISSUE TITLE
failed to update defx buffer with Defx path

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/defx.nvim#105]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

I can not update defx buffer via command `:Defx new_path`

## Expected

I think same as vimfiler, we should be able to updated defx buffer via `:Defx new_path`. in vimfiler, we can use `Vimfiler -no-toggle new_path` to update vimfiler buffer.

## Environment Information

 * defx version(SHA1): master

 * OS: windows

 * neovim/Vim version: neovim master

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
call defx#custom#option('_', {
      \ 'winwidth': 30,
      \ 'split': 'vertical',
      \ 'show_ignored_files': 0,
      \ 'buffer_name': '',
      \ 'toggle': 1,
      \ 'resume': 1
      \ })

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. `:Defx`, defx will be opend with current dir
 2. `:Defx -no-toggle D:/`, nothing changed

as I know, defx support `-new` option,  it is same as `-create` option in vimfiler.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by tex** [comment]
You can also do that with just calling do_action:

```
        nnoremap <silent><buffer><expr> cc                                                                                              
                                \ defx#do_action('cd', [PATH])                                                                   
```

**Comment by wsdjeg** [comment]
@Shougo, I have test this issue, it still happened for me.

**Comment by Shougo** [comment]
> @Shougo, I have test this issue, it still happened for me.

The feature does not work for `resume`.
Please read `https://github.com/Shougo/defx.nvim/issues/106`.

Please see your defx's configuration.

**Comment by wsdjeg** [comment]
@Shougo  Yes I have enable resume, because I need this feature for resume tree. I hope defx can add this feature, here is why users need this feature:

1. people may expand project directory, so the project tree should be able to resumed when the path is cached.

2. when switch to new path, and the path layout is not cached, then generated new tree.
