### ISSUE TITLE
broken -resume

### ISSUE THREAD

**Issue by tex** [Shougo/defx.nvim#106]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Latest (47d7a676ff1c0e32103785c5e3d01bf042caed18) commit broken -resume function.

open nvim with some file in folder B, pwd in nvim shows B.
:Defx
navigate to some other directory (for example A/)
q (to quit defx)
:Defx -resume
defx's buffer shows folder B

## Expected

open vim with some file in folder B
:Defx
navigate to some other directory (for example A/)
q (to quit defx)
:Defx -resume
defx's buffer should show the latest directory (A/)

## Environment Information

 * defx version(SHA1):

 * OS:

NixOS

 * neovim/Vim version:

0.4

 * `:checkhealth` or `:CheckHealth` result(neovim only):

It is fully OK.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

See problem summary and expected.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Fixed.

**Comment by tex** [comment]
Thanks Shougo! I am migrating (slowly) from Unite/Vimfiller to Denite/Defx. So far very good experience. Thank you for your work on those plugins!
