### ISSUE TITLE
Add depth or level option to open tree recursively upon Defx open

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#108]
Hi! I would like to open Defx with some trees "unfolded". Is it possible to introduce a `depth` or `tree` parameter (in order to do `Defx -level=2`)  that opens the directory tree recursively up to that level? Thanks!!

**Comment by Shougo** [comment]
Why it is needed?
Please describe it more clearly.

If not, I will close it.

**Comment by petobens** [comment]
I want to use defx as a previewer for denite in https://github.com/Shougo/denite.nvim/pull/204. For that objective I need to be able to operate the tree depth (I only want to open/unfold a few levels); Currently the `open_tree_recursive` opens all levels which takes long and it's not particularly useful for the preview.

**Comment by petobens** [comment]
Thank you!
