### ISSUE TITLE
(WIP) modify file names

### ISSUE THREAD

**Issue by callmekohei** [Shougo/defx.nvim#12]
Hello! I love your defx.nvim!

I'm happy if you add the functions of `modifing file names`.

(before)
```txt
- /Users/callmekohei/tmp/Foo/
  2018-08-15-foo
  2018-08-15-bar.txt
  2018-08-15-baz.txt
```

(after)
```txt
- /Users/callmekohei/tmp/Foo/
  foo
  bar.txt
  baz.txt
```

Thanks :-)

**Comment by Shougo** [comment]
It is exrename feature?
It is already todo listed, but it is low priority.

**Comment by callmekohei** [comment]
Hello! Shougo-san!

Sure!

I'm looking forward to implement this future!

Thank you very much! :-)
