### ISSUE TITLE
airblade/vim-rooter not working with defx

### ISSUE THREAD

**Issue by zhoupro** [Shougo/defx.nvim#120]
https://github.com/airblade/vim-rooter
when use nerdtree, Change directory will change root. defx not working .

**Comment by zhoupro** [comment]
I found`nnoremap <silent><buffer><expr> cd
     \ defx#do_action('change_vim_cwd')` can set current directory. I will just use it, not to use vim-rooter.

**Comment by Shougo** [comment]
You should use this.
https://github.com/airblade/vim-rooter#using-root-finding-functionality-in-other-scripts
