### ISSUE TITLE
Defx -resume then quit and not in correct buffer

### ISSUE THREAD

**Issue by tex** [Shougo/defx.nvim#124]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Open file A.txt in neovim.
:Defx -resume
q
Now I see A.txt. Open B.txt.
:Defx -resume
q
Now I see A.txt.

Defx is resumed correctly, cursor position, folder is as expected. But the quit works incorrectly.

## Expected

At the end I should see B.txt. The buffer that opened Defx last. 

## Environment Information

 * defx version(SHA1):

6764dae5773736654cd02749a742406bc275c4a5
Today's current master.

 * OS:

 * neovim/Vim version:

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

See description.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by tex** [comment]
I have workaround for this, but still I think Defx should return to the buffer from where Defx was executed.

```
function! My_defx() abort                                                                                                               
        let w:defx_pwd = expand('%:p:h')                                                                                                
        let w:defx_cbn = bufnr('%')                                                                                                     
        call defx#util#call_defx('Defx', '-resume')                                                                                     
endfunction                                                                                                                             
                                                                                                                                        
function! My_defx_quit(context) abort                                                                                                   
        call defx#do_action('quit')                                                                                                     
        execute 'buffer ' . w:defx_cbn                                                                                                  
endfunction                                                                                                                             
```

**Comment by Shougo** [comment]
Fixed.
