### ISSUE TITLE
Concealed question mark 

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#127]
# Problems summary
Fix for issue #126 caused this question mark to show as concealed. There is no way to hide it, at least i didn't find a way to do it.

## Expected
To not see the question mark, or at least be able to hide it.

## Environment Information

 * defx version(SHA1): b8d688b54b34f8b9b0f03bef17fb4f4d1ddbf74b

 * OS: Manjaro Linux i3

 * neovim/Vim version:
```
NVIM v0.4.0-631-g24a9516ff
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

```
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. start up neovim
 2. run `:Defx`

## Screen shot (if possible)
![screenshot](https://i.imgur.com/Di8jc8c.png)

**Comment by Shougo** [comment]
Please set `conceallevel`.
I think you have disabled it.

**Comment by kristijanhusak** [comment]
Works now, thanks!
