### ISSUE TITLE
Custom Color file type

### ISSUE THREAD

**Issue by sphynx79** [Shougo/defx.nvim#129]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
How i can reproduce this plugin [vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight).
I want set the custom color for my file type

Another question in Nerdtree i use NERDTreeFocus, for set focus in Nerdtree window, it's possible implement this function in Defx.

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/5004160/58517486-d71e7900-81ab-11e9-8a71-dd28c8f26446.png)

## Environment Information

 * defx version(SHA1):

 * OS: Windows 7 64 bit

 * neovim version: 0.4.0-819

**Comment by Shougo** [comment]
I think this plugin is better for you.

https://github.com/kristijanhusak/defx-icons

**Comment by Shougo** [comment]
You can change the filename color by `defx-column-type`.
But the configuration is complicated.

```
							*defx-column-type*
type		File type.

		variables:
		types		  the types definition
				  (default: complicated)
```

**Comment by Shougo** [comment]
> Another question in Nerdtree i use NERDTreeFocus, for set focus in Nerdtree window, it's possible implement this function in Defx.

Hm.  I think `Defx -resume` is for it.
