### ISSUE TITLE
開いたフォルダ内での移動

### ISSUE THREAD

**Issue by take** [Shougo/defx.nvim#130]
大変お世話になっております、Vimfiler時代から愛用させていただいてます。

一つ質問なんですが、どこかに記載されていたらすみません（一応doc/defx.txtは見ました）。

Vimfiler時代は開いたフォルダ内での移動を、`g k`や`g j`で出来たと思うんですが、それに相当するキーバインドは存在してたりしますでしょうか？ :bow: 

お手数ですが返信いただけると助かります

**Comment by Shougo** [comment]
すみませんが、言っている意味がさっぱりわかりません。
スクリーンショット付きでもっと具体的に動作を教えてください。

**Comment by take** [comment]
説明不足ですみません :bow: 

<img width="489" alt="Screen Shot 2019-06-02 at 1 09 54" src="https://user-images.githubusercontent.com/1095842/58750935-27127e00-84d3-11e9-8909-aa18cad3dc1b.png">

上の画像で言うと、カーソルがある位置からappフォルダ内一番下の`views`に移動したい、といった要望です

**Comment by Shougo** [comment]
なるほど。defx にはないです。
