### ISSUE TITLE
VimFilerの-findのようなオプション

### ISSUE THREAD

**Issue by take** [Shougo/defx.nvim#131]
度々すみません :bow: 

VimFilerを使っていた時は、 `:VimFilerExplorer -find` をよく使っていたのですが、これに相当するような機能は現在ありますでしょうか？ :eyes: 

一応docを見たのですが見当たらなかったので質問させていただきました

**Comment by Shougo** [comment]
```
Q: I want to explore the folder where the current file is.

A: >
	Defx `expand('%:p:h')` -search=`expand('%:p')`
```
