### ISSUE TITLE
width of filename column is one off for folders

### ISSUE THREAD

**Issue by tex** [Shougo/defx.nvim#133]
# Problems summary

$SUBJ

It is because of ':' as a folder marker which is not accounted when computing width of filename column.

## Expected

Same width for folders and files.

**Comment by Shougo** [comment]
Sorry.  It is feature to fix https://github.com/Shougo/defx.nvim/issues/126 problem.

If you can implement better, please create the PR.

Closing.

**Comment by Shougo** [comment]
And I don't think `width of filename column is one off for folders` is problem than #126.

**Comment by tex** [comment]
![defx](https://user-images.githubusercontent.com/27386/58908042-d20f7b80-870f-11e9-927a-b2a8ccac4fdc.png)

Will try to fix it. I do not like how it looks now.

**Comment by Shougo** [comment]
Hm...

I don't reproduce the problem.
Please upload the minimal vimrc.   I will try it later.

**Comment by Shougo** [comment]
Fixed.

**Comment by tex** [comment]
Thank you very much!!
