### ISSUE TITLE
defx#is_directory_opened() api should return false on closed dir

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/defx.nvim#135]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

when cursor is on dir, and the dir is not opened, defx#is_directory_opened() should return v:false

## Expected

defx#is_directory_opened() return false on closed dir

## Environment Information

 * defx version(SHA1): master

 * OS: win7

 * neovim/Vim version: neovim-master

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

1. open defx, and open dir, move cursor to line 3
2. run `:echo defx#is_directory_opened()`

## Screen shot (if possible)

![图片](https://user-images.githubusercontent.com/13142418/59143167-71778b80-89fa-11e9-96e1-11d9378a0e2b.png)

**Comment by wsdjeg** [comment]
thank you for hot fix.

**Comment by wsdjeg** [comment]
@Shougo I just test it, it still return v:true

**Comment by Shougo** [comment]
I have tested it and it is false.
If it is `v:true`, defx tree feature does not work.

**Comment by Shougo** [comment]
Please test it is the latest version.

Fortunately, you are not Vim beginner and reproduce-able for the problem.
Please fix/report the problem.

**Comment by Shougo** [comment]
If it is reproduce-able, it is easy to fix.
But it is not reproduce-able, it is hard.

I cannot reproduce-able but you can.
So I or you should fix/report the problem?

**Comment by wsdjeg** [comment]
sorry, It works, I just forgot to recache runtime file.

**Comment by Shougo** [comment]
OH....
