### ISSUE TITLE
Do not move the directory with the 'open' command.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/defx.nvim#139]
# Problems summary
Do not move the directory with the 'open' command.

## Expected
Currently, when selecting a directory, the directory is moved using the 'open' command, but please do not move the directory.

## Environment Information

 * defx version(SHA1): 1ca84d27bd4b0bffdb2ff9919a8c97486c88d10c

 * OS: Mac

 * neovim/Vim version: neovim 0.3.7

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```vim
function! s:defx_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
    \ defx#do_action('open')
endfunction
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. When selecting a file, open the file with the 'open' command.
 2. When selecting a directory, just open the directory, do not move it.

**Comment by Shougo** [comment]
Sorry.  I don't want to change the current behavior.

**Comment by Shougo** [comment]
Because, it breaks other users configuration.

**Comment by nabezokodaikon** [comment]
Understood. Thank you for the reply.
