### ISSUE TITLE
icons are merely shown half.

### ISSUE THREAD

**Issue by Azureki** [Shougo/defx.nvim#140]
# Problem
when using non-mono fonts, icons are merely shown half.

## Environment
+ system: linux
+ terminal: konsole
+ vim plugin manager: [vim-plug](https://github.com/junegunn/vim-plug)
+ plugins: defx.nvim + [defx-icons](https://github.com/kristijanhusak/defx-icons)

Last line `set termguicolors` is **necessary** to reproduce the problem.  
`~/.config/nvim/init.vim`:  
``` vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'kristijanhusak/defx-icons'
Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
cal plug#end()

set termguicolors
```

## The reproduce ways:  
1. install plugins
2. `:Defx -columns=mark:indent:icons:filename:type`

## Screen shot
1. font: furacode nerd (non-mono)
<img width="140" alt="image" src="https://user-images.githubusercontent.com/22387028/59549116-92f0ee00-8f8b-11e9-9104-b9db1c13e7f8.png">

2. font: furacode nerd Mono
<img width="153" alt="image" src="https://user-images.githubusercontent.com/22387028/59549128-b2881680-8f8b-11e9-8479-07724bfda3f1.png">

`furacode nerd` is a double-width glyph font, while `furacode nerd Mono` is single-width.

----

## other plugins
I also tried other plugins,  icons are shown wholly, although they are grey. 

NerdTree: 
<img width="144" alt="image" src="https://user-images.githubusercontent.com/22387028/59549096-28d84900-8f8b-11e9-88e6-c13e1150848c.png">

vim-startify: 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/22387028/59549297-0f84cc00-8f8e-11e9-8c57-da76fbb37440.png">

[lightline-bufferline](https://github.com/mengelbrecht/lightline-bufferline): 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/22387028/59549336-8621c980-8f8e-11e9-80b2-ce00561de459.png">

It seems that these plugins are not influenced by `set termguicolors`.

**Comment by kristijanhusak** [comment]
Try increasing this value, for example put 3.
```
let g:defx_icons_column_length = 3
``

**Comment by Azureki** [comment]
@kristijanhusak 
in `.config/nvim/init.vim`?

I tried and it made no difference.

**Comment by Azureki** [comment]
I tried [sakura](https://launchpad.net/sakura) and [Alacritty](https://github.com/jwilm/alacritty).  
Both of them can show entire icons.

Good bye, konsole.

**Comment by Shougo** [comment]
> when using non-mono fonts, icons are merely shown half.

It is the terminal problem.

**Comment by Azureki** [comment]
@Shougo 
Yes, last night I tested on 4 terminals: `konsole, Alacritty, sakura, hyper`, only `konsole` can reproduce this issue.
