### ISSUE TITLE
split=floatingを設定した際のhighlight NormalFloat guibg=NONEについて

### ISSUE THREAD

**Issue by yuk1h1ra** [Shougo/defx.nvim#142]
こんにちは、日本語で失礼いたします。

Defxのオプションで `-split=floating` を設定した際に
`highlight NormalFloat guibg=NONE`
が記述されている理由はなにかありますか？

具体的には、floatingされたwindowの色を変えようと思っていたのですが、
上記の記述があるため、毎度背景色と同じになってしまいました。

```
augroup NormalFloatBG
  autocmd!
  autocmd BufWinEnter * highlight NormalFloat guibg=gray
augroup END
```

上記のコードにて一応floating windowの背景色を変えることはできていますが、
Defx.nvimのほうでNormalFloat guibg=NONEが設定されている理由が気になりました。

**Comment by Shougo** [comment]
NormalFloat のハイライト上書きを削除しました。
これを設定していた理由としては、Floating Windows のデフォルトの背景色が見づらいためですね
