### ISSUE TITLE
Last buffer does not show

### ISSUE THREAD

**Issue by ppnman** [Shougo/defx.nvim#143]
# Problems summary

When there is only one buffer and defx is openning, vim does not show the buffer.

## Expected

Always show buffer.

## Environment Information

 * defx version(SHA1): Latest

 * OS: ubuntu16.04

 * neovim/Vim version: Latest

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
nnoremap <silent> <F2> :Defx -resume -toggle<CR>

autocmd FileType defx do WinEnter | call s:defx_my_settings()
fu! s:defx_my_settings() abort
    nnoremap <silent><buffer><expr> <CR> defx#do_action('drop')
endf
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. `vim a.txt b.txt`
 2. press `<F2>` to open defx
 3. `:bd` to delete a.txt
 4. Then we CANNOT see b.txt, only see defx.

**Comment by wsdjeg** [comment]
you should read Vim help :bd, this command will close split Windows.

发自我的华为手机

-------- 原始邮件 --------
主题：[Shougo/defx.nvim] Last buffer does not show (#143)
发件人：Zj Li
收件人："Shougo/defx.nvim"
抄送：Subscribed

Problems summary

When there is only one buffer and defx is openning, vim does not show the buffer.

Expected

Always show buffer.

Environment Information

  *   defx version(SHA1): Latest

  *   OS: ubuntu16.04

  *   neovim/Vim version: Latest

Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

nnoremap <silent> <F2> :Defx -resume -toggle<CR>

autocmd FileType defx do WinEnter | call s:defx_my_settings()
fu! s:defx_my_settings() abort
    nnoremap <silent><buffer><expr> <CR> defx#do_action('drop')
endf

The reproduce ways from neovim/Vim starting (Required!)

  1.  vim a.txt b.txt
  2.  press <F2> to open defx
  3.  :bd to delete a.txt
  4.  Then we CANNOT see b.txt, only see defx.

―

**Comment by Shougo** [comment]
`:bd` behavior is Vim's feature.
Not defx's issue.

And you have not the minimal vimrc.
Closing.

**Comment by Shougo** [comment]
> **Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

Have you read it in the issue template?
I can close the issue without minimal vimrc quickly.

**Comment by ppnman** [comment]
@wsdjeg @Shougo 
It's not defx's issue, I am so sorry.
I should using `:bp |  bd #` instead of `:bd`

**Comment by ppnman** [comment]
> > **Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**
> 
> Have you read it in the issue template?
> I can close the issue without minimal vimrc quickly.

I am so sorry. I just thought "minimal init.vim" means minimal configuration of defx.

**Comment by Shougo** [comment]
> I am so sorry. I just thought "minimal init.vim" means minimal configuration of defx.

OK.  "minimal init.vim" means it can reproducible by the file like this.

`nvim -u init.vim`

It does not mean minimal plugin configuration.
