### ISSUE TITLE
TUI mess up when try to async open dir

### ISSUE THREAD

**Issue by zgpio** [Shougo/defx.nvim#144]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
TUI mess up when try to async open dir.

## Environment Information

 * defx version(SHA1): 1d657eb0

 * OS: linux

 * neovim/Vim version: NVIM v0.4.0-567-gae2401621

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set rtp+=./defx.nvim/

nnoremap <silent>   <Space>e :<C-u>Defx -columns=mark:indent:icon:filename:type -split=vertical -direction=topleft -winwidth=40 -listed -resume <CR>
autocmd FileType defx call Defx()

func Defx()
  nnoremap <silent><buffer><expr> l defx#async_action('open')
  nnoremap <silent><buffer><expr> h defx#do_action('cd', ['..'])
endfunc
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. nvim -u init.vim
 2. press `<space>e` to open defx
 3. press `h` util root dir
 4. try to use `l` to open `bin/`, you will find that TUI mess up `**` as the [video](https://asciinema.org/a/iGj1XIZ6APEq4FDHHKgSRAp70)

**Comment by Shougo** [comment]
Unfortunately, it is the feature.
I think you use slow machine.

`defx#async_action()` is asynchronous.
The syntax highlight may not work correctly.
