### ISSUE TITLE
[New action] open_or_close_tree_or_drop

### ISSUE THREAD

**Issue by Psykopear** [Shougo/defx.nvim#146]
Hi Shougo, thank you for this plugin.

I wanted to be able to map a command that open/closes the tree if the line under the cursor is a folder, or call the "drop" command if it's a file.

I didn't find and easy way to do this, so I forked the project and implemented a new action, "open_or_close_tree_or_drop" that does exactly this.

Is it possible to do the same thing with the current implementation?

Otherwise I can open a PR with this new action if you'd like.

**Comment by kristijanhusak** [comment]
This should work:

```vimL
nnoremap <silent><buffer><expr> <CR> defx#is_directory() ? defx#do_action('open_or_close_tree') : defx#do_action('drop')

```

**Comment by Psykopear** [comment]
Yes, it work! Thanks kristijanhusak, I'm closing the issue then
