### ISSUE TITLE
Wired character in defx

### ISSUE THREAD

**Issue by amikai** [Shougo/defx.nvim#154]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
1. When i open defx window first time, there are  || and ** character like following. But open the defx window second time (toggle three time), it will work normally
![image](https://user-images.githubusercontent.com/13815956/63221619-49f92800-c1ce-11e9-86c7-938a6e2901fe.png)

2. When i use visual mode in defx, there are || and ** character like following
![image](https://user-images.githubusercontent.com/13815956/63221604-2930d280-c1ce-11e9-9ad0-328152732ee9.png)

## Environment Information

 * defx version(SHA1):
89c7594eeab887408555ba001fe29ab95a80ac80
 * OS:
OSX
 * neovim/Vim version:
```
amikai$ nvim -v
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/build/config -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/build/src/nvim/auto -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.7_2/share/nvim"
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_add = '''
    nnoremap <silent><F4> :<C-u>Defx<CR>
'''
```

**Comment by Shougo** [comment]
Please see this.

https://github.com/Shougo/defx.nvim/issues/144

**Comment by Shougo** [comment]
> When i use visual mode in defx, there are || and ** character like following

This is the feature to highlight filenames properly.
No magic.

**Comment by amikai** [comment]
But when i open first time, i haven't used the visual mode, there are || and ** characters too.

**Comment by Shougo** [comment]
Have you read the issue template and other issues?

> **Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

Please read this.

```
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_add = '''
    nnoremap <silent><F4> :<C-u>Defx<CR>
'''
```

You configuration is not reproduce-able for me.
So I can ignore/close your issue.

**Comment by Shougo** [comment]
You *must* create the minimal configuration to reproduce the problem.
If not, I will ignore your issue.

**Comment by Shougo** [comment]
defx use conceal feature to characters.  I think it is overwritten.
You should check conceallevel in defx buffer.

```vim
verbose setlocal conceallevel? concealcursor?
```

**Comment by amikai** [comment]
After `verbose setlocal conceallevel? concealcursor?` , i found that  'Yggdroot/indentLine' set conceallevel. thanks.

**Comment by Shougo** [comment]
OK.  So this is the conflict with indentLine plugin.
You should execute IndentLinesDisable in defx buffer.

**Comment by amikai** [comment]
OK, thanks.
