### ISSUE TITLE
defx does not support sftp(scp) 

### ISSUE THREAD

**Issue by cocobear** [Shougo/defx.nvim#159]
# Problems summary
When I edit file on remote server with command:
`vim sftp://pi@192.168.1.171/html/safe/public/index.php`

open defx will get error:

## Environment Information

 * defx version(SHA1): e4259b3cbe88163eb553fd6207b5755b9a04ff26

 * OS: macOS 10.13.6

 * neovim/Vim version: NVIM v0.4.0-dev

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

Here is my vimrc files;
[.vimrc](https://github.com/cocobear/dotfiles/blob/master/.vimrc)

## The reproduce ways from neovim/Vim starting (Required!)

 1. vim sftp://pi@192.168.1.171/html/safe/public/index.php
 2. vim command : ::Defx `expand('%:p:h')`
 

## Upload the log file
> Error invoking '_defx_start' on channel 4 (python3-rplugin-host):
> error caught in request handler '_defx_start [[['sftp://pi@192.168.1.171/html/safe/public'], {'columns': 'git:indent:icon:icons:filename:type', 'auto_cd': 0, '
> prev_bufnr': 1, 'root_marker': '\ufb0c ', 'resume': 0, 'auto_recursive_level': 0, 'sort': 'filename', 'listed': 0, 'new': 0, 'ignored_files': '.*', 'direction'
> : 'topleft', 'visual_end': 0, 'winheight': 30, 'profile': 0, 'search': 'sftp://pi@192.168.1.171/html/safe/public/index.php', 'buffer_name': 'default', 'winwidt
> h': 32, 'split': 'vertical', 'visual_start': 0, 'cursor': 17, 'winrelative': 'editor', 'prev_winid': 1000, 'wincol': 39, 'winrow': 17, 'session_file': '', 'sho
> w_ignored_files': 1, 'drives': [], 'toggle': 0}]]':
> Traceback (most recent call last):
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 36, in start
>     self._rplugin.start(args)
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 32, in start
>     views[0].init(paths, context, self._clipboard)
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 51, in init
>     if not self._init_defx(paths, clipboard):
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 379, in _init_defx
>     self.redraw(True)
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 137, in redraw
>     self._init_candidates()
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 563, in _init_candidates
>     defx._mtime = root['action__path'].stat().st_mtime
>   File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1168, in stat
>     return self._accessor.stat(self)
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/cocobear/code/safe/public/sftp:/pi@192.168.1.171/html/safe/public'
> 
> ## Expected
>

**Comment by Shougo** [comment]
Yes.  It is not supported now.

And it is not easy feature to implement.

**Comment by TeoDev1611** [comment]
I think this could serve you, it is not native but it would serve you https://github.com/matsui54/defx-sftp

**Comment by Shougo** [comment]
I need ssh source though...

**Comment by matsui54** [comment]
Thanks for introducing my plugin.
This plugin is under development. For now, you can view and operate (remove, move, copy and create) remote files. Exchanging files between remote and local is not implemented now (this will need modifying defx's source code).
Though I'm busy now, I will work on that before long.
