### ISSUE TITLE
Line number settings not working for latest NeoVim when Defx is started on VimEnter

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#160]
# Problems summary

I have a VimEnter autocmd that starts the Defx when i open vim. It worked out fine, but today after i updated Neovim to latest nightly version I noticed it is not respecting my number and relativenumber settings. 
It doesn't show numbers in defx buffer, which is fine, but it also doesn't show numbers in other windows after i open the file.

It works fine in latest stable neovim (0.38), so it is a potentially a neovim issue.

Edit: Also, not sure if it helps, but it is not happening with NerdTree.

## Expected
Expect to respect my number settings for other buffers

## Environment Information

 * defx version(SHA1): 4be6dbe8953488bfab425fc647e357945194b73d (currently latest)

 * OS: Manjaro linux

 * neovim/Vim version: NVIM v0.4.0-1961-g632ee8d2e

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#defx#check                                                                                                      
========================================================================                                               
## defx.nvim                                                                                                           
  - OK: has("python3") was successful                                                                                  
  - OK: Python 3.6.1+ was successful   
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
set number
set relativenumber
autocmd VimEnter * Defx
autocmd FileType defx nnoremap<silent><buffer><expr> <CR> defx#do_action('drop')
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open up neovim in any folder (from terminal `nvim .`)
 2. Go to some file, open it with Enter
 3. See the missing line numbers

Temporary fix:

```vim
autocmd BufEnter * if &ft !=? 'defx' && !&nu | set nu | endif
```

**Comment by Shougo** [comment]
> It works fine in latest stable neovim (0.38), so it is a potentially a neovim issue.

Yes.  neovim have changed the behavior.
It may be intended, but it is not compatible with Vim's behavior.

https://github.com/neovim/neovim/pull/9110

This is the bad commit.

**Comment by Shougo** [comment]
I have added workaround for the problem.
