### ISSUE TITLE
Buffer does not get updated when windows is resized

### ISSUE THREAD

**Issue by pwntester** [Shougo/defx.nvim#164]
## Problems summary
When Defx is openend in a vertical split, file names may get truncated. If window is resized, the filenames are not refreshed and they remain truncated to the same length.

## Expected
When window is resized, buffer is updated and filenames are expanded to the new buffer width.

## Environment Information

 * defx version(SHA1):
master

 * OS:
MacOS

 * neovim/Vim version:
NVIM v0.4.0-dev

**Comment by Shougo** [comment]
Sorry.  I don't want to add the feature.

**Comment by Shougo** [comment]
And Vim has not window resize event.

**Comment by wsdjeg** [comment]
Windows resized event should be added to neovim/vim. any exist issue about this feature?

**Comment by Shougo** [comment]
https://github.com/vim/vim/issues/3226

Not exists in neovim issues.

**Comment by wsdjeg** [comment]
Thanks

---

Best regards,
wsdjeg

**Comment by wsdjeg** [comment]
as people in that issue saied. we can tell defx the Windows is changed. and itself need to be resized.

my heck is: defx should provid a api to resize windows. for example:

defx#do_action('resize', 35)

then we can use statusline line function to update defx

--
Best regards,
wsdjeg

**Comment by kristijanhusak** [comment]
@wsdjeg you have redraw action, so if you can hook into resize event somehow, calling `defx#do_action('redraw')` should do the trick. Didn't test it though.

**Comment by pwntester** [comment]
Just tried it and it didnt work. But I agree that would be the best solution; to have a redraw action (not taking any width parameter since that should be calculated from defx buffer) and then have users to decide how to trigger it (shortcut, autocommand, statusline driven, etc.)

**Comment by pwntester** [comment]
I tried adding the following lines to the beginning of `redraw` function:

```
        width=self._vim.call('winwidth',0)
        self._vim.command('vertical resize %d' % width)
```

Now, redraw, respects new buffer width (previously it was resizing it to the original value stored in `context.winwidth`, but text is not redraw and remains truncated

**Comment by Shougo** [comment]
I have added "resize" action.

If you need to respect current width,

```
		max_width	  the maximum width of a defx buffer
				  If it is negative value, it means "winwidth *
				  max_width / 100".
				  (default: 100)
```

**Comment by pwntester** [comment]
Thank you Shougu San,


- having filename max_width to -1
- calling do_action(resize)
- and then calling do action(redraw)

**Comment by pwntester** [comment]
Sorry, my fault, I had to use `max_width=-100` instead and then it works.

The only thing not working is that when calling `do_action("redraw")` we get an error because buffer is not modifiable. Can you enable modification for the duration of the redraw action?

Thanks!

**Comment by pwntester** [comment]
Thanks @Shougo,

`nnoremap <silent><buffer><expr> z defx#do_action('resize',winwidth(0))` + `win_width=-90` works great for me

Cheers
