### ISSUE TITLE
Resize filename when resizing window and allow incremental resize

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#165]
Consider the following minimal init.vim file:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'show_ignored_files': 1,
            \ 'winwidth': 43,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ 'columns': 'mark:indent:icon:filename:icons:size',
            \ })
call defx#custom#column('indent', { 'indent': '  '})
call defx#custom#column('filename', {
            \ 'min_width': 23,
            \ 'max_width': 23,
            \ })

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:defx_settings()
    nnoremap <silent><buffer><expr> <A-l>  defx#do_action('resize', 50)
endfunction
```
Now, as in the GIF, do
1. Run `:Defx` in a directory that has a file with a long filename (in my case `asdasdasdasasdasdasdasdasdasdasdasdasddasad.txt`).
2. Press `<Alt-l>` to resize the defx window from 43 columns to 50

I have two questions/feature requests:
i) Is it possible to also resize the filename width when resizing the window? (i.e the general use case is that I would like to  resize the defx window to see the full filename instead of the truncated one)
ii) Can the resize action be "incremental" in the sense that we could run something like `defx#do_action('resize', '+10)` (or '-10')?

![defx-size](https://user-images.githubusercontent.com/2583971/65376333-0b470980-dc75-11e9-99ca-73feb0af3845.gif)

**Comment by Shougo** [comment]
> i) Is it possible to also resize the filename width when resizing the window? (i.e the general use case is that I would like to resize the defx window to see the full filename instead of the truncated one)

https://github.com/Shougo/defx.nvim/issues/164#issuecomment-533350836

Have you read the issue???
It is not defx's issue.  Vim8/neovim does not have the event.

**Comment by Shougo** [comment]
WinResized event seems listed in todo.txt Vim8.

**Comment by Shougo** [comment]
> ii) Can the resize action be "incremental" in the sense that we could run something like defx#do_action('resize', '+10) (or '-10')?

`defx#do_action('resize', winwidth(0) + 10)`

**Comment by petobens** [comment]
I should've read the issue. Sorry about that. Thanks
