### ISSUE TITLE
Defx sometimes does not restore sessions properly

### ISSUE THREAD

**Issue by 110y** [Shougo/defx.nvim#166]
## Problems summary

`add_session` saves sessions like below:

```json
{
  "/path/to/defx.nvim": {
    "name": "defx.nvim",
    "path": "/path/to/defx.nvim",
    "opened_candidates": [
      "/path/to/defx.nvim/autoload/defx",
      "/path/to/defx.nvim/autoload",
      "/path/to/defx.nvim/autoload/health"
    ]
  }
}
```

Since the order of `opened_candidates` seems to be not deterministic,
`defx` sometimes does not restore sessions properly.
For example with sessions like above, when I launch `Defx`,
it restores `/autoload/health` directory properly, however, it does not restore `/autoload/defx` directory like below.

```
- autoload/
  + defx/
  - health/
     defx.vim
    defx.vim
```

## Expected

`Defx` restores all `opened_candidates` properly.

## Environment Information

 * defx version(SHA1): `6da0c86`

 * OS: `macOS 10.14.6`

 * neovim/Vim version: `NVIM v0.5.0-dev: 0ab7da856`

 * `:checkhealth` or `:CheckHealth` result(neovim only): all `OK`.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" This assumes CWD is this repository.
set runtimepath+=./

function! s:map_defx_functions() abort
    nnoremap <silent><buffer><expr> O defx#do_action('open_tree_recursive')
endfunction

function! s:defx() abort
    call defx#util#call_defx('Defx', '-session-file=defx-session')
endfunction

autocmd BufLeave,BufWinLeave \[defx\]* silent call defx#call_action('add_session')
autocmd FileType defx call s:map_defx_functions()

command! D  call s:defx()

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open Defx by typing `:D`.
 2. Open `/autoload` directory recursively by typing `O`.
 3. Quit Vim by typing `:q`.
 4. Open Vim and Defx by typing `:D`.

Defx sometimes restores all `open_candidates` properly, but sometimes does not restore properly.

**Comment by 110y** [comment]
I tries to fix this problem and sent PR: https://github.com/Shougo/defx.nvim/pull/167

**Comment by Shougo** [comment]
Thanks.
