### ISSUE TITLE
Drop into current folder

### ISSUE THREAD

**Issue by chalmagean** [Shougo/defx.nvim#17]
It would be nice to have a way to jump to the current file or folder. I often edit a file and I want to create another in the same folder or just explore the folder where the current file is.

**Comment by kristijanhusak** [comment]
I created function for myself that does that, check here https://github.com/kristijanhusak/neovim-config/blob/defx/init.vim#L346

**Comment by chalmagean** [comment]
Stweet! Thank you.

**Comment by Shougo** [comment]
`Defx `expand('%:p:h')` -search=`expand('%:p')``
