### ISSUE TITLE
Can't update opened Defx buffers to syncronize file git status automatically when changing file

### ISSUE THREAD

**Issue by cjun714** [Shougo/defx.nvim#170]
# Problems summary
I use kristijanhusak/defx-git to display file git status.
I open defx as tree parking on left side, and then I modify file and save it , but defx tree will not update its status automatically.
I need to enter defx buffer and press 'r' which binding `defx#do_action('redraw')` to refresh, then defx tree can update to newest git status. 

I try to use `autocmd BufWrite` to solve it, but it doesn't work:
``` vimscript
autocmd BufWrite * call defx#do_action('redraw')
```

Could you please kindly give some guide for this? 
Thanks a lot.

## Expected
After I  changing file, all the opened defx buffers can be updated(redraw) automatically. 

## Environment Information

 * defx version(SHA1): Newest 442fda4ab39a340052c173e414e03e10eb0c8244

 * OS: LinuxMint 19.1

 * neovim/Vim version: neovim v0.4.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
map <A-w> :call DefxTree()<CR>
autocmd BufWrite * call defx#do_action('redraw')

function! DefxTree() abort
  call s:defx_option_tree()
  :Defx
endfunction

function! s:defx_option_tree() abort
  call defx#custom#option('_', {
    \ 'columns': 'git:indent:icons:filename:size:time',
    \ 'winwidth': 23,
    \ 'split': 'vertical',
    \ 'direction': 'topleft',
    \ 'show_ignored_files': 0,
    \ 'ignored_files':'.*,*.png,*.hdr,bin,pkg',
    \ 'buffer_name': 'defx_tree',
    \ 'toggle': 1,
    \ 'resume': 1,
    \ })
endfunction

autocmd FileType defx call s:defx_setting()
function! s:defx_setting() abort
  setl cursorline
  setl nospell
  setl signcolumn=no
  setl nonumber
  call s:preventKeys()
  nnoremap <silent><buffer><expr> o
  \ defx#is_directory() ?
  \ defx#do_action('open_or_close_tree') : defx#do_action('drop',)
  nmap <silent><buffer><expr> <2-LeftMouse>
  \ defx#is_directory() ?
  \ defx#do_action('open_or_close_tree') : defx#do_action('drop',)
  nnoremap <silent><buffer><expr> ma defx#do_action('new_file')
  nnoremap <silent><buffer><expr> mA defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> md defx#do_action('remove')
  nnoremap <silent><buffer><expr> mm defx#do_action('rename')
  nnoremap <silent><buffer><expr> vs
  \ defx#is_directory() ?
  \ defx#do_action('open_tree') : defx#do_action('open', 'vsplit')
  nnoremap <silent><buffer><expr> sp
  \ defx#is_directory() ?
  \ defx#do_action('open_tree') : defx#do_action('open', 'split')
  nnoremap <silent><buffer><expr> O defx#do_action('open_tree_recursive')
  nnoremap <silent><buffer><expr> P defx#do_action('paste')
  nnoremap <silent><buffer><expr> r defx#do_action('redraw')
  nnoremap <silent><buffer><expr> . defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> ss defx#do_action('toggle_select')
  nnoremap <silent><buffer><expr> zz defx#do_action('quit')
  nnoremap <silent><buffer><expr> <Esc> defx#do_action('quit')
  nnoremap <silent><buffer><expr> q defx#do_action('quit')
endfunction

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open a Defx buffer.
 2. Modify file and save it.
 3. Defx buffer doesn't update automatically, unless enter it and call defx redraw.

## Screen shot (if possible)
When I modify file, left and right defx buffer will not update automatically.
For normal defx buffer(like right one) it's not an problem, since it's just used to open file, so it will open/close frequently, every time I open it will get newest status of all files.
But for left defx tree, it will be always kept parking, so it need to track newest file status.
![1](https://user-images.githubusercontent.com/12163580/67545077-6f546600-f72a-11e9-804c-6ccd7b894bea.jpg)

Need manually trigger status update after changing file
![2](https://user-images.githubusercontent.com/12163580/67545095-7c715500-f72a-11e9-807d-0a97c7b10f33.jpg)

**Comment by kristijanhusak** [comment]
Defx window needs to be focused when calling redraw.

**Comment by Shougo** [comment]
Yes.  The feature is not supported now.

**Comment by Shougo** [comment]
@cjun714 Please test https://github.com/Shougo/defx.nvim/pull/171.

**Comment by cjun714** [comment]
@Shougo  it works perfectly with `autocmd BufWritePost * call defx#redraw()`.
All opened defx buffers can be updated automatically now.

Thanks so much!

**Comment by kristijanhusak** [comment]
Great, i'll probably add this to the git plugin so it is done automatically.

**Comment by Shougo** [comment]
OK.  Merged.

**Comment by kristijanhusak** [comment]
@cjun714 just a note that this is now added in the git plugin, so you don't need to add it yourself.

**Comment by cjun714** [comment]
@kristijanhusak thanks for inform.
I have update you newest git plugin, it works perfectly, thank you!
