### ISSUE TITLE
Error '[defx] defx requires Python3 support("+python3")' on Windows10, Vim8

### ISSUE THREAD

**Issue by EtiamNullam** [Shougo/defx.nvim#172]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

I'm getting this error on `:Defx` command run:
```
[defx] defx requires Python3 support("+python3").
```
Vim is compiled with `Python3`, `pynvim` is installed. It works fine on NeoVim.

## Expected

Vim8 should be able to run `:Defx`.

## Environment Information

 * defx version(SHA1): commit SHA-1: 0a42be58745b2b0a19f6d59ca6238d1dfc96a07b

 * OS: Win10 x64

 * neovim/Vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2019 23:02:14)

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:python3_host_prog = '~\AppData\Local\Programs\Python\Python38\python.exe'

call plug#begin('~/.vim-plug')
	Plug 'Shougo/defx.nvim'
	Plug 'roxma/nvim-yarp'
	Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Start Vim8
 2. Run `:Defx`
 3. Get error

## Screen shot (if possible)

![image](https://user-images.githubusercontent.com/10875340/68193689-c6243000-ffb3-11e9-9372-d59cef79e68c.png)

## Upload the log file

[vimLog.txt](https://github.com/Shougo/defx.nvim/files/3808191/vimLog.txt)

**Comment by Shougo** [comment]
Please upload `:messages` result.

**Comment by Shougo** [comment]
> Vim is compiled with Python3, pynvim is installed. It works fine on NeoVim.

Really?  I have checked the implementation, `!has('python3')` seems 0.

You should check `:echo has('python3')` result.

**Comment by Shougo** [comment]
`python3/dyn` is not means "Python3 support is enabled".
It means "Python3 support is loaded dynamically".
It does not guarantee "Python3 support works".

**Comment by EtiamNullam** [comment]
You're right, thanks for clarification. I've misinterpreted `+python3/dyn` assumed it was as good as `+python3`.

I guess I was fooled a bit by this (https://github.com/roxma/nvim-yarp#requirements):

```
g:python3_host_prog pointed to your python3 executable [...]
```

When it seems like `g:python3_host_prog` is mainly used in `nvim`. On Vim8 I had to use these two:

```
set pythonthreehome=~\AppData\Local\Programs\Python\Python38
set pythonthreedll=~\AppData\Local\Programs\Python\Python38\python38.dll
```

Actually I still had to set `g:python3_host_prog` for `https://github.com/roxma/nvim-yarp`.

I've ran into two minor issues after that, but that's my final, working, minimal rc (Vim8):

```
set encoding=utf-8

let g:python3_host_prog = expand('~\AppData\Local\Programs\Python\Python38\python.exe')

set pythonthreehome=~\AppData\Local\Programs\Python\Python38
set pythonthreedll=~\AppData\Local\Programs\Python\Python38\python38.dll

call plug#begin('~/.vim-plug')
	Plug 'Shougo/defx.nvim'
	Plug 'roxma/nvim-yarp'
	Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()
```
![image](https://user-images.githubusercontent.com/10875340/68266156-82cacf80-004e-11ea-9e72-e19942a74bac.png)



Sorry for taking your time.

**Comment by Shougo** [comment]
OK.  The problem is fixed.
