### ISSUE TITLE
Opening defx when running `:e /some/directory/`

### ISSUE THREAD

**Issue by daveyarwood** [Shougo/defx.nvim#175]
Hi, apologies for not using your issue template! This is more of a question that I'm hoping for a quick answer to so that I can close this and file a more detailed issue if necessary.

I recently switched over to defx from vimfiler and I'm enjoying it, but I noticed that one feature of vimfiler appears to be missing in defx: the behavior where if you run `:e /path/to/some/directory`, vimfiler would open in that directory.

A variant of this is that if you ran `vim /path/to/some/directory` at the command-line, Vim would open and display vimfiler in that directory.

I'm not actually 100% sure that vimfiler provided this functionality, or if it was baked into Vim somehow that Vim would open a file explorer if you provide a directory as the argument to `:e`. Do you know where this behavior was coming from, and how I might be able to implement it with defx?

**Comment by Shougo** [comment]
Sorry.  It is not supported.
I don't want to add it in defx.

Because, it is not easy to implement.

It hooks Vim's behavior.  So it is easy to conflict and break.

**Comment by daveyarwood** [comment]
OK, that makes sense to me.

Would you mind pointing me to where it is implemented in vimfiler so that I can try and add something similar to my vimrc?

**Comment by Shougo** [comment]
You can add the feature in your vimrc instead.

**Comment by Shougo** [comment]
You need to check plugin/vimfiler.vim.

**Comment by daveyarwood** [comment]
I was able to re-implement this behavior as a straightforward autocmd:

```viml
function! s:defx_my_settings() abort
  " ... configure defx as per :help defx-examples ...
endfunction

function! s:open_defx_if_directory()
  let l:full_path = expand(expand('%:p'))
  if isdirectory(l:full_path)
    Defx `expand('%:p')`
  endif
endfunction

augroup defx_config
  autocmd!
  autocmd FileType defx call s:defx_my_settings()

  " It seems like BufReadPost should work for this, but for some reason, I can't
  " get it to fire. BufEnter seems to be more reliable.
  autocmd BufEnter * call s:open_defx_if_directory()
augroup END
```

**Comment by Deerhound579** [comment]
When I do this, I will have a useless buffer with the directory name in addition to the `defx` window. For those who encounter this problem, this is my fix. It might now be the best way to do it but works.
```vim
if isdirectory(l:full_path)
    execute "Defx `expand('%:p')` | bd" . expand('%:r') 
endif
```

**Comment by daveyarwood** [comment]
Good idea! I tested your change and it works like a charm. It's definitely nice not having those extra buffers floating around.

I'll edit my post above so that others can benefit.

For context, the lines in question used to be:

```viml
  if isdirectory(l:full_path)
    Defx `expand('%:p')`
  endif
```

**Comment by facadeproof** [comment]
Getting this error while triggering a `defx#do_action('quit')` on `~/.config` with the new approach
```
Error detected while processing function defx#call_action[7]..defx#util#rpcrequest:
line   18:
Error invoking '_defx_do_action' on channel 4 (python3-rplugin-host):
error caught in request handler '_defx_do_action [['quit', [], {'columns': 'indent:git:icons:filename', 'auto_cd': False, 'winrelative': 'editor', 'root_marker': '[in]: ', 'resume': 1, 'auto_recursive_level': 0, 'sort': 'filename', 'li
sted': 1, 'new': False, 'ignored_files': '.*', 'direction': 'topleft', 'visual_end': 0, 'winheight': 30, 'profile': False, 'search': '', 'buffer_name': 'default', 'winwidth': 30, 'prev_bufnr': 2, 'split': 'vertical', 'visual_start': 0,
 'cursor': 2, 'prev_last_bufnr': 2, 'prev_winid': 1000, 'wincol': 58, 'winrow': 22, 'session_file': '', 'show_ignored_files': 1, 'drives': [], 'toggle': 1}]]':
Traceback (most recent call last):
  File "/home/user/.local/share/nvim/plugged/defx.nvim/rplugin/python3/defx/__init__.py", line 39, in do_action
    self._rplugin.do_action(args)
  File "/home/user/.local/share/nvim/plugged/defx.nvim/rplugin/python3/defx/rplugin.py", line 44, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/home/user/.local/share/nvim/plugged/defx.nvim/rplugin/python3/defx/view.py", line 85, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/home/user/.local/share/nvim/plugged/defx.nvim/rplugin/python3/defx/action.py", line 59, in do_action
    action.func(view, defx, context)
  File "/home/user/.local/share/nvim/plugged/defx.nvim/rplugin/python3/defx/base/kind.py", line 201, in _quit
    view.quit()
  File "/home/user/.local/share/nvim/plugged/defx.nvim/rplugin/python3/defx/view.py", line 113, in quit
    self._vim.command('buffer ' + str(self._prev_bufnr))
  File "/home/user/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(bdelete):E94: No matching buffer for .config
```
