### ISSUE TITLE
questions about the hotkey define.

### ISSUE THREAD

**Issue by irreallich** [Shougo/defx.nvim#176]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I find a problem about the plugs defx, by the way, this plug is very good, I really love it.
I am not sure my issue is a bug or not. 
the defx run well on my vimrc, the only way is the hotkey define
I use the follow code to define the hotkey for all the plugs on my vim , this is one of the key define of my setting, I copied your example.
```vim
execute('nnoremap <silent><buffer><expr> <CR> defx#do_action("open")')
```
the following steps are working fine
1. use :defx to start defx
2. define the hotkeys 
the hotkey work fine

 it don't work on the following steps
1. make sure the defx has loaded by vim-plug,  and define the hotkey
2.use :defx to start defx
the hotkey don't work

I understand your example code the following, and it work on my side.
```vim
autocmd FileType defx call s:defx_my_settings()
```
But I hope to define the hotkey before cmd :defx,  is there anyway to do?
 
## Environment Information

 * defx version(SHA1):last version

 * OS:ubuntu

 * neovim/Vim version:8.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set nocompatible
let $AAA="/home/hjwang/work/config/vimrc.d/"
let $BBB="/home/hjwang/work/config/vimrc.d/plugged_vim8_linux/defx.nvim"
set runtimepath+=$AAA
set runtimepath+=$BBB

call plug#begin('/home/hjwang/work/config/vimrc.d/plugged_vim8_linux') 
  Plug 'Shougo/defx.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()

function! Test1()
  call plug#load('defx.nvim')
  call plug#load('nvim-yarp')
  call plug#load('vim-hug-neovim-rpc')
endfunction

execute('nnoremap <silent><buffer><expr> <CR> defx#do_action("open")')
```

## The reproduce ways from neovim/Vim starting (Required!)
I don't understand what means about the following '1', '2', '3', i just reproduce this issue on vim
 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
> But I hope to define the hotkey before cmd :defx, is there anyway to do?

It is not possible.
You need to define the hotkey in `autocmd FileType defx`.

You should learn why it does not work.  I am not teacher.

**Comment by Shougo** [comment]
> I am not sure my issue is a bug or not.

The issue is intended behavor.  It is not bug.
