### ISSUE TITLE
Example for is_directory needs to be corrected

### ISSUE THREAD

**Issue by mvphilip** [Shougo/defx.nvim#178]
Hello, Firstly this is a fantastic high quality plugin. Thank you very much for writing it and releasing
it.

This issue is minor. The documentation example for defx#is_directory() needs to be corrected.
The following is from the repo:

defx#is_directory()					*defx#is_directory()*
		Returns |v:true| if the current cursor candidate is directory.

		Example: >

		nnoremap <silent><buffer><expr> <CR>
		\ defx#is_directory() ?
		\ defx#do_action('**open**') :
		\ defx#do_action('multi', ['drop', 'quit'])

The true statement in bold needs to be changed to

		\ defx#do_action('**open_directory**') :

thank you,

-mp

**Comment by Shougo** [comment]
The fix is not needed though.  Because if it is directory, open action is same with open_directory action...
