### ISSUE TITLE
Random "not modifiable" error

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#179]
# Problems summary

First, I know i don't have minimum vimrc and steps to reproduce, but i'm not able to reproduce it always, it happens random to me.

I get this "not modifiable" error totally random. I'm posting screenshot of error, and steps how it happens to me.

## Environment Information

 * defx version(SHA1):f5c3a9d842843f1e4a636dcd6cedfec56e7cdb81

 * OS: Manjaro I3 Linux

 * neovim/Vim version: NVIM v0.5.0-68-gfe9d54f41

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
This happens in my day to day usage, totally randomly. I'm not able to reproduce it on purpose. Here's link to the file where i have all defx settings ,hope it will help [https://github.com/kristijanhusak/neovim-config/blob/master/nvim/partials/defx.vim](https://github.com/kristijanhusak/neovim-config/blob/master/nvim/partials/defx.vim)

## The reproduce ways from neovim/Vim starting (Required!)
I only know it happens when i try to open directory tree, i didn't manage to figure out reproducible steps.

## Screen shot (if possible)
![https://i.imgur.com/obhmJHe.png](https://i.imgur.com/obhmJHe.png)

**Comment by Shougo** [comment]
I don't reproduce the error.

> I get this "not modifiable" error totally random. I'm posting screenshot of error, and steps how it happens to me.

What action is executed before the error?

**Comment by kristijanhusak** [comment]
It looks like it's fixed, didn't happen for me today.
Thanks!

**Comment by Shougo** [comment]
OK.
