### ISSUE TITLE
Defx blank on initial opening

### ISSUE THREAD

**Issue by blayz3r** [Shougo/defx.nvim#180]
# Problems summary

:Defx command produces blank buffer on first try, works on second try

## Environment Information

 * OS: Windows 10

 * neovim/Vim version:
![image](https://user-images.githubusercontent.com/12205650/71385949-66f89a00-25b8-11ea-8ef3-d3ca431c394f.png)

**VIMRC**
```vim
call plug#begin('~/.vim/bundle') "plugins' root path

Plug 'Shougo/defx.nvim'
Plug 'kristijanhusak/defx-icons'
Plug 'kristijanhusak/defx-git'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'


" All of your Plugs must be added before the following line
call plug#end()            " required
```

## Screen shot (if possible) 

first time(**blank**)
![image](https://user-images.githubusercontent.com/12205650/71385810-b094b500-25b7-11ea-8361-47626232cdd2.png)

Second time(**works**):
![image](https://user-images.githubusercontent.com/12205650/71386616-0750bd80-25bd-11ea-841c-b9432f9a8d8e.png)

**Log**
![image](https://user-images.githubusercontent.com/12205650/71389219-8a781080-25c9-11ea-8e98-5fe92f84b6d2.png)

**Comment by Shougo** [comment]
The error messages are printed in the command line.
Please upload :messages result.

**Comment by blayz3r** [comment]
> 
> 
> The error messages are printed in the command line.
> Please upload :messages result.

done!

**Comment by Shougo** [comment]
OK. I get it.  It is defx-git error instead.
You should report the issue in defx-git repository.

**Comment by Shougo** [comment]
The error is reproduced in Vim8 only.
Reason: https://github.com/deoplete-plugins/deoplete-jedi/issues/237

**Comment by kristijanhusak** [comment]
@blayz3r can you confirm that everything is working without the `defx-git` column?

@Shougo why `vars.get()` is not working?

**Comment by blayz3r** [comment]
> 
> 
> @blayz3r can you confirm that everything is working without the `defx-git` column?
> 
> @Shougo why `vars.get()` is not working?

Yes, Defx works without git column. Thanks for the speedy response

**Comment by Shougo** [comment]
@kristijanhusak Because pynvim broke backward compatibility.
https://github.com/neovim/pynvim/pull/405
