### ISSUE TITLE
c + p + ctrl-c, window dead, no response any more

### ISSUE THREAD

**Issue by winkee01** [Shougo/defx.nvim#181]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Setting up with the example mappings. In defx window, I move cursor to a file, type c(copy file), then p(paste file), it show options as below: 

/path/to/file_abc already exists.  Overwrite?
(F)orce, (N)o, (R)ename, (T)ime, (U)nderbar:

Then, before typing any character, I press Ctrl-c trying to cancel, the terminal window become stuck and never respond, I have to forcibly close the iTerm2 terminal.

## Expected
Cancel the p[aste] action

## Environment Information

 * defx version(SHA1):4dc152a

 * OS:macOS 10.13.6

 * neovim/Vim version:vim8.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Fixed.
