### ISSUE TITLE
How can it replace netrw? such as when user `:split C:\Users\path\to\a\directory` it will use defx not netrw?

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#183]
Such as `:split C:\Users\path\to\a\directory`, `:find C:\Users\path\to\a\directory`, it will use defx not netrw? It looks like `nerdtree` can do it. Thanks!

**Comment by Shougo** [comment]
Sorry.  I don't want to add the feature.
vimfiler implements it though.

https://github.com/Shougo/defx.nvim/issues/175

**Comment by Freed-Wu** [comment]
same as <https://github.com/Shougo/defx.nvim/issues/121>
