### ISSUE TITLE
If user use defx to delete a readonly file will return permission error?

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#184]
OS: Windows 10
If user use defx to delete a readonly file, it will return permission error. User must restart vim as administrator to delete this file. Is there exists another method without restarting vim? Such as pop up a window to get the permission temporaryly?
Thank you a lot!

**Comment by Shougo** [comment]
This is not defx problem.  It is Windows problem.

You can use sudo software in Windows.
But defx does not support it.

**Comment by Freed-Wu** [comment]
It is no problem. User can `:call delete('path_which_user_wanna_delete')` to delete that readonly file. Just write some vimscript. A little bit of trouble but not very hard.
```
nnoremap <silent><buffer><expr> C
			\ defx#do_action('yank_path')
nnoremap <silent><buffer><expr> R
			\ defx#do_action('redraw')
nmap <silent><buffer> <LocalLeader>x C:call delete('<C-r>0', 'rf')<CR>R
```

Thank you!
