### ISSUE TITLE
[Plugin feature request] Add clipboard to context for columns

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#185]
Hi,

I would like to add a support in my [defx-icons](https://github.com/kristijanhusak/defx-icons) plugin to mark files that are selected for copy or move. 
I can't do that because i don't have access to the Clipboard or View from the Context provided to the Column. Can we add something to the Context so i can figure out if candidate is in the copy/move candidates list?

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by Shougo** [comment]
I have reverted the changes.  Because complexity and performance problems.

I have added view argument in hook functions.  Please use it instead.
