### ISSUE TITLE
Feature request: add copy and move icons to mark column

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#188]
Currently the `mark` column allows to set and customize icons for readonly and selected candidates. Is it possible to add icons for `copy` and `move` actions? I think it's useful to have a visual indication of such actions. Thanks!

**Comment by kristijanhusak** [comment]
@petobens you have that as part of https://github.com/kristijanhusak/defx-icons, but it's not working super smoothly. It requires redraw to be indicated. Give it a try.

**Comment by petobens** [comment]
Hi @kristijanhusak thanks for the pointer but I was asking if this could be added natively to defx own `marker` column (I do use defx-icons but I use it combined with but not as a replacement of the marker column).

**Comment by Shougo** [comment]
Sorry.  I don't want to add the feature natively.

**Comment by petobens** [comment]
Ok.
