### ISSUE TITLE
defx#do_action('drop') or defx#do_action('drop', 'split') sometimes make vim stucked

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#190]
e.g.
![e](https://user-images.githubusercontent.com/32936898/74601567-8f91a180-50da-11ea-9f76-8b950583381f.gif)

gvim will get stucked util be forced to quit.

![e](https://user-images.githubusercontent.com/32936898/74601628-2eb69900-50db-11ea-9b09-1e2b243839ae.gif)

this is vimrc.

```
set nocompatible
set runtimepath+=$GITHUBWORKSPACE/roxma/nvim-yarp
set runtimepath+=$GITHUBWORKSPACE/roxma/vim-hug-neovim-rpc
set runtimepath+=$GITHUBWORKSPACE/Shougo/defx.nvim
set runtimepath+=$GITHUBWORKSPACE/mhinz/vim-signify
set runtimepath+=$GITHUBWORKSPACE/Yggdroot/LeaderF
autocmd FileType defx nnoremap <buffer><expr> go
			\ defx#do_action('drop')
autocmd FileType defx nnoremap <buffer><expr> gi
			\ defx#do_action('drop', 'split')
```

OS: gentoo/Linux
vim: gvim8.2

this error never appear in windows OS 10.
there exists other circumustances to encouter this error.
and `defx#do_action('multi', [['drop', 'split'], 'quit'])` will not trigger this error. cheers.

**Comment by Shougo** [comment]
```vim
set runtimepath+=$GITHUBWORKSPACE/mhinz/vim-signify
set runtimepath+=$GITHUBWORKSPACE/Yggdroot/LeaderF
```

They are needed to reproduce?
I need real minimal vimrc.

**Comment by Shougo** [comment]
And please upload the reproduce instructions.
If not, I need to close the issue.

**Comment by Shougo** [comment]
And have you tested the vimrc in the screenshot?
I have tested it and not highlights.

**Comment by Shougo** [comment]
I have tested it in Vim8 and it is not reproduced for me.
If you don't reply, I will close the issue.

**Comment by Freed-Wu** [comment]
syntax highlight is because `/etc/vim/vimrc`(the default system vimrc). I copy one line from system vimrc to test vimrc then delete the system vimrc. (in gif, i `:scriptnames` to display `/etc/vim/vimrc` have not be sourced.)

```
set nocompatible
filetype plugin on
set runtimepath+=$GITHUBWORKSPACE/roxma/nvim-yarp
set runtimepath+=$GITHUBWORKSPACE/roxma/vim-hug-neovim-rpc
set runtimepath+=$GITHUBWORKSPACE/Shougo/defx.nvim
set runtimepath+=$GITHUBWORKSPACE/mhinz/vim-signify
set runtimepath+=$GITHUBWORKSPACE/Yggdroot/LeaderF
autocmd FileType defx nnoremap <buffer><expr> go
			\ defx#do_action('drop')
autocmd FileType defx nnoremap <buffer><expr> gi
			\ defx#do_action('drop', 'split')
```

before test, I 

```
cd /home/wzy/.config/nvim
mv init.vim init.vim.bak
touch init.vim
touch empty.txt
```

that edit init.vim as example.

and need

```
cd /home/wzy/.vim
ln -s /home/wzy/.config/nvim/init.vim vimrc
```

(in gif i `cd .vim` and `ls -al` to display it)

my vim is 8.2.0114(i `:version` to display it)

I use `ttyrec` and `ttygif` to record a gif. 

open vim, then `Defx /home/wzy/.config/nvim`, then move cursor at line where `init.vim` at, press `gi` to see `init.vim` its content is as above example. then move cursor to `empty.txt`, press `gi`, vim will get stucked. i have to close this terminal by force. the ttyrec stop together.

![tty](https://user-images.githubusercontent.com/32936898/74605743-b1544e00-5105-11ea-84dc-3d1fd62d793a.gif)

the error is very strange. at first, i `drop` some file in defx will get vim stucked. so after backup my init.vim to init.vim.bak, i spend a bit time to delete many lines in my original init.vim to get the minimal vimrc. the map about `go` is spare but for true i leave it. except `go`, deleting any line will make the gvim cannot get stucked. especially that two plugins. if you can reproduce this error it will be good. if can not i will try to use `defx#do_action('multi', [['drop', 'split'], 'quit'])` to replace `defx#do_action('drop', 'split')` to avoid this error. and this error never appear in Windows OS 10. it confused me.

**Comment by Shougo** [comment]
```
set runtimepath+=$GITHUBWORKSPACE/mhinz/vim-signify
set runtimepath+=$GITHUBWORKSPACE/Yggdroot/LeaderF
```

The plugins are really needed??
Please answer my question.

**Comment by Freed-Wu** [comment]
yes, and directory `/home/wzy/.config/nvim/` must be deposited by git before test. i copy `init.vim` to other directory without deposition of git, test again will not see exclamatory mark on the left provided by signify, and the error will not appear, too.

![2020-02-17 11-52-26 的屏幕截图](https://user-images.githubusercontent.com/32936898/74622515-19457b80-517c-11ea-8488-85b45fe0ff7d.png)

and don't load plugin Leaderf will not result in this error. i test. it looks like they all don't have problem, but when they be loaded together, vim get stucked probably.

**Comment by Shougo** [comment]
OK.  I get it.
But your instruction is not reproducible for me.
I will rewrite your instruction.
Please wait.

**Comment by Shougo** [comment]
I have cloned your configuration repository.
https://github.com/Freed-Wu/myInit.vim

```
cd ~/src/myInit.vim
mv init.vim init.vim.bak
touch init.vim
touch empty.txt
```

that edit init.vim as example.

```
cd /src/myInit.vim
ln -s ~/src/myInit.vim/init.vim vimrc
```

**Comment by Shougo** [comment]
```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/
set runtimepath+=~/src/vim-signify
set runtimepath+=~/src/LeaderF

filetype plugin indent on

" Remap leader key to ,
let g:mapleader=','
nnoremap <leader>g :<C-u>Denite grep:. -no-empty<CR>

autocmd FileType defx nnoremap <buffer><expr> go
			\ defx#do_action('drop')
autocmd FileType defx nnoremap <buffer><expr> gi
			\ defx#do_action('drop', 'split')
```

```
$ cd /src/myInit.vim
$ vim -Nu ~/test.vimrc
```

**Comment by Shougo** [comment]
```
1. open vim
2. Defx
3. move cursor at line where init.vim
4. press gi to see init.vim its content is as above example
5. move cursor to empty.txt, press gi
6. vim will get stucked. i have to close this terminal by force. the ttyrec stop together.
```

**Comment by Shougo** [comment]
I have created the instructions to reproduce, but it cannot be reproduced for me.
So I will close the issue later.

**Comment by Shougo** [comment]
Please don't use your configuration in `/home/wzy/.config/nvim/`.
It is not reproduce-able for me.

**Comment by Shougo** [comment]
No response.
I will close it later.
