### ISSUE TITLE
goes to last buffer if previous buffer doesn't exist anymore when defx quits

### ISSUE THREAD

**Issue by twen2000** [Shougo/defx.nvim#191]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
If the previous buffer doesn't exist anymore, when defx is closed, it should go back to last buffer if it exists, instead of creating a new buffer.

For example:
1. open two files: a and b
2. open defx
3. switch to buffer b
4. delete buffer b
5. type 'q' in defx
6. current behavior: a new buffer is created
    expected behavior: go to last buffer if exists

I have modified code tested, and ready. If you agree, I will checkin and create a pull request.

Thanks.

## Environment Information

 * defx version(SHA1):

 * OS:

 * neovim/Vim version:

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
OK.  Please send the PR.  I will check it.
