### ISSUE TITLE
How to go a subdirectory and let the subdirectory as the working directory of defx?

### ISSUE THREAD

**Issue by roachsinai** [Shougo/defx.nvim#195]
It's not a bug, but need help to set the defx!

`  nnoremap <silent><buffer><expr> p defx#do_action('multi', [['cd', '..'], 'change_vim_cwd'])`

Above mapping help me to seet the root of defx to the parent directory where I open Vim. But how to set it back? I read the doc.txt but faild to make it.

Thanks in advance!

**Comment by Shougo** [comment]
Please use `:Denite defx/history` to go back.

Note: you need to use denite plugin.

**Comment by Shougo** [comment]
I think you should use `-auto-cd` option.

**Comment by roachsinai** [comment]
While `-auto-cd` is not exactly I expected. I just want the reverse of `nnoremap <silent><buffer><expr> p defx#do_action('multi', [['cd', '..'], 'change_vim_cwd'])` -- it was supported to change the root of defx as the parent as current dir without option `-auto-cd`.

`-auto-cd` option will leads to each `open` action changing the root of defx.

**Comment by roachsinai** [comment]
`-auto-cd` works! Thanks a lot!
