### ISSUE TITLE
Defx exits when file is marked instead of opening directory

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#197]
Consider the following minimal `init.vim` file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:defx_settings()
    nnoremap <silent><buffer><expr> <CR>
        \ defx#is_directory() ? defx#do_action('open') :
        \ defx#do_action('multi', ['drop', 'quit'])
    nnoremap <silent><buffer><expr> <Space>
        \ defx#do_action('toggle_select') . 'j'
    nnoremap <silent><buffer><expr> c defx#do_action('copy')
endfunction
```
Now, as in the GIF, do:
1. Open nvim, run `:Defx ~/Desktop/bar` where the `/bar` directory has a file `bar.txt` and an inner `bar/` directory
2. Press `<Space>` on the `bar.txt` file to select it and then press `c` to copy it
3. Move to the `bar` directory and press `<CR>`

After 3. I expect `Defx` to get into (i.e open) the `bar` directory instead `Defx` exits

 
![Peek 2020-03-30 22-53](https://user-images.githubusercontent.com/2583971/77978903-90bd0d80-72d9-11ea-9331-fa710276faa6.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you!
