### ISSUE TITLE
Dynamic filename width

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#198]
Consider the following minimal `init.vim` file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 30,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
call defx#custom#column('filename', {
            \ 'min_width': 20,
            \ 'max_width': 20,
            \ })
nnoremap <C-l> <C-w>2>
```
Now, as in the  GIF, do
1. Open and run `:Defx ~/Desktop/bar` where in the `bar` directory you have a file with a really long name such as `asadjaslkdasdjaslkdasjdkladakl.txt`
2. Once in the Defx window press `<C-l>` to increase the  window width.

After 2. the Defx window width increases but the filename is still truncated. Can a new feature be added such that the filename width  also increase dynamically with the window width? (vimfiler had this behaviour)

![Peek 2020-03-30 22-53](https://user-images.githubusercontent.com/2583971/78046578-b552cd00-734d-11ea-9095-f37fe0e5f2fc.gif)

**Comment by kristijanhusak** [comment]
calling `redraw` action after resizing should help.

**Comment by Shougo** [comment]
@petobens 
Why don't you read the documentation and existing issues??

#164 #165

**Comment by Shougo** [comment]
```vim
call defx#custom#column('filename', {
            \ 'min_width': 20,
            \ 'max_width': -80,
            \ })
nnoremap <silent><expr> <C-l> defx#do_action('resize', winwidth(0)+2)
```

**Comment by petobens** [comment]
Sorry about that. Thanks

**Comment by petobens** [comment]
Using the minimal reproducible example:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

call defx#custom#option('_', {
            \ 'winwidth': 30,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
call defx#custom#column('filename', {
            \ 'min_width': 23,
            \ 'max_width': -80,
            \ })

augroup ps_defx
    au!
    au FileType defx call s:defx_settings()
augroup END

function! s:defx_settings()
    nnoremap <silent><buffer><expr> <A-l> defx#do_action('resize',
        \ defx#get_context().winwidth + 5)
endfunction
```
This is not longer working:

![defx](https://user-images.githubusercontent.com/2583971/103136570-48801f80-46a0-11eb-9057-61166cd2359d.gif)

Do I need to change this somehow? Or is it a bug?

**Comment by Shougo** [comment]
Please read the documentation.
I have changed the behavor.
Why don't you read the documentation changes??

```
COMPATIBILITY						*defx-compatibility*

2020-12-17
* "max_width_percent" is added instead of negative value of "max_width".
* "max_width" negative value sets max_width to current window width plus
  "max_width".
```

**Comment by Shougo** [comment]
Please also see https://github.com/Shougo/defx.nvim/pull/278

**Comment by petobens** [comment]
I did read the docs but I didn't understand the changes... Using:
```viml
call defx#custom#column('filename', {
            \ 'min_width': 23,
            \ 'max_width_percent': 55,
            \ })
```
seems to make the trick but I still don't get the any workings / possible combinations of these settings. Anyways thanks for the help.

**Comment by Shougo** [comment]
Really?  Please wait.

**Comment by Shougo** [comment]
```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

augroup user_plugin_defx
  autocmd!
  " Define defx window mappings
  autocmd FileType defx call <SID>defx_mappings()
augroup END

function! s:defx_mappings() abort
  nnoremap <silent><buffer><expr> <C-l> defx#do_action('resize',
        \ winwidth(0) + 2)
endfunction

call defx#custom#option('_', {
            \ 'winwidth': 30,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
call defx#custom#column('filename', {
            \ 'min_width': 23,
            \ 'max_width_percent': 80,
            \ })
```

It works for me.
If you press `<C-l>`, the filename column will be extended.

> seems to make the trick but I still don't get the any workings / possible combinations of these settings. Anyways thanks for the help.

I don't understand.  We have not ESP skills.
I just ignore.

**Comment by petobens** [comment]
I meant that the docs were not clear about what `max_width_percent` represents (at least for me) and whether we should use it over or combined with `max_width`. Thanks for the help.

**Comment by Shougo** [comment]
You can improve the documentation.
The PR is welcome.
