### ISSUE TITLE
Set project title for file tree

### ISSUE THREAD

**Issue by Shougo** [Shougo/defx.nvim#2]
https://github.com/SpaceVim/SpaceVim/issues/1261

> I hope vimfiler provide a option to set the text. we can use a funcref as the value of the func. and call this func with one argv (path). then return the text which will be used as title.

**Comment by Shougo** [comment]
I think it should be another plugin "header".

**Comment by wsdjeg** [comment]
you mean issue label?

**Comment by Shougo** [comment]
No.  I have fixed the comment.
