### ISSUE TITLE
Defx -search not working

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#20]
# Problems summary
Defx search stopped working from commit https://github.com/Shougo/defx.nvim/commit/8b98842154344981f851e4de2ddcbc0561300995. Commits before work.

## Environment Information

 * defx version(SHA1): latest

 * OS: Linux mint 19

 * neovim/Vim version:
```
NVIM v0.3.2-dev
Build type: RelWithDebInfo
Lua 5.1
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/defx.nvim/
nnoremap <Leader>n :call DefxFindFile()<CR>

function! DefxFindFile() abort
  return execute(printf('Defx %s -search=%s', expand('%:p:h'), expand('%:p')))
endfunction
```

1. Open file
2. Press Leader n

It opens the right folder, but doesn't find the file.

**Comment by Shougo** [comment]
It is already fixed.
