### ISSUE TITLE
How to edit file in other buffer that loaded a file 

### ISSUE THREAD

**Issue by jinleileiking** [Shougo/defx.nvim#201]
I want open the file in the window right that had a file in it.
'open', 'vsplit' will open another buffer.

**Comment by jinleileiking** [comment]
I want to jump the window recently and edit the file in the window. I check the nerdtree codes. But no find.

**Comment by kristijanhusak** [comment]
@jinleileiking try `drop`.

**Comment by jinleileiking** [comment]
thanks . drop works fine @kristijanhusak
