### ISSUE TITLE
Nested empty folder on the same line

### ISSUE THREAD

**Issue by Andrflor** [Shougo/defx.nvim#207]
Hi,
First of all thanks a lot for that great plugin, I use it everyday :+1: 

Currently i'm mainly working on JVM based projects and package names have a lot of empty nested folders..

I  was wondering if it's possible to render that kind of folders all in one line, like github does.

Going from something like this
![image](https://user-images.githubusercontent.com/32484588/80825625-0e2db380-8be1-11ea-9862-7d28585fad9d.png)

To something like this
![image](https://user-images.githubusercontent.com/32484588/80825859-7da3a300-8be1-11ea-87e4-ff2bc86ca980.png)

I tried do it myself with config but got no result...

If you have any hint it would be really appreciated :smile:

**Comment by Shougo** [comment]
Sorry. defx does not have the feature.

I can implement the feature, but if I add the feature, you cannot operate files in nested directory.

For example you cannot add files in `src/main/java/org/hogehoge`.
