### ISSUE TITLE
Uppercase names cannot be changed to lowercase. Also, the reverse is not possible.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/defx.nvim#210]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Uppercase names cannot be changed to lowercase. Also, the reverse is not possible.

## Expected
It allows uppercase filenames to lowercase and vice versa.

## Environment Information

 * defx version(SHA1):667283ba8adab539eb90809cd8f3c22e7290fe24

 * OS:Mac

 * neovim/Vim version:v0.5.0-nightly-12-ga6be7a918

 * `:checkhealth` or `:CheckHealth` result(neovim only):OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
nnoremap <silent> F :<C-u>Defx -resume<CR>

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  nnoremap <silent><buffer><expr> c
    \ defx#do_action('copy')
  nnoremap <silent><buffer><expr> m
    \ defx#do_action('move')
  nnoremap <silent><buffer><expr> p
    \ defx#do_action('paste')
  nnoremap <silent><buffer><expr> o
    \ defx#do_action('open_or_close_tree')
  nnoremap <silent><buffer><expr> <CR>
    \ defx#do_action('open')
  nnoremap <silent><buffer><expr> <C-n>
    \ defx#do_action('new_multiple_files')
  nnoremap <silent><buffer><expr> C
    \ defx#do_action('toggle_columns',
    \                'mark:filename:type:size:time')
  nnoremap <silent><buffer><expr> D
    \ defx#do_action('remove')
  nnoremap <silent><buffer><expr> r
    \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> yy
    \ defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> .
    \ defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> l
	  \ defx#do_action('open')
  nnoremap <silent><buffer><expr> h
    \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> q
    \ defx#do_action('quit')
  nnoremap <silent><buffer><expr> j
    \ line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k
    \ line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> <C-l>
    \ defx#do_action('redraw')
  nnoremap <silent><buffer><expr> <C-g>
    \ defx#do_action('print')
  nnoremap <silent><buffer><expr> ~
    \ defx#do_action('change_vim_cwd')
endfunction
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open defx buffer.
 2. ```defx#do_action('new_multiple_files')```
 3. Input ```AAA```
 4. ```defx#do_action('rename')```
 5. Input```aaa```
 6. Error occurred```[defx] /Users/nabezokodaikon/workspace/develop-private/python-learning/chapter03/aaa already exists```

**Comment by Shougo** [comment]
Please check your file system.
Your file system(Mac) is really ignored case?

I think you should test to rename it by command line.

**Comment by Shougo** [comment]
Mac default filesystem(HFS+) ignores your case like Windows for compatibility.

**Comment by nabezokodaikon** [comment]
I confirmed that it was not case sensitive. This is not a problem with defx. We apologize for the inconvenience.

**Comment by nabezokodaikon** [comment]
But you did. Thank you!
