### ISSUE TITLE
some error about ctermfg

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#211]
i try to use nvim not vim recently. i found some error exists in nvim not vim. and to my suprise, this error is a Heisenberg bug -- sometimes it exists. sometime it doesn't exist.
when the error exists. `Defx` will get 

![image](https://user-images.githubusercontent.com/32936898/82858279-ffb78b00-9f45-11ea-9109-ae1ccdf62cf7.png)

the error appears randomly. so if i quit and restart neovim, this error usually does not appear. and i never met this error in vim with the same rc. i have no idea about this phenomenon.
Thanks!

**Comment by Shougo** [comment]
Please upload your configuration.
If not, I will close your issue.

It seems your column's(`git`) error.

**Comment by Freed-Wu** [comment]
you are right. it is related with columns. when i disable kristijanhusak/defx-icons the error will disappear.

**Comment by Shougo** [comment]
Hm...

**Comment by Shougo** [comment]
Please test the latest version of defx.
