### ISSUE TITLE
Sync defnvim and buffer

### ISSUE THREAD

**Issue by thevan96** [Shougo/defx.nvim#214]
# Problems summary
How to sync change width defxnvim and buffer 

## Expected
- when delete file in defxnvim -> delete buffer ( if file open or existed in buffer)
- when rename/chang directory file -> buffer rename/ change directory(if file open or existed in buffer )
## Environment Information

 * defx version(SHA1):

 * OS: Kubuntu (20.04)

 * neovim/Vim version: NVIM v0.5.0-dev

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#targets#check
========================================================================
  - OK: No conflicting mappings found

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=0).

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/thevan96/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/thevan96/.pyenv
  - INFO: Using: g:python3_host_prog = "/home/thevan96/.pyenv/shims/python3"
  - INFO: Executable: /home/thevan96/.pyenv/shims/python3
  - INFO: Python version: 3.8.3
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Disabled (g:loaded_ruby_provider=0).

## Node.js provider (optional)
  - INFO: Node.js: v12.18.0
  - INFO: Nvim node.js host: /home/thevan96/.nvm/versions/node/v12.18.0/bin/neovim-node-host
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

## Perl provider (optional)
  - INFO: Disabled (g:loaded_perl_provider=0).

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins'  }
Plug 'kristijanhusak/defx-git'
Plug 'kristijanhusak/defx-icons'
nnoremap <silent><leader>f :Defx -search=`expand('%:p')` -columns=indent:icon:mark:git:icons:filename:type -split=vertical -winwidth=35 -direction=topleft -show-ignored-files -resume<cr>
nnoremap <silent><leader>F :Defx -search=`expand('%:p')` -columns=indent:icon:mark:git:icons:filename:type -split=vertical -winwidth=35 -direction=topleft -show-ignored-files -toggle -resume<cr>

autocmd BufWritePost * call defx#redraw()
autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  call defx#custom#column('filename', {
        \ 'max_width': '100',
        \ 'min_width': '100'
        \})
  call defx#custom#column('icon', {
        \ 'directory_icon': '▸',
        \ 'opened_icon': '▾',
        \ 'root_icon': 'R',
        \ })
  call defx#custom#column('mark', {
        \ 'readonly_icon': '✗',
        \ 'selected_icon': '✓',
        \ })
  nnoremap <silent><buffer><expr> <cr>
        \ defx#do_action('drop')
  nnoremap <silent><buffer><expr> u
        \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> o
        \ defx#do_action('open_or_close_tree')
  nnoremap <silent><buffer><expr> ss
        \ defx#do_action('drop','split')
  nnoremap <silent><buffer><expr> sv
        \ defx#do_action('drop', 'vsplit')
  nnoremap <silent><buffer><expr> dd
        \ defx#do_action('remove_trash')
  nnoremap <silent><buffer><expr> D
        \ defx#do_action('remove')
  nnoremap <silent><buffer><expr> yy
        \ defx#do_action('copy')
  nnoremap <silent><buffer><expr> mv
        \ defx#do_action('move')
  nnoremap <silent><buffer><expr> p
        \ defx#do_action('paste')
  nnoremap <silent><buffer><expr> mk
        \ defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> t
        \ defx#do_action('new_file')
  nnoremap <silent><buffer><expr> T
        \ defx#do_action('new_multiple_files')
  nnoremap <silent><buffer><expr> R
        \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> q
        \ defx#do_action('quit')
  nnoremap <silent><buffer><expr> <tab>
        \ defx#do_action('toggle_select')
  nnoremap <silent><buffer><expr> *
        \ defx#do_action('toggle_select_all')
  nnoremap <silent><buffer><expr> a
        \ defx#do_action('toggle_select_visual')
  nnoremap <silent><buffer><expr> cl
        \ defx#do_action('clear_select_all')
  nnoremap <silent><buffer><expr> j
        \ line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k
        \ line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> yp
        \ defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> i
        \ defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> .
        \ defx#do_action('change_vim_cwd')
  nnoremap <silent><buffer><expr> rr
        \ defx#do_action('redraw')
endfunction
```
## Screen shot (if possible)
![Peek 2020-06-08 20-29](https://user-images.githubusercontent.com/47932916/84036035-dfb4ac80-a9c6-11ea-811d-86e1b69020ed.gif)

**Comment by Shougo** [comment]
> when delete file in defxnvim -> delete buffer ( if file open or existed in buffer)

Sorry.  I don't want to implement this.  It may be danger(You may lost the changes).

**Comment by Shougo** [comment]
> when rename/chang directory file -> buffer rename/ change directory(if file open or existed in buffer )

Implemented.

**Comment by Shougo** [comment]
Note: It does not support for directory rename.

**Comment by vitaly** [comment]
Hmm. I just checked and when I move the file into a different directory, the open buffer with the file doesn't change. if I save the buffer, it saves to the original path, before the move.

**Comment by Shougo** [comment]
The feature was not implemented for move action.
I have added it.  Please use the latest version.
