### ISSUE TITLE
defx is slower than nerdtree?

### ISSUE THREAD

**Issue by zgpio** [Shougo/defx.nvim#22]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Defx is slower than nerdtree, is this normal?

## Expected
I am fed up with nerdtree support for windows.
Then I try defx, I only compared the time to open defx and nerdtree, just to evaluate from subjective feelings.

## Environment Information

 * defx version(SHA1): latest

 * OS: win10

 * neovim/Vim version: vim8.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):

**Comment by Shougo** [comment]
> Defx is slower than nerdtree, is this normal?

No.  I have tested NERDTree performance already.
NERDTree is very slow.

NERDTree 15s in 10000 files
netrw 15s in 100000 files
Vaffle/dirvish 9.3s in 100000 files
defx 3s in 100000 files
vimfiler Infinity in 100000 files

**Comment by Shougo** [comment]
Note: I don't test defx's performance in Windows.

**Comment by Shougo** [comment]
NERDTree is slower than netrw/Vaffle/dirvish etc...

**Comment by zgpio** [comment]
OK, I will check it.

**Comment by Shougo** [comment]
defx needs to load Python.  It may be overhead in Windows.
But in huge directory, defx is faster.

**Comment by zgpio** [comment]
I understand.

**Comment by Shougo** [comment]
> I am fed up with nerdtree support for windows.

NERDTree does not support shellslash etc...

**Comment by zgpio** [comment]
Yes, that is  https://github.com/scrooloose/nerdtree/issues/860#issue-341393387.
