### ISSUE TITLE
[Feature Request] support image preview

### ISSUE THREAD

**Issue by glepnir** [Shougo/defx.nvim#220]
## Feature Request
@Shougo  Sorry for broken issue template.There doesn't have a feature request issue template.  I found this plugin [ipod825/vim-netranger](https://github.com/ipod825/vim-netranger/), It can show image by `ueberzug` a python lib.
Does defx.nvim can integrated it？

## Image
It looks like this.
![image](https://user-images.githubusercontent.com/41671631/85924522-73daab00-b8c5-11ea-9ac7-6261e3fa0928.png)

**Comment by Shougo** [comment]
Hm.  OK.  It can be supported.

**Comment by glepnir** [comment]
@Shougo  Thanks for work. but i don't get it work.. I had add the options. but nothing happen when i type `P` on a jpg file
```diff
@@ -42,6 +42,9 @@
       \ 'show_ignored_files': 0,
       \ 'columns': 'indent:git:icons:filename',
       \ 'root_marker': ' ',
+      \ 'floating_preview': 1,
+      \ 'vertical_preview': 1,
+      \ 'preview_height': 50,
       \ })

     call defx#custom#column('git', {
@@ -107,7 +110,7 @@
       nnoremap <silent><buffer><expr> st    defx#do_action('multi', [['drop', 'tabnew'], 'quit'])
       nnoremap <silent><buffer><expr> s     defx#do_action('open', 'botright vsplit')
       nnoremap <silent><buffer><expr> i     defx#do_action('open', 'botright split')
-      nnoremap <silent><buffer><expr> P     defx#do_action('open', 'pedit')
+      nnoremap <silent><buffer><expr> P     defx#do_action('preview')
```

**Comment by Shougo** [comment]
> env is macos.

Unfortunately, ueberzug is for X11 only.

Please read this.

https://github.com/seebye/ueberzug#dependencies

You should test the example at first.
https://github.com/seebye/ueberzug#examples

**Comment by glepnir** [comment]
I had install https://www.xquartz.org/. i will test example thanks.

**Comment by petobens** [comment]
I'm trying this out and also cannot seem to make it work. Following https://github.com/seebye/ueberzug/issues/101#issuecomment-636522366 I wrote the next `foo.sh` script which works just fine:
```bash
{
    declare -pA addCommand=([action]="add" [identifier]="example0" [x]="0" [y]="0" [path]="/home/pedro/Pictures/Screenshots/Screenshot_2020-04-12_13:43:01.png")
    sleep 5
} | ueberzug layer --parser bash
```
when ran using either `bash foo.sh` or `source foo.sh`.  On the other if I open defx and run the `preview` action on that same image candidate then the image is not shown.

**Comment by Shougo** [comment]
Really??

> if I open defx and run the preview action on that same image candidate then the image is not shown.

Why it works for me??

**Comment by glepnir** [comment]
It also works for me on linux.. can't get it on macos..

**Comment by Shougo** [comment]
I will test bash version.  Please wait.

**Comment by Shougo** [comment]
I have implemented bash version instead.  Please test.

**Comment by glepnir** [comment]
@Shougo  Ok wait.

**Comment by glepnir** [comment]
Also works.
![image](https://user-images.githubusercontent.com/41671631/85951207-3c86ff80-b994-11ea-9503-6b8c90cc2cc0.png)

**Comment by glepnir** [comment]
The gif show this feature. by the way only get it works on linux. seems like the x11 of xquartz can't work wit ueberzug on macos.
![test](https://user-images.githubusercontent.com/41671631/85951399-9a681700-b995-11ea-8e4c-63aaa75706a1.gif)

**Comment by Shougo** [comment]
Oh.  So ueberzug does not support MacOSX.
You can ask it on ueberzug's issues.

**Comment by glepnir** [comment]
@Shougo Don't care, x11 seems like died on macosx。so ueberzug doesn not suport OSX.  Thanks for your work again.

**Comment by Shougo** [comment]
Oh, OK.
I recommend for you to use Linux.

**Comment by petobens** [comment]
I does work now with the bash change thanks!. Is is possible to make the `sleep 5` configurable? With the current setting the preview is shown but disappears after 5 seconds (it might make sense for the be visible until the user decides to close it by either killing the preview action or changing candidates)

**Comment by Shougo** [comment]
> it might make sense for the be visible until the user decides to close it by either killing the preview action or changing candidates

Implemented.  But it is only works for neovim.
