### ISSUE TITLE
Nvim Hanging in Python Process

### ISSUE THREAD

**Issue by thecontinium** [Shougo/defx.nvim#222]
# Problems summary

Nvim Hangs in the python process

## Expected

Not to hang

## Environment Information

 * defx version(SHA1): latest

 * OS: MacOs

 * neovim/Vim version: HEAD

 * `:checkhealth` or `:CheckHealth` result(neovim only): ok

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

any 

## The reproduce ways from neovim/Vim starting (Required!)

```
cd /tmp
nvim
:Defx 
:e ~/foo.bar
:Defx `getcwd()` -search=`expand('%:p')` 
```

Nvim Hangs in the python process

This has only recently started to happen after an update.
If you need more just let me know.
Cheers

**Comment by Shougo** [comment]
Fixed.

**Comment by thecontinium** [comment]
cheers - it no longer hangs
