### ISSUE TITLE
Recreate vinegar behaviour

### ISSUE THREAD

**Issue by t0str** [Shougo/defx.nvim#226]
Hi

First and foremost thanks a lot, I am using a few plugins from you and am very happy about all of them!

Recently I switched to defx from vim-vinegar (which is basically just netrw on steroids). I was able to configure everything as I want it, just one thing I have not managed to do.

If I call `:Defx` while editing a file in a subdirectory, Defx displays my project root directory. `-auto-cd` helps a little bit, but I often open files via different means, and in these cases `-auto-cd` does not help. What I want to achieve is "always open the current file directory" when I enter Defx. Is there a way to do this? I looked at the documentation but I could not find a setting.

Thanks & Best
t0str

**Comment by Shougo** [comment]
It is already documented.

```
Q: I want to explore the folder where the current file is.

A: >
	Defx `expand('%:p:h')` -search=`expand('%:p')`
```

**Comment by t0str** [comment]
Thank you very much, I missed that in the docs!
