### ISSUE TITLE
Can't add count to function mapping to move between candidates

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#231]
Consider the following minimal `init.vim` file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

function! s:DefxUpdatePreview(dir, lines) abort
    execute 'normal! ' . a:lines . a:dir
endfunction

au FileType defx call s:defx_settings()

function! s:defx_settings()
    nnoremap <silent><buffer> j :call <SID>DefxUpdatePreview('j', v:count1)<CR>
    nnoremap <silent><buffer> k :call <SID>DefxUpdatePreview('k', v:count1)<CR>
endfunction
```
Now open vim and do:
1. Run `:Defx` to open a defx buffer
2. Press `3j` to move 3 lines down between candidates
3. Press `3k` to move 3 lines up between candidate

As it can be seen in the GIF after 3. the cursor only moves 1 line up (I expect it to move 3 lines).

![Peek 2020-07-14 14-54](https://user-images.githubusercontent.com/2583971/87459402-bac4e200-c5e1-11ea-88ac-f831d7b7d0b7.gif)

**Comment by Shougo** [comment]
This is defx issue really?
Your function does not call defx features!

**Comment by Shougo** [comment]
Reproduced.  It is not defx issue I don't know the reason though.

It works for me.

```vim
function! s:defx_settings()
    nnoremap <silent><buffer> j :<C-u>call <SID>DefxUpdatePreview('j', v:count1)<CR>
    nnoremap <silent><buffer> k :<C-u>call <SID>DefxUpdatePreview('k', v:count1)<CR>
endfunction
```

**Comment by Shougo** [comment]
The problem is reproduced in any buffers.

**Comment by petobens** [comment]
Thanks!
