### ISSUE TITLE
File becomes empty, when a file is closed and renamed by Defx rename

### ISSUE THREAD

**Issue by nyatsui** [Shougo/defx.nvim#232]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

First of all, thank you a lot for that wonderful plugin, I use it everyday.  
File becomes empty, when a file is closed and renamed by Defx rename.   

## Expected

Rename file keeping the contents.

## Environment Information

 * defx version(SHA1):

ea3563894e4a705bccc18094573105e21db203ec

 * OS:

macOS 10.15

 * neovim/Vim version:

NVIM v0.5.0-nightly-1421-g1ca67a73c

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```First of all, thank you a lot for that wonderful plugin, I use it every day

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let s:dein_cache_path = expand('~/.cache/nvim_dbg/dein')
let s:dein_dir = s:dein_cache_path .'/repos/github.com/Shougo/dein.vim'

if &runtimepath !~ '/dein.vim'
  if !isdirectory(s:dein_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_dir
  endif
  execute 'set runtimepath+=' . fnamemodify(s:dein_dir, ':p')
endif


if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)
  call dein#add('Shougo/Defx.nvim')
  call dein#end()
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
syntax enable

nnoremap <silent>   <Space>f
\ :<C-u>Defx -listed -resume -winwidth=200 -buffer-name=tab`tabpagenr()`<CR>

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>
 \ defx#async_action('open')
  nnoremap <silent><buffer><expr> r
 \ defx#do_action('rename')
endfunction
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. open test.txt and edit text.txt
 2. close this file by :bd 
 3. (open Defx by "\<Space\>f" and open test.txt. test.txt has same contents)
 4. open Defx by "\<Space\>f" and rename text.txt to text1.txt
 5. open text1.txt (this file is empty)

**Comment by Shougo** [comment]
Fixed.
