### ISSUE TITLE
How can i change the directory name color with the latest version defx

### ISSUE THREAD

**Issue by glepnir** [Shougo/defx.nvim#234]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

When update the latest version . the default highlight of directory name seems wired with my colorscheme. So I want to change it withe this option `hi Defx_filename_directory guifg=red`. but failed...

## Expected

change colorscheme .

## Environment Information

 * defx version(SHA1): latest

 * OS: macos 10.15.6

 * neovim/Vim version: neovim-0.5-nightly

 * `:checkhealth` or `:CheckHealth` result(neovim only):  Defx check is OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim

set runtimepath+=~/.cache/vim/dein/repos/github.com/Shougo/defx.nvim

filetype plugin indent on
syntax on

call defx#custom#option('_', {
  \ 'resume': 1,
  \ 'winwidth': 30,
  \ 'split': 'vertical',
  \ 'direction': 'topleft',
  \ 'show_ignored_files': 0,
  \ 'columns': 'mark:indent:git:icons:filename',
  \ 'root_marker': '[in]: ',
  \ })

hi Defx_filename_directory guifg=red
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. nvim - u mininit.vim
 2. Defx
 3.  color of directory name don't change.

**Comment by kristijanhusak** [comment]
@Shougo is there a way to know in column if nvim namespace is used? (`_ns` property in view) ? I don't want to add `syntax match` commands if not needed.

**Comment by Shougo** [comment]
> I don't want to add syntax match commands if not needed.

You don't need to check.  Because if namespace is used, the syntax is not defined.
Please use `highlight_commands` to define highlights.

**Comment by kristijanhusak** [comment]
@Shougo It's not working for me. I have to do same thing in the `__init__` that you do:
https://github.com/kristijanhusak/defx-icons/commit/434dd17a0026ed5c251a8aecd2f15a3e5e0639e1#diff-b6d162fcea11dc4aea1ae69031651cdaR28

**Comment by Shougo** [comment]
@kristijanhusak Really?  I need to test.
Please provide the reproduce instructions.

**Comment by glepnir** [comment]
@Shougo  It seems like does not work fine.

**Comment by Shougo** [comment]
@glepnir Please use the latest version.

> So I want to change it withe this option hi `Defx_filename_directory guifg=red`. but failed...

You should check the highlight name in defx buffer.

**Comment by kristijanhusak** [comment]
@Shougo nevermind, I fixed it. I cached syntax_name at beginning, it was wrong value.

**Comment by glepnir** [comment]
@Shougo  I had updated defx. i will check. @kristijanhusak   i also use defx-git  and defx-icons. maybe related?

**Comment by Shougo** [comment]
> @Shougo nevermind, I fixed it. I cached syntax_name at beginning, it was wrong value.

OK.

**Comment by glepnir** [comment]
@Shougo   Also use the mininit.vim. I used `:syntax` command in defx buffer. got `No syntax items defined in this buffer`

**Comment by Shougo** [comment]
OK

**Comment by glepnir** [comment]
another question.. what highlight of root path. i tried the `Defx_root` `Defx_root_directory`.

**Comment by Shougo** [comment]
Please check highlight command result.
Defx_filename_root_marker

**Comment by glepnir** [comment]
@Shougo   Not marker.  there
![image](https://user-images.githubusercontent.com/41671631/88455233-38bc9f00-cea6-11ea-9fc9-ee5b906bb59d.png)

**Comment by Shougo** [comment]
I have fixed it.
`Defx_filename_root`

**Comment by glepnir** [comment]
@Shougo .  Fixed when update defx. Thanks for work.
