### ISSUE TITLE
error about drop

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#238]
### test.vim

```{.vim}
" $XDG_CONFIG_HOME/test.vim
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/Shougo/defx.nvim
nnoremap <expr> ; defx#do_action('drop', 'split')
```

### Reproduce Procedures

in shell
```{.sh}
vi -u $XDG_CONFIG_HOME/test.vim
```

in vi
```{.vim}
" now working directory of this buffer is ~
Defx `$XDG_CONFIG_HOME` -split
lcd $XDG_CONFIG_HOME
" now working directory of defx is $XDG_CONFIG_HOME
" press ; in init.vim
" you will open an empty file ~/nvim/init.vim not $XDG_CONFIG_HOME/nvim/init.vim
" because the 2 buffers have differenet working directories
" i guess that some path variable should be absoluate path not relative path to solve this problem
```

### Environment

- vi: nvim 0.4.3
- OS: linux 5.4.13

**It is mime, although I think this problem should exist in other environments.**

**Comment by Freed-Wu** [comment]
this bug has appeared again.

## reproduce procedures

```{.vim}
" FILE: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" VI: nvim v0.4.3
" TERM: guake v3.7.0
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/Shougo/defx.nvim
autocmd VimEnter * Defx `$GITHUBWORKSPACE`/Shougo/defx.nvim -split=vertical
nnoremap <expr> i
			\ defx#is_directory() ?
			\ defx#do_action('open_or_close_tree') :
			\ defx#do_action('drop', 'split')
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

![Screenshot from 2020-09-04 10-55-26](https://user-images.githubusercontent.com/32936898/92194479-5b76a600-ee9d-11ea-961a-63953e98a3a6.png)

`<C-w>l:lcd $XDG_DATA_HOME/nvim`
![Screenshot from 2020-09-04 10-56-07](https://user-images.githubusercontent.com/32936898/92194512-747f5700-ee9d-11ea-889f-abd147b54f16.png)

`<CR><C-w>h4ji3j`

![Screenshot from 2020-09-04 10-56-24](https://user-images.githubusercontent.com/32936898/92194622-b8725c00-ee9d-11ea-81f2-c6ce7c69d4bc.png)

`i`

![Screenshot from 2020-09-04 10-56-45](https://user-images.githubusercontent.com/32936898/92194663-cfb14980-ee9d-11ea-804b-5da206807760.png)

vi will open an empty buffer. however, this file `test/conftest.py` is not empty.

**Comment by Shougo** [comment]
@dietrichm Please fix it.  If not, I will revert your changes.

**Comment by dietrichm** [comment]
Hello @Freed-Wu 

I tested my patch using your scenario and it fixed the bug for me.

Could you check whether it also happens with NVIM 0.5.0?

Dietrich

**Comment by Shougo** [comment]
I have added `haslocaldir()` check for it.

**Comment by dietrichm** [comment]
Thanks @Shougo, this seems like a valid fix to me. I'm glad we could keep the relative path behaviour in place.

Dietrich
