### ISSUE TITLE
exrename make file disappear

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#244]
```{.vim}
" FILE: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" VI: nvim v0.4.3
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/Shougo/defx.nvim
autocmd VimEnter * Defx ~/Desktop
nnoremap <expr> s defx#do_action('toggle_select') . 'j'
nnoremap <expr> r defx#do_action('rename')
nnoremap <expr> R defx#do_action('redraw')
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

![Screenshot from 2020-08-28 21-01-13](https://user-images.githubusercontent.com/32936898/91564092-a743bf80-e972-11ea-9c5a-e476c01a0b1f.png)

`7jss`

![Screenshot from 2020-08-28 21-01-43](https://user-images.githubusercontent.com/32936898/91564104-ae6acd80-e972-11ea-9f5e-f990afad624e.png)

`r`

![Screenshot from 2020-08-28 21-01-47](https://user-images.githubusercontent.com/32936898/91564119-b62a7200-e972-11ea-903d-027b1073726a.png)

`ddp`

![Screenshot from 2020-08-28 21-02-05](https://user-images.githubusercontent.com/32936898/91564152-c5112480-e972-11ea-90dc-67a308c34849.png)

`ZZR`

![Screenshot from 2020-08-28 21-02-16](https://user-images.githubusercontent.com/32936898/91564164-c80c1500-e972-11ea-9b5e-59952965a155.png)

you will not swap `test1` and `test2` in filename, but permanently lose `test2`.

**Comment by Shougo** [comment]
The swapping rename does not support in defx.
I will add the error check.
