### ISSUE TITLE
[feature] support of excommand

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#247]
just like exrename

e.g.

```{.vim}
nnoremap <buffer><expr> !!
			\ defx#do_action('command')
```
cursor stays in this line.

![image](https://user-images.githubusercontent.com/32936898/92323813-49982d00-f06e-11ea-8cdf-219f8d3a5dbf.png)

press `!!` and input some shell command.

![image](https://user-images.githubusercontent.com/32936898/92323827-5c126680-f06e-11ea-8147-6fdeb7ea672c.png)

press `<CR>` will execute `convert main.pdf main.png` to generate a new png file.

and

select 2 files

![image](https://user-images.githubusercontent.com/32936898/92323860-9d0a7b00-f06e-11ea-95b6-f504530c5fa6.png)

press `!!` will popup a new window

![image](https://user-images.githubusercontent.com/32936898/92323896-ebb81500-f06e-11ea-9fa2-ff3136ab8e01.png)

![image](https://user-images.githubusercontent.com/32936898/92323903-fd99b800-f06e-11ea-92f4-85ef341c8718.png)

press `ZZ` will init 2 new git repos. (syntax should be `&shell`)

moreover, syntax can be more languages, such as vim (Git is the command provided by <https://github.com/tpope/vim-fugitive>)

![image](https://user-images.githubusercontent.com/32936898/92323942-4ea9ac00-f06f-11ea-94b4-6bb05bae93ed.png)

and can support action args

```{.vim}
nnoremap <buffer><expr> !g
			\ defx#do_action('command', 'git init %')
```

when  user press `!g` will init git repos corresponding the selected files automatically.

just a rough and stupid though, thanks!

**Comment by Shougo** [comment]
> press !! will popup a new window

I reject the feature.  It is too complex feature.

**Comment by Freed-Wu** [comment]
> > press !! will popup a new window

i have a temporary solution:

```{.vim}
nnoremap <buffer><expr> <LocalLeader><LocalLeader>
			\ defx#do_action('call', 'defx#command#main')
```

```{.vim}
let s:temp = '/tmp/temp'
function! defx#command#main(context) abort "{{{
	execute 'vertical new ' . s:temp
	execute 'set filetype=' . fnamemodify(&shell, ':t')
	for l:target in a:context.targets
		0put=l:target
	endfor
	augroup defx_temp "{{{
		autocmd!
		execute 'autocmd BufLeave ' . s:temp . ' !source %'
		execute 'autocmd BufLeave ' . s:temp . ' call delete("' . s:temp . '")'
	augroup END "}}}
endfunction "}}}
```

![image](https://user-images.githubusercontent.com/32936898/92347631-4438f200-f103-11ea-9b75-eb49759ab46b.png)

it can work but i am not sure it always can work.

**Comment by Shougo** [comment]
`execute_command` action already exists.
