### ISSUE TITLE
[feature]support for `defx#do_action('cd', '-')`

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#248]
By now, `defx#do_action('cd', '-')` will change directory to a path named '-'.  can make it similarer a true `cd`? when
```{.shell}
cd -3
```

a true cd will change directory to the last 3 directory user accessed.

Thanks!

**Comment by Shougo** [comment]
I have tested and `cd -3` is not supported both Vim and neovim.
`cd -` is only supported.

**Comment by Shougo** [comment]
This is really useful??
You can track the history by `Denite defx/history`.

Please explain usage more clearly.

**Comment by resolritter** [comment]
As explained by this answer

https://unix.stackexchange.com/a/331197/357062

`cd -` is really a shorthand for `cd "$OLDPWD" && pwd`. It does not work like a "stack" like the idea in the proposal suggests, because it's a single variable. You can use it to bounce back-and-forth between **two** directories with `cd -`, but not go back in the history, because it does not represent a history.

**Comment by Shougo** [comment]
I think zsh supports the feature.

**Comment by Freed-Wu** [comment]
> As explained by this answer
> 
> https://unix.stackexchange.com/a/331197/357062
> 
> `cd -` is really a shorthand for `cd "$OLDPWD" && pwd`. It does not work like a "stack" like the idea in the proposal suggests, because it's a single variable. You can use it to bounce back-and-forth between **two** directories with `cd -`, but not go back in the history, because it does not represent a history.

you are right. perhaps
```{.vim}
nnoremap <buffer><expr> J
			\ defx#do_action('cd', defx#oldpwd())
```
will be better? looks like more reasonable than `defx#do_action('cd', '-')` because when a directory which name starts with '-' exists, we cannot use `cd -- -` to change directory to it in defx.

**Comment by Shougo** [comment]
OK.  If so, you should use `g:defx#_histories` for it.

**Comment by Freed-Wu** [comment]
Great,
```{.vim}
nnoremap <buffer><expr> J
			\ defx#do_action('cd', g:defx#_histories[-1][1])
```
looks like right.
