### ISSUE TITLE
[feature] support for action args of 'yank_path'

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#249]
```{.vim}
nnoremap <buffer><expr> C
			\ defx#do_action('yank_path')
```

can yank the path of selected files.

sometimes we only need one part of the path. can it support

```{.vim}
nnoremap <buffer><expr> C
			\ defx#do_action('yank_path', ':e')
```

except `:e`,  also contain other filename-modifiers supported by vim. such as `:t`, `:r`.

Thanks!

**Comment by resolritter** [comment]
`defx#get_candidate()['action__path']` should give you the full path to the item under the cursor, and from there you can do `fnamemodify`

not sure if that's public API, though... the name is a bit weird
