### ISSUE TITLE
No color in defx buffers after commit 01d597fc0ff13e2e187ace5dac79f2f3399a45e2

### ISSUE THREAD

**Issue by ljohnston** [Shougo/defx.nvim#251]
# Problems summary
This commit has broken colors in my defx buffers (i.e. all text in my defx buffers is a single color):  https://github.com/Shougo/defx.nvim/commit/01d597fc0ff13e2e187ace5dac79f2f3399a45e2

This only affects MacVim. Neovim still works as expected.

## Expected
Colors work as before that commit (i.e. I have color highlighting in my defx buffers). I feel like maybe there's something I need to change in my configuration, but I don't know what that is?

## Environment Information

 * plugin version(SHA1): 01d597fc0ff13e2e187ace5dac79f2f3399a45e2

 * OS: MAC OS

 * neovim/Vim version: 8.2.1456 (165)

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed
