### ISSUE TITLE
The indent of folder had missed when update to latest defx

### ISSUE THREAD

**Issue by glepnir** [Shougo/defx.nvim#253]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Seems like the new commit of defx cauesd? check the new commit just see use textpos and remove syntax. Don't know where caused.

## Expected

work like before?

## Environment Information

 * plugin version(SHA1): latest

 * OS: mac os

 * neovim/Vim version: 0.5-nightly

 * `:checkhealth` or `:CheckHealth` result(neovim only):  all is ok.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

No need.

## The reproduce ways from neovim/Vim starting (Required!)

1. use latest defx
2. opendefx

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/41671631/92863642-c04a7700-f42e-11ea-8a61-36d5a6724df1.png)

Now in defx.
![image](https://user-images.githubusercontent.com/41671631/92863581-add03d80-f42e-11ea-9e78-de14f8b14804.png)

**Comment by Shougo** [comment]
I get it.  It is the bug.  I will fix it later.

**Comment by Shougo** [comment]
Fixed.
