### ISSUE TITLE
[feature request] filter support

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/defx.nvim#255]
Sorry for do not use issue template. I think this is a feature request.

I hope defx support filter feature. This should be a action which can be used as key binding.

For example, only list the `*.test` files. This feature is useful for user to check the file layout for specific filetype.

and I know denite support filter feature. But it is different. denite do not support drawing file tree layout.

**Comment by wsdjeg** [comment]
awesome, Thanks. I will try to use it.

**Comment by wsdjeg** [comment]
@Shougo I have tested this feature. It seems do not word for files in sub directory. filter should skip directory and list files match the pattern in all directorys. currently it only list files root directory.

**Comment by Shougo** [comment]
> @Shougo I have tested this feature. It seems do not word for files in sub directory. filter should skip directory and list files match the pattern in all directorys. currently it only list files root directory.

I have implemented skip directory feature.  Please update defx.nvim.

But I don't reproduce `currently it only list files root directory`.
You should create the new issue with the latest version of defx.
If not, OK.  I will ignore your report.

**Comment by wsdjeg** [comment]
Hi, I please checkout https://github.com/SpaceVim/SpaceVim/pull/3803#issuecomment-692113712

**Comment by Shougo** [comment]
I don't reproduce the problem.
Why don't you create the new issue?
