### ISSUE TITLE
[question] what is drive?

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#256]
in doc/defx.txt:731-733
```{.vim}
	call defx#custom#option('_', 'drives', [
	\ expand('~/Downloads'), expand('~')
	\ ])
```
except this paragraph (defx/drive), there are not any introduction about drive.

Can i know what is drive, please?

thank you!

**Comment by Shougo** [comment]
It is the shortcut to jump directories.
The same feature is available on vimfiler.
