### ISSUE TITLE
[Help] Tree's root changed call back function and defx window detect

### ISSUE THREAD

**Issue by zoumi** [Shougo/defx.nvim#262]
1, I want to load a customised exclude list under the root directory, how can I get notified when the root directory is changed?
(I would put the exclude list in ".defx_exclude" file under the root directory.)

2, How to query if there exist a defx window and it's root directory when I'm triggering an key map in a non-defx buffer?

Thanks!

**Comment by Shougo** [comment]
> 2, How to query if there exist a defx window and it's root directory when I'm triggering an key map in a non-defx buffer?

You can get root directory by `b:defx` in defx buffer.

`len(filter(range(1, winnr('$')), "getwinvar(v:val, '&filetype') ==# 'defx'"))`

**Comment by Shougo** [comment]
> 1, I want to load a customised exclude list under the root directory, how can I get notified when the root directory is changed?

I have added `DefxDirChanged` User autocmd.

**Comment by zoumi** [comment]
Thank you very much!

But still get a problem when I try to get 'b:defx'. It returns nothing.
Here is my test code:
```viml
map <F8> :call GetDefxWins()<CR>
function! GetDefxWins()
    let l:re=[]
    for i in range(1,winnr('$'))
        let l:filetype = getwinvar(i,'&filetype')
        if l:filetype=='defx'
            echo i
            call add(l:re,i)
            echo getwinvar(i,'b:defx')
            echo getbufvar(winbufnr(i),'&defx')
        endif
    endfor
    return l:re
endfunction
```

**Comment by Shougo** [comment]
It must be: `echo getbufvar(winbufnr(i),'defx')`

**Comment by zoumi** [comment]
Thanks again, I have finished what I want. Let me share it here:
```viml
function! GetDefxWins()
    let l:re=[]
    for i in range(1,winnr('$'))
        let l:filetype = getwinvar(i,'&filetype')
        if l:filetype=='defx'
            call add(l:re,i)
            "echo getbufvar(winbufnr(i),'defx')
        endif
    endfor
    return l:re
endfunction

autocmd! User DefxDirChanged  call OnDefxDirChanged()
func! OnDefxDirChanged()
    let l:defx_win = GetDefxWins()[0]
    let l:defx_bufnr = winbufnr(l:defx_win)
    let l:var = getbufvar(l:defx_bufnr,'defx')
    let l:tree_root = l:var['paths'][0]
    let l:ig_file = l:tree_root . '/.tree_view_ignored'
    if filereadable(l:ig_file)
        let l:lines = readfile(l:ig_file)
        if len(l:lines)>0
            let l:line = trim(l:lines[0])
            let l:defx_last_root_ignored_files =
                        \ getbufvar(l:defx_bufnr,'defx_last_root_ignored_files','')
            "remove last root dir's ignored_files
            let l:cur_ig = l:var['context']['ignored_files']
            let l:df_len = len(l:cur_ig) - 
                        \ len(l:defx_last_root_ignored_files)
            let l:last_ig_len = len(l:defx_last_root_ignored_files)
            if strpart(l:cur_ig,l:start_pos,l:last_ig_len)==l:defx_last_root_ignored_files
                let l:cur_ig=strpart(l:cur_ig,0,l:df_len)
            endif
            call setbufvar(l:defx_bufnr,'defx_last_root_ignored_files',',' . l:line)
            call defx#do_action('change_ignored_files',l:cur_ig . ',' . l:line)
            "echo l:cur_ig . ',' . l:line
        endif
    endif
endfunc
```

**Comment by zoumi** [comment]
There is a flaw: file name with space can not be ignored.
('moni cus*' can not match 'moni cus.ttf')

**Comment by Shougo** [comment]
@zoumi I have tested it, but I don't reproduce your problem.  Sorry.
You need to create the issue for it.  If not, OK.  I will ignore your issue.

**Comment by Shougo** [comment]
@zoumi You should test it by `change_ignored_files` action manually without your code.

**Comment by zoumi** [comment]
Thank you for your tip. I have found the bug:
```viml
call defx#do_action('change_ignored_files',l:cur_ig . ',' . l:line)
```
should be changed to
```viml
call defx#do_action('change_ignored_files',l:cur_ig . ',' . l:line)
```

it's wired that 'change_ignored_files' doesn't modify the value 'ignored_files', it modify another internal var?

**Comment by Shougo** [comment]
> it's wired that 'change_ignored_files' doesn't modify the value 'ignored_files', it modify another internal var?

You should read the documentation.

```
defx#do_action({action}[, {args}])			*defx#do_action()*
		Fire {action} action with {args}.  You can find the actions
		list in |defx-actions|.
		{args} behavior depends on {action}.
		Note: It is only used to define mappings.
```

> Note: It is only used to define mappings.

Please read this.  `defx#do_action()` returns mapping expr.

**Comment by zoumi** [comment]
@Shougo It's seem that DefxDirChanged autocmd didn't work now. Can you check it?

**Comment by Shougo** [comment]
@zoumi Please create new issue with minimal vimrc and minimal instructions.
If not, I will ignore your report.
We have not ESP skills.
