### ISSUE TITLE
Start one instance of external cmd with selection

### ISSUE THREAD

**Issue by ubmarco** [Shougo/defx.nvim#265]
# Problems summary

I want to run *one instance* of an external program and pass all selected files to it.
As far as I understand `execute_command` will use the command on each file passed as %, so multiple instances of my command are started.
My usecase is to start [Beyond Compare](http://scootersoftware.com/) on all selected files. It needs to be called like this:
`bcompare <path_1> <path_2> <path_n>`

## Expected

Have a solution to pass all files to a single external command

**Comment by ubmarco** [comment]
It would also be helpful if the execute command could be configured to be non-blocking, so the external instance is started and I can still use vim to edit.

**Comment by Shougo** [comment]
Implemented.

**Comment by ubmarco** [comment]
Cool thanks for the fast-as-always reply and help.
I tried this mapping:
```
autocmd FileType defx nmap <buffer><expr> b     defx#do_action('execute_command', 'bcompare *', 'async')
```
I see 2 issues now:

1. async does not work as expected, the external command seems to block nvim
2. all exit codes unequal 0 lead to a red exception, for this I'd appreciate a setting so it can be ignored

I recorded a small screencast.
![Peek 2020-09-24 08-47](https://user-images.githubusercontent.com/839934/94110541-13ff8c00-fe43-11ea-92a7-8d3f990cc42f.gif)

I guess I could circumvent both issues by wrapping the external program with a bash script, but a native solution would be more convenient.

**Comment by Shougo** [comment]
`defx#do_action('execute_command', 'bcompare *', 'async')` is wrong.

`{args}` must be List.

`defx#do_action('execute_command', ['bcompare *', 'async'])`

**Comment by Shougo** [comment]
> all exit codes unequal 0 lead to a red exception, for this I'd appreciate a setting so it can be ignored

If you use 'async', the exit code is ignored.

**Comment by ubmarco** [comment]
Ah thanks, that fixes it. Maybe add a hint or an example to the docs?

**Comment by Shougo** [comment]
I have added the error check and updated the documentation.

**Comment by ubmarco** [comment]
Perfect
