### ISSUE TITLE
Does not support opening paths that have spaces in them

### ISSUE THREAD

**Issue by svermeulen** [Shougo/defx.nvim#266]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Cannot pass a path to Defx that contains a space

## Expected

Defx should open paths with space

## Environment Information

 * plugin version(SHA1): be769aa

 * OS: Mac OSX

 * neovim/Vim version: `NVIM v0.5.0-715-g8bc55f656`

 * `:checkhealth` or `:CheckHealth` result(neovim only):  defx reports all green OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin()
Plug 'Shougo/defx.nvim'
call plug#end()
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Create directory at `~/Temp/Foo/Bar Bar`
 1. Open neovim
 1. Execute `:Defx ~/Temp/Foo`
 1. Notice that this displays `Bar Bar` correctly
 1. Exit neovim
 1. Open neovim again
 1. Execute `:Defx ~/Temp/Foo/Bar Bar`
 1. Notice errors (see attached image)

## Screen shot (if possible)

![image](https://user-images.githubusercontent.com/810762/94986152-37949780-0511-11eb-8289-0714938a9779.png)

## notes

I also tried this: `:Defx "~/Temp/Foo/Bar Bar"` but this also failed

**Comment by Shougo** [comment]
You must escape the spaces.

```vim
Defx ~/Temp/Foo/Bar\ Bar
```

> I also tried this: `:Defx "~/Temp/Foo/Bar Bar"` but this also failed

Your escape is invalid for defx.

**Comment by svermeulen** [comment]
Thanks
