### ISSUE TITLE
[bug] incorrect behaviour of rename

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#268]
## The reproduce ways from neovim/Vim starting (Required!)

```vim
" File: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" Vi: nvim v0.4.3
" Py: cpython v3.6.10
" Term: guake v3.7.0
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/Shougo/defx.nvim
nnoremap <expr> r defx#do_action('rename')
nnoremap <expr> s defx#do_action('toggle_select') .. 'j'
autocmd VimEnter * Defx
" cd Desktop
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

### 0

![0](https://user-images.githubusercontent.com/32936898/97272257-9927f780-186c-11eb-8714-1d04085b5dca.png)

### 1

`jjjjssr`

![1](https://user-images.githubusercontent.com/32936898/97272292-a513b980-186c-11eb-8496-fa161f96cc38.png)

### 2

`<C-V>Itest/<ESC>`

![2](https://user-images.githubusercontent.com/32936898/97272317-ad6bf480-186c-11eb-9e0b-b5b07c689b6f.png)

### 3

`ZZ`

![3](https://user-images.githubusercontent.com/32936898/97272329-b3fa6c00-186c-11eb-9a1a-e6c47c671652.png)

Nothing happened.

### Correct Behaviour

`test.vim` and `test.md` will be renamed to `test/test.vim` and `test/test.md`

## Other

However, if rename one file, it can work normally.
![Screenshot from 2020-10-27 15-52-56](https://user-images.githubusercontent.com/32936898/97272219-8b727200-186c-11eb-88db-c20ff13f8ff4.png)

**Comment by Shougo** [comment]
Fixed.
