### ISSUE TITLE
set no number column on start

### ISSUE THREAD

**Issue by roachsinai** [Shougo/defx.nvim#270]
## Problems summary

Is there a way to not show number column for defx buffer? I use [myusuf3/numbers.vim](https://github.com/myusuf3/numbers.vim) to setting numbers column, and set `let g:numbers_exclude = ['defx', 'Mundo']`.

For Mundo buffer number column never shows. But for defx buffer, the very first time number column will show, and if I run `:Defx` (defx close), `:Defx` to let defx buffer show second time, number column disappers. Disappers with 3rd, and other shows.

## Expected

Same behavior with Mundo: never show number column.

## Environment Information

 * plugin version(SHA1): 042c408 lastest

 * OS: Manjaro

 * neovim/Vim version: local/gVim 8.2.1704-1

## Screen shot (if possible)

![Peek 2020-11-03 23-13](https://user-images.githubusercontent.com/9500049/98004179-91e38980-1e2a-11eb-8716-c07796da8828.gif)

**Comment by Shougo** [comment]
Please disable it in `FileType defx` autocmd.

```vim
autocmd FileType defx setlocal nonumber
```

**Comment by roachsinai** [comment]
Thanks @Shougo .

**Comment by yongqi-zhang** [comment]
if you set relativenumber
```
autocmd FileType defx setlocal nonumber
autocmd FileType defx setlocal norelativenumber
```
