### ISSUE TITLE
Have to do action redraw after do action toggle_sort?

### ISSUE THREAD

**Issue by roachsinai** [Shougo/defx.nvim#271]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Have to call action `redraw` to show `toggle_sort` result. Is it by design?

## Expected

`redraw` Defx buffer after `toggle_sort`.

## Environment Information

 * plugin version(SHA1): lastest

 * OS: Manjaro

 * neovim/Vim version: gvim 8.2.1704-1

**Comment by Shougo** [comment]
I will fix it later.

**Comment by roachsinai** [comment]
@Shougo Thanks!
