### ISSUE TITLE
Improvoment suggestion: Different colors for different file size units

### ISSUE THREAD

**Issue by woodyZootopia** [Shougo/defx.nvim#273]
Defx currently prints file size column with the same highlight (as most of other filers do). However, when units of the files are different, The size of the file doesn't comply with the number prefixed to the size, which makes hard to grab the file size at first glance.

If we can highlight filesize with different rules depending on the units, we can highlight, for example, like:
B     -> blue
KB    -> yellow
MB    -> Red
GB    -> Bold Red
to avoid confusion above. Do you think this is a good idea?

**Comment by Shougo** [comment]
OK.

**Comment by Shougo** [comment]
I have implemented it.

**Comment by woodyZootopia** [comment]
Thank you very much! I love it!!!
