### ISSUE TITLE
Defx command doesn't handle paths containing a colon

### ISSUE THREAD

**Issue by mkalinski** [Shougo/defx.nvim#275]
# Problems summary
When a path passed as argument to `:Defx` command contains a colon anywhere, defx transforms the path in an unexpected way and tries to open a different path (than may not exist).

This also happens if a backtick expression evaluates to a path containing a colon.

This doesn't happen when a directory with colon in name is opened from the defx buffer (it behaves normally and is opened).

## Expected
`:Defx` command handles paths containing colons in the same way as other valid paths.

## Environment Information

 * plugin version(SHA1): c5f1a646122eb4f6048f97b1ef8a936ad49f18eb

 * OS: Fedora 33

 * neovim/Vim version: NVIM v0.4.4

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "./venv/bin/python3"
  - INFO: Executable: ./venv/bin/python3
  - INFO: Python version: 3.9.0
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```vim
let &rtp = './defx.nvim,' .. $VIMRUNTIME
let &packpath = ''
let g:python3_host_prog = './venv/bin/python3'
```
(defx.nvim repo was cloned into working dir, and a fresh virtualenv with pynvim was created there)

### Before neovim start
1. `mkdir foo:bar`
2. `touch foo:bar/baz.txt`

### Case 1: Colon directly in command line
1. `:Defx foo:bar`

### Case 2: Colon in result of backtick expression
1. `:e foo:bar/baz.txt`
2. ``:Defx `expand('%:h')` ``

### Bonus weirdness
Defx command actually works as expected if the colon is "escaped".

1. `:Defx foo\:bar`

## Screen shot (if possible)
![Screenshot](https://user-images.githubusercontent.com/959502/101090568-24f11a00-35b7-11eb-90f3-ee463e0ec5fb.png)

## Upload the log file
Log file was empty.

**Comment by Shougo** [comment]
`:` is used for source name separator.
So you need to escape `:` in `:Defx` command.

**Comment by mkalinski** [comment]
Is this documented anywhere?

I'm fine with escaping `:` on command line, but in the case 2, where colon appears in expansion of `expand('%:h')` there isn't a way to escape it.

**Comment by Shougo** [comment]
I will update the documentation.

**Comment by Shougo** [comment]
You can use escape function.

**Comment by mkalinski** [comment]
Thanks for clarification!
