### ISSUE TITLE
[feature] create link

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#285]
Many modern file explorers can allow user to create link. Such as `nautilus`
(default file explorer of gnome):
![Screenshot-20210206234135-1366x768](https://user-images.githubusercontent.com/32936898/107123075-847ce600-68d6-11eb-85bf-b9822c712d03.png)

How about let defx did it?

## Expected

```vim
augroup defx "{{{
	autocmd!
	autocmd FileType defx nnoremap <buffer><expr> C
			\ defx#do_action('symbolic_link', 'relative_path')
	autocmd FileType defx nnoremap <buffer><expr> p
			\ defx#do_action('paste')
augroup END "}}}
```

press `C` in a file such as `~/Documents/a`, the press `p` in a directory
such as `~/Desktop`, defx will execute `ln -s ../Documents/a ~/Desktop/a` (if
	`~/Desktop/a`  has already existed, it should prompt a dialog to let user decide:

```
/home/$USER/Desktop/a already exists.  Overwrite?
(F)orce, (N)o, (R)ename, (T)ime, (U)nderbar:
```

it is just a primary idea, if there exists any dilemma can be changed to make it possible to realize.

if it can be realized, how about absolute path? how about hard link `ln ../Documents/a ~/Desktop/a` or win32 shortcut (it may be not useful, because it only exists in windows. looks like cygwin provides a command `mkshortcut` to create win32 shortcut just like `ln`)

Thanks!

**Comment by Shougo** [comment]
Implemented.

In Windows, create symbolic link feature is already implemented.
But it needs the permission.
