### ISSUE TITLE
[bug] Cannot call rmtree on a symbolic link

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/defx.nvim#286]
```vim
" File: $XDG_CONFIG_HOME/nvim/test.vim
" OS: linux v5.4.13
" Vi: nvim v0.4.3
" Py: cpython v3.9.0b3
" Term: guake v3.7.0
set runtimepath=$VIMRUNTIME,$GITHUBWORKSPACE/Shougo/defx.nvim
nnoremap <expr> <C-x> defx#do_action('remove')
" ln -s Desktop D
" vi -u $XDG_CONFIG_HOME/nvim/test.vim
```

```vim
Defx
```

`jjjjj<C-x>`
![Screenshot from 2021-02-07 21-11-15](https://user-images.githubusercontent.com/32936898/107147578-c74bc600-6989-11eb-8bae-c9030935e778.png)

`y`
![Screenshot from 2021-02-07 21-11-06](https://user-images.githubusercontent.com/32936898/107147586-cc107a00-6989-11eb-9623-7ffeef2b07b4.png)

if `D` is a file not a link, the bug will not exist.

**Comment by Shougo** [comment]
Fixed.
