### ISSUE TITLE
defx requires Pyhon3 support("+python3") in MacVim on MacOS

### ISSUE THREAD

**Issue by snailtree008** [Shougo/defx.nvim#287]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I'm getting this error on :Defx command run:
`[defx] defx requires Python3 support("+python3").`

I use macvim and macvim's built-in TUI version of vim, pynvim is installed. 
I have followed the author's method to add the configuration file, but it does not seem to take effect in macOS.
When I enter the command: echo has('python3’) in MacVim, the return value is still 0

## Expected
MacVim should be able to run :Defx.

## Environment Information

 * plugin version(SHA1):ecc8a0274232be388d922c7ad518c413ac485c44

 * OS:arm MacOS BigSur 11.2.1

 * neovim/Vim version: MacVim 8.2.2164 (169)

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:python3_host_prog = expand('/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/bin/python3')
set pythonthreehome=/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/bin/
set pythonthreedll=/opt/homebrew/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib

" Initialize plugin system
call plug#begin('~/.vim/plugged')
    " Display Vim Statues
    Plug 'vim-airline/vim-airline'
    " Display Weclome Interface
    Plug 'mhinz/vim-startify'
    Plug 'Shougo/defx.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. brew install python
 2. config .vimrc 
 3. start macvim
 4. run :Defx
 5. Get Error

## Screen shot (if possible)
<img width="630" alt="46F087FE-3120-467D-80F7-7AE31DFF12E3" src="https://user-images.githubusercontent.com/31061237/108621498-e4929100-746d-11eb-867d-1328cd38ac0a.png">
<img width="575" alt="QQ20210221-1" src="https://user-images.githubusercontent.com/31061237/108621506-f4aa7080-746d-11eb-9c4f-9f57a5ad8426.png">
<img width="1323" alt="QQ20210221-0" src="https://user-images.githubusercontent.com/31061237/108621512-fc6a1500-746d-11eb-9567-3638c79a49c4.png">
<img width="573" alt="478419E59F2F293491A246EAD8AD1A91" src="https://user-images.githubusercontent.com/31061237/108621526-14da2f80-746e-11eb-9b86-e0c6fcb3bf1a.png">

**Comment by okcl** [comment]
Make sure you have Python3 installed, the following answer also works with Python2.

Make sure you installed the nvim module
`python3 -m pip install --user --upgrade pynvim`

Check for help
`:help provider-python`

I solved mine (I use mac m1) with installing Python3.8 to usr/bin then changing my system language to english.

**Comment by Shougo** [comment]
It is not problem of defx.nvim...
