### ISSUE TITLE
[Feature Request] auto select the file when opened

### ISSUE THREAD

**Issue by mrjones2014** [Shougo/defx.nvim#290]
It would be awesome to have a feature that automatically reveals and scrolls to the opened file in defx whenever a file is opened/a window becomes active.

**Comment by Shougo** [comment]
I don't want to add the feature.
It seems not useful for me. You can use preview action instead.

**Comment by mrjones2014** [comment]
... how about leaving the issue open in case someone else wants to make a PR, at least...

**Comment by Shougo** [comment]
If other people or you explain advantage, I will reopen it.

**Comment by Shougo** [comment]
Or you can send the PR and explain the advantage.

**Comment by mrjones2014** [comment]
In larger projects with conventions around directory structure, sometimes the easiest way to figure out where a new file should go is to search and open a similar file and see where that file lives. this would provide a quick and easy way to see that at a glance.

**Comment by Shougo** [comment]
Hm... I don't understand.
Can you provide the example?

**Comment by mrjones2014** [comment]
sometimes I know the name of a file but not what directory it lives in -- so I'll use fuzzy search via ctrlp to open the file, it would be nice if opening the file also revealed it in the defx tree so I can quickly see where the file lives at a glance.

**Comment by Shougo** [comment]
OK. I know the feature.
Hm...

**Comment by Shougo** [comment]
You can use `Defx -no-fucus` for it.

**Comment by Shougo** [comment]
> [Feature Request] auto-scroll to file when opened

It is not `auto scroll`.  It should be `auto select`.

**Comment by Shougo** [comment]
I have changed the title.
And it is possible without source code changes.

**Comment by Shougo** [comment]
```vim
augroup user_plugin_defx
  autocmd!
  autocmd FileType defx call <SID>defx_mappings()
  autocmd BufNewFile,BufRead * Defx `getcwd()` -no-focus -search=`expand('%:p')`
augroup END

function! s:defx_mappings() abort
  setlocal cursorline
endfunction

call defx#custom#option('_', {
            \ 'winwidth': 30,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
```

**Comment by mrjones2014** [comment]
thank you @Shougo !!!

**Comment by mrjones2014** [comment]
@Shougo your script just closes Defx when I open a file for me 🤔

**Comment by mrjones2014** [comment]
oh, I see. If defx is already open, it closes it.

**Comment by Shougo** [comment]
> oh, I see. If defx is already open, it closes it.

You have set `-toggle` option.
You need to check the configuration.

**Comment by mrjones2014** [comment]
@Shougo I did not set the `-toggle` option

**Comment by Shougo** [comment]
You should provide the minimal vimrc and the reproduce instruction.
If not, I don't work for you.
