### ISSUE TITLE
Can't I just See the modified files in git.

### ISSUE THREAD

**Issue by yylogo** [Shougo/defx.nvim#292]
pycharm has this cool function in file browser is that it can select different mood in their file browser:
Project, Open files, All changed files.

All changed files means the file showed in the browser only when it has been changed.

**Comment by Shougo** [comment]
Sorry.  It is not supported.

**Comment by yylogo** [comment]
I want add this function in defx..

**Comment by Shougo** [comment]
The feature is really needed?
You can add  the source like this.
https://github.com/Shougo/defx.nvim/blob/master/rplugin/python3/defx/source/file/list.py

**Comment by yylogo** [comment]
When I'm in a big project, and I'm in a half developed function, I just want see browse the file changed.  
I really like this function in pycharm, and I want this function in my vim.

**Comment by Shougo** [comment]
You can see git output indicator.
https://github.com/kristijanhusak/defx-git
