### ISSUE TITLE
directory name is disordered when move the directory

### ISSUE THREAD

**Issue by yut19** [Shougo/defx.nvim#294]
# Problems summary
When move directory and Defx buffer is updated, "/" remains and directory name become disodered if previous directory name is longer than next one. 

## Environment Information

 * plugin version(SHA1): up-to-date (i'm not sure SHA1)

 * OS: WSL 20.04 LTS

 * neovim/Vim version: NVIM v0.5.0-dev+1053-g459a6c845

 * `:checkhealth` or `:CheckHealth` result(neovim only): 
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```
 

## Provide a minimal init.vim/vimrc

```toml
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''

  call defx#custom#option('_', {
  \ 'winwidth': 40,
  \ 'split': 'vertical',
  \ 'direction': 'topleft',
  \ 'show_ignored_files': 1,
  \ 'buffer_name': 'exproler',
  \ 'toggle': 1,
  \ 'resume': 1,
  \ 'columns': 'indent:icons:filename:mark',
  \ })

  nnoremap <silent>fs :<C-u>Defx -auto-cd -vertical-preview -floating-preview<CR>

  autocmd FileType defx call s:defx_my_settings()
  function! s:defx_my_settings() abort
    " Define mappings
    nnoremap <silent><buffer><expr> <CR>
      \ defx#is_directory() ?
      \ defx#do_action('open') :
      \ defx#do_action('multi', ['drop', 'quit'])

    nnoremap <silent><buffer><expr> h
      \ defx#do_action('cd', ['..'])

    nnoremap <silent><buffer><expr> j
      \ line('.') == line('$') ? 'gg' : 'j'

    nnoremap <silent><buffer><expr> k
      \ line('.') == 1 ? 'G' : 'k'

    nnoremap <silent><buffer><expr> l
      \ defx#do_action('open')

  endfunction

'''

```

## The reproduce ways from neovim
Let's use files in this repository for example.
1. Clone this repository in local environment.
2. Move to the directory and launch neovim. And open Defx buffer. ('fs' in my env)
3. Move to .git directory by defx#do_action('open'). ('i' in my env)
4. I can see the style is disordered. "/" remains and the position that directory name starts is inconsistent.

## Screen shot
initial state

![messageImage_1616556318573](https://user-images.githubusercontent.com/57561531/112250754-4e849d00-8c9d-11eb-819b-c841426b468b.jpg)

when move to .git directory
![messageImage_1616556656424](https://user-images.githubusercontent.com/57561531/112250705-357bec00-8c9d-11eb-9d59-193894fe88d8.jpg)

## what I tried
I tried to use defx-action-multi to hook defx#redraw() function. However, problem was not solved.
```
nnoremap <silent><buffer><expr> h defx#do_action('multi', ['cd', '..', 'redraw'])   
```
And I also tried to use autocmd to hook "User DefxDirChanged" event and <C-l> redraw command. But this trial end up to fail with my tiny vimscript power...

**Comment by Shougo** [comment]
```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

" Disable netrw
let g:loaded_netrwPlugin       = 1

call defx#custom#option('_', {
      \ 'winwidth': 40,
      \ 'split': 'vertical',
      \ 'direction': 'topleft',
      \ 'show_ignored_files': 1,
      \ 'buffer_name': 'exproler',
      \ 'toggle': 1,
      \ 'resume': 1,
      \ 'columns': 'indent:icons:filename:mark',
      \ })

nnoremap <silent>fs :<C-u>Defx -auto-cd -vertical-preview -floating-preview defx.nvim<CR>

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>
        \ defx#is_directory() ?
        \ defx#do_action('open') :
        \ defx#do_action('multi', ['drop', 'quit'])

  nnoremap <silent><buffer><expr> h
        \ defx#do_action('cd', ['..'])

  nnoremap <silent><buffer><expr> j
        \ line('.') == line('$') ? 'gg' : 'j'

  nnoremap <silent><buffer><expr> k
        \ line('.') == 1 ? 'G' : 'k'

  nnoremap <silent><buffer><expr> l
        \ defx#do_action('open')
endfunction
```

I don't reproduce your problem.  Please use the minimal vimrc and upload the exact reproduce instructions.
If not, I will close the issue.

**Comment by Shougo** [comment]
>what I tried

Please create the minimal vimrc before the try.
We have not ESP skills.

**Comment by matsui54** [comment]
I could reproduce the same problem in WSL's default console. However, when this problem occurs, the whole Neovim's drawing system is broken.
If @yut19 has the same problem, this is not defx's problem, but WSL console's one.
It seems that WSL's default console is incompatible with Vim. I recommend using windows terminal.

**Comment by yut19** [comment]
@Shougo @matsui54
I'm sorry for inadequate reporting and thank you for your quick response. 
I understand the cause of problem. I'll use Windows Terminal instead.

**Comment by Shougo** [comment]
OK.
