### ISSUE TITLE
Change sorters dynamically

### ISSUE THREAD

**Issue by Shougo** [Shougo/defx.nvim#3]
For example:  Sorting.

https://github.com/Shougo/vimfiler.vim/issues/414

denite.nvim supports the feature.

`<denite:toggle_sorters:{arg}>`

**Comment by lambdalisue** [comment]
It is just a suggestion while I don't really get the mean of this issue but how about using `<denite:switch_sorter:{name}:{args}>` instead?

The word "toggle" sounds like "Switching from A to B or from B to A" for me (I'm not sure about the exact definition of "toggle" though).
However, I think there would be several sorters with its specialized `{args}`.

**Comment by Shougo** [comment]
I don't understand your comment.
Please describe it more clearly.

**Comment by Shougo** [comment]
I think `<denite:change_sorter:{name}>` is better name.

**Comment by Shougo** [comment]
> However, I think there would be several sorters with its specialized {args}.

Sorry, I don't want to add the feature.

**Comment by fab6** [comment]
Hi,
I am not sure from this issue discussion... is sorting already working in defx? I am not sure how to apply the denite way to defx?

**Comment by fab6** [comment]
Ok, thanks. Do you have an idea about the time line, when you will implement it. Is it high up on your list or rather far away?

**Comment by Shougo** [comment]
> Ok, thanks. Do you have an idea about the time line, when you will implement it. Is it high up on your list or rather far away?

It is relative high.  But other plugins development is needed before.

**Comment by fab6** [comment]
ok, great, thanks

**Comment by Shougo** [comment]
The next high priority is to implement the feature.
