### ISSUE TITLE
Defx works not so well with Recover.vim

### ISSUE THREAD

**Issue by roachsinai** [Shougo/defx.nvim#302]
# Problems summary

Run `:call execute("Defx -auto-cd -search=".fnameescape(expand('%:p'))." ".expand("~"))` when enable plugin https://github.com/chrisbra/recover.vim will get some unexpected results:

1. defx shows in current window instead of a new split
2. something happend let other autocmd not work

## Expected

Fix listed results above, which means have same behavior as https://github.com/chrisbra/recover.vim disabled.

## Environment Information

 * plugin version(SHA1): **e1842ae**
 * OS: Linux
 * neovim/Vim version: gvim 8.2.2815-1

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
let mapleader=" "

call plug#begin('~/.vim/plugged')
if has('nvim')
  Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/defx.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'chrisbra/recover.vim'
Plug 'ntpeters/vim-better-whitespace'
call plug#end()

augroup vimrc_defx
  autocmd!
  autocmd VimEnter * call Setup_Defx()
augroup END

nnoremap <silent><leader>l :call execute("Defx -auto-cd -search=".fnameescape(expand('%:p'))." ".expand("~"))<CR>

function! Setup_Defx() abort
  silent! call defx#custom#option('_', {
        \ 'winwidth': 30,
        \ 'split': 'vertical',
        \ 'direction': 'topleft',
        \ 'show_ignored_files': 0,
        \ 'buffer_name': 'defxplorer',
        \ 'columns': 'indent:filename',
        \ 'toggle': 1,
        \ 'resume': 1,
        \ 'listed': 1,
        \ 'root_marker': '≡ '
        \ })
  silent! call defx#custom#column('filename', {
        \ 'max_width': 80,
        \ })
endfunction

let g:better_whitespace_enabled=1
let g:better_whitespace_filetypes_blacklist=['defx']
```

## The reproduce ways from Vim starting (Required!)

Use Vim open a file `A` and then press `<leader>l`.

Compare results of press `<leader>l` in Normal mode between enable and disable https://github.com/chrisbra/recover.vim .

What we can find:

### https://github.com/chrisbra/recover.vim enabled

1. defx covers buffer of `A`
2. the trailing spaces of defx are highlight by https://github.com/ntpeters/vim-better-whitespace, which means the autocmd set by https://github.com/ntpeters/vim-better-whitespace not run after open defx

### https://github.com/chrisbra/recover.vim disabled

1. defx opens in a new split
2. the trailing spaces of defx not hightlight

## Screen shot (if possible)

when enable Recover.vim:

![image](https://user-images.githubusercontent.com/9500049/118514269-05b20780-b767-11eb-8a69-2022da4cec3d.png)

when disable Recover.vim:

![image](https://user-images.githubusercontent.com/9500049/118514505-2da16b00-b767-11eb-8dbd-c078920072d7.png)

**Comment by roachsinai** [comment]
By the way, wanna know is there a way of Vim to generate a logfile?

And, don't know why is I change the map of `<leader>l` to:

`nnoremap <silent><leader>l :execute("Defx -auto-cd -search=".fnameescape(expand('%:p'))." ".expand("~"))<CR>`

I mean remove `call` befor `execute` function everything is OK.

**Comment by roachsinai** [comment]
@chrisbra what's the vim-file-manager do you using and any suggestions from you is appreciated, too.

**Comment by Shougo** [comment]
I have tested the below vimrc and it works.

```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/
set runtimepath+=~/src/recover.vim
set runtimepath+=~/src/vim-better-whitespace

let mapleader=" "

augroup vimrc_defx
  autocmd!
  autocmd VimEnter * call Setup_Defx()
augroup END

nnoremap <silent><leader>l :Defx -auto-cd -search=`expand('%:p')` ~<CR>

function! Setup_Defx() abort
  silent! call defx#custom#option('_', {
        \ 'winwidth': 30,
        \ 'split': 'vertical',
        \ 'direction': 'topleft',
        \ 'show_ignored_files': 0,
        \ 'buffer_name': 'defxplorer',
        \ 'columns': 'indent:filename',
        \ 'toggle': 1,
        \ 'resume': 1,
        \ 'listed': 1,
        \ })
  silent! call defx#custom#column('filename', {
        \ 'max_width': 80,
        \ })
endfunction

let g:better_whitespace_enabled=1
let g:better_whitespace_filetypes_blacklist=['defx']
```

My vimrc is wrong??

> And, don't know why, if I change the map of `<leader>l` to:

Please compare the mapping.

**Comment by Shougo** [comment]
I have checked plugins are loaded.

**Comment by roachsinai** [comment]
@Shougo Thanks for your reply!

For the mapping what you posted or directly run

```
:Defx -auto-cd -search=`expand('%:p')` ~
```

in Vim commandline works well in my computer, too.

But I have an extra question:

why can't it be surrounded by `call execute()`?

I mean run

```
:call execute("Defx -auto-cd -search=`expand('%:p')` ~")
```

this issue could be reproduced.

**Comment by Shougo** [comment]
> this issue could be reproduced.

I cannot reproduce the problem again.
What the magic?

**Comment by Shougo** [comment]
If other people reproduce the problem, please report it.

**Comment by Shougo** [comment]
> neovim/Vim version: gvim 8.2.2815-1

Oh...  It seems Vim specific.

**Comment by Shougo** [comment]
https://github.com/chrisbra/Recover.vim/blob/master/plugin/recover.vim#L27

The autocmd breaks defx behavior.

**Comment by Shougo** [comment]
I get it.  `redir` breaks `execute()`.

Closing.

https://github.com/chrisbra/Recover.vim/blob/master/autoload/recover.vim#L20

**Comment by roachsinai** [comment]
Uh, thanks for the deep work.

```
:Defx -auto-cd -search=`expand('%:p')` ~` " works
:execute("Defx -auto-cd -search=`expand('%:p')` ~") " works
:call execute("Defx -auto-cd -search=`expand('%:p')` ~") " issue reproduce
```

So maybe it caused by both `call` and `execute`...

**Comment by Shougo** [comment]
Oh, you don't understand Vim script.

```
execute("Defx -auto-cd -search=`expand('%:p')` ~")
```

means

```
execute "Defx -auto-cd -search=`expand('%:p')` ~")
```

means

```
Defx -auto-cd -search=`expand('%:p')` ~
```

It is not equal with `execute()`!

**Comment by roachsinai** [comment]
Get it, thanks @Shougo !

**Comment by chrisbra** [comment]
I just pushed a fix, I think.

**Comment by roachsinai** [comment]
@chrisbra works well!

**Comment by roachsinai** [comment]
> Oh, you don't understand Vim script.
> 
> ```
> execute("Defx -auto-cd -search=`expand('%:p')` ~")
> ```
> 
> means
> 
> ```
> execute "Defx -auto-cd -search=`expand('%:p')` ~")
> ```
> 
> means
> 
> ```
> Defx -auto-cd -search=`expand('%:p')` ~
> ```
> 
> It is not equal with `execute()`!

@Shougo I have one question to make sure about `call execute("Defx")` and `execute("Defx")`.

Use `call` when use don't care about the return value of a function call, what I searched from google before.

But for now seems vim interprete first word of each line of script as a Ex command?

So when I run `:execute("Defx")`, Vim will run `execute` command not `execute` function, and turn `:execute("Defx")` to `:execute "Defx" `, the exception is for `call` command and function call not at the front of a Ex command. Am I right about this?

**Comment by Shougo** [comment]
Yes.

**Comment by roachsinai** [comment]
@Shougo Thanks!
