### ISSUE TITLE
how to back to parent dir without close current opened dir

### ISSUE THREAD

**Issue by zdmgmail** [Shougo/defx.nvim#309]
`autocmd filetype defx nnoremap <silent><buffer><expr><nowait> h defx#do_action('cd', ['..'])` can go to parent dir, but current opened dir will close,  how to back to parent dir without close current opened dir?

**Comment by Shougo** [comment]
Ah, I get it.  Unfortunately, it is not supported.

**Comment by Shougo** [comment]
It can be supported easily.

**Comment by Shougo** [comment]
Implemented.
