### ISSUE TITLE
rename command cursor position

### ISSUE THREAD

**Issue by zdmgmail** [Shougo/defx.nvim#310]
If rename /a/b/file.txt , hope can have arg for different cursor posion

- /a/b/file.txt`cursor`
- /a/b/`cursor`file.txt
- /a/b/file`cursor`.txt

and rename with new name
- /a/b/`cursor` 

this is ranger(another file manager) action, hope can also support in defx

**Comment by Shougo** [comment]
I have added the feature.  Please read the documentation.
