### ISSUE TITLE
defx-action-link arg

### ISSUE THREAD

**Issue by zdmgmail** [Shougo/defx.nvim#311]
hope  `defx-action-link` can have some arg(`ln` 's arg)

- symbolic or hard link
- relative or not

and a little problem is some file manager use copy link, some use paste link. I always forget it ...

may be change `link` command to arg for `copy` command,  or for both `copy` and `paste` command?

**Comment by Shougo** [comment]
> may be change link command to arg for copy command, or for both copy and paste command?

I don't want to change the action name.
