### ISSUE TITLE
Don't open tree when moving between directories

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#312]
Consider the following minimal init.vim file:
```vim
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim

au FileType defx call s:defx_settings()
function! s:defx_settings()
    nnoremap <silent><buffer><expr> u defx#do_action('cd', ['..'])
endfunction
```
Now as in the GIF:
1. Open nvim
2. Run `:Defx`
3. Press `u` to move up a directory

After 3. folds (tree) are opened... I expect them to be closed.

![defx](https://user-images.githubusercontent.com/2583971/133538226-fa3d1446-ccda-4e15-a899-59c20ef1c249.gif)

**Comment by Shougo** [comment]
Please read this.
https://github.com/Shougo/defx.nvim/issues/309

**Comment by zdmgmail** [comment]
I thought still open is useful
seems you can have a function,  `defx#call_action('cd', ['..'])`  then `defx#call_action('open_tree', 'toggle')`

**Comment by Shougo** [comment]
I have added cd argument and restored cd behavior.

**Comment by petobens** [comment]
Thanks!
