### ISSUE TITLE
defx-action-open_tree recursive exclude pattern

### ISSUE THREAD

**Issue by zdmgmail** [Shougo/defx.nvim#313]
when I use `defx#do_action('open_tree', ['recursive:10', 'toggle'])`,  
always want to  some dir `.git , node_modules, __pycache__` ... not open 
hope can have arg to exclude them(not ignore, just not open)

**Comment by Shougo** [comment]
Well, I should add the argument...

**Comment by Shougo** [comment]
Implemented.
