### ISSUE TITLE
new_file args for open

### ISSUE THREAD

**Issue by zdmgmail** [Shougo/defx.nvim#318]
use `new_multiple_files` create mult files in different dir then open them feel a little hard,

so hope can have arg ,  create mult files then open all newfiles

and often , `new_file`, `new_directory` also want to open, so also hope have open arg

**Comment by Shougo** [comment]
Really??  Oh, no.

**Comment by zdmgmail** [comment]
@Shougo 

`new_file` work ok , create, refresh, open,

`nnoremap <silent><buffer><expr><nowait> x  defx#do_action('new_file'          ,['open','drop'])` 

but `new_multiple_files` 

`nnoremap <silent><buffer><expr><nowait> X  defx#do_action('new_multiple_files',['open','drop'])`  will not refresh defx, 
could you make it refresh same as mult time use `new_file`  ?

and `mult`  seems not work  for those command

```
without mult, worked

nnoremap <silent><buffer><expr><nowait> x  defx#do_action('new_file'          ,['open','drop'])
nnoremap <silent><buffer><expr><nowait> X  defx#do_action('new_multiple_files',['open','drop'])

add mult, not work

nnoremap <silent><buffer><expr><nowait> x  defx#do_action('multi',[['new_file'          ,['open','drop']]])
nnoremap <silent><buffer><expr><nowait> X  defx#do_action('multi',[['new_multiple_files',['open','drop']]])
nnoremap <silent><buffer><expr><nowait> M  defx#do_action('multi', [['new_directory'     ,'open_tree']])
```


this `open_tree` not work for nest dir

```
nnoremap <silent><buffer><expr><nowait> M  defx#do_action('new_directory'     ,['open','open_tree'])
```

create dir `a` will  open_tree(but not focus this new dir, I thought it should focus)

create dir `a/b` will not open_tree

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thanks!
