### ISSUE TITLE
Temporary clearing wildignore list causes issue with another plugins

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#32]
In this issue i reported a problem where i couldn't open a file that is part of wildignore https://github.com/Shougo/defx.nvim/issues/24.

You fixed it by setting wildignore to empty list temporarily, and returning it back to the old value.
That fixed the issue, but caused another problems.
For example, i'm using vim-gutentags to auto generate tags file. It also respects the wildignore when generating tags.
I noticed that when i open a project file from defx,gutentags generates a lot of bad tags that should be ignored. When i run command to do it again, everything works fine.

I figured out that gutentags generates tags on bufread, and at that moment wildignore is empty because of defx.

**Comment by Shougo** [comment]
I cannot/don't fix the problem.

Because, 

* I don't like `wildignore` option
* Vim/Neovim cannot resolve the problem.   Vim/Neovim don't support "ignore wildignore, but it is enabled in BufRead autocmd".
* I think previous problem(#24) is fatal problem than the problem.

If you can find the other plugin file manager resolve the problem, please tell me.
I will research the implementation.

**Comment by kristijanhusak** [comment]
I know that NERDTree doesn't do anything with the wildignore, and it works without any issues.

**Comment by Shougo** [comment]
> I know that NERDTree doesn't do anything with the wildignore, and it works without any issues.

Hm.   OK.  I will test it.
Please upload the reproduce instructions and the minimal configuration to test the problem.

Note:  Please don't ignore the issue template.  I cannot test the problem.

**Comment by Shougo** [comment]
> Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

Please read this.

**Comment by kristijanhusak** [comment]
Sorry, just wanted to start a discussion first.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
set runtimepath+=~/path/to/vim-gutentags/
autocmd FileType defx call s:defx_my_settings()

function! s:defx_my_settings() abort
	nnoremap <buffer><expr> <CR> defx#do_action('open')
endfunction

set wildignore=*.mypy_cache*
```


## The reproduce ways from neovim/Vim starting (Required!)

 1. Make sure you have `.mypy_cache` in the defx folder, which you probably do.
 2. Open nvim, run `:Defx`
 3. navigate to some .py file, for example `view.py`
 4. Open `tags` file generated in root, it has lots of tags from .mypy_cache folder
 5. Go back to `view.py`, run `:GutentagsUpdate!` 
 6. Open tags again, no `.mypy_cache` tags.

**Comment by Shougo** [comment]
> I know that NERDTree doesn't do anything with the wildignore, and it works without any issues.

I get the reason.  I have fixed it in the latest version.

**Comment by kristijanhusak** [comment]
It works, but it doesn't work when using `drop`:

```vimL
  nnoremap <silent><buffer><expr> <CR> defx#do_action('open', 'wincmd p \| drop')
```
Only workaround i can think of is to not use drop but custom logic that simulates the `drop` and calls `edit` in the background.

**Comment by Shougo** [comment]
I think drop command uses `wildignore` in the internal implementation.
It is very ugly.

**Comment by Shougo** [comment]
Other file manager does not change wildignore internally.
So they have same problem.

**Comment by Shougo** [comment]
You already know `wildignore` is very ugly option.

**Comment by kristijanhusak** [comment]
Yeah i know. NerdTree simulates drop with some custom code i assume.
It's ok, thanks for the fix.

**Comment by Shougo** [comment]
I think current `:drop` command behavior is very strange.
You can test `:drop` command with `wildignore` behavior in both Vim and neovim.

I recommend for you to report the behavior in their issues.

**Comment by kristijanhusak** [comment]
Here's a simple workaround if someone gets the same issue:
```vimL
function! FocusOrEdit(filename) abort
  let l:winnr = bufwinnr(a:filename)
  if l:winnr > 0
    exe l:winnr.'wincmd w'
  else
    exe 'edit ' a:filename
  endif
endfunction

command -nargs=1 FocusOrEdit call FocusOrEdit(<q-args>)

function! DefxSettings() abort
  nnoremap <silent><buffer><expr> <CR> defx#do_action('open', 'wincmd p \| FocusOrEdit')
endfunction

**Comment by Shougo** [comment]
I have added "drop" action.
You can use it instead.

> I think drop command uses wildignore in the internal implementation.
> It is very ugly.

It is builtin `:drop` problem.  It is not defx specific.
It same with both Vim and neovim.
I have read neovim implementation code and `:drop` is implemented by `glob()`.
