### ISSUE TITLE
如何配置，可以实现看到 "." ,“.." 两个目录，一个当前目录一个上级目录

### ISSUE THREAD

**Issue by gamark** [Shougo/defx.nvim#323]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
如何配置，可以实现看到 "." ,“.." 两个目录，一个当前目录一个上级目录

## Environment Information

 * plugin version(SHA1):

 * OS:

 * neovim/Vim version:

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/plugin/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Have you read the other issues?  Please use English instead.
I cannot read Chinese.

**Comment by Shougo** [comment]
And please describe the issue more understandable.  It is hard to understand using translation.
I think the screenshot is needed.
We have not ESP skills.
