### ISSUE TITLE
How to configure to see .,..  directory

### ISSUE THREAD

**Issue by gamark** [Shougo/defx.nvim#324]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
How to configure to see .,..  directory
example:
../
./
other directorys
other files

## Environment Information

 * plugin version(SHA1):

 * OS:

 * neovim/Vim version:

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/plugin/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
OK.  I get it.  defx does not support the feature.
Please use the mapping like this.

`nnoremap <silent><buffer><expr> h defx#do_action('cd', ['..'])`

vimfiler supports `..` though.
https://github.com/Shougo/vimfiler.vim/blob/master/doc/vimfiler.txt#L1011

**Comment by gamark** [comment]
thanks!
