### ISSUE TITLE
defx failed to init at gvim startup sometimes

### ISSUE THREAD

**Issue by zoumi** [Shougo/defx.nvim#328]
# Problems summary
Sometimes when I start defx in VimEnter, defx fails to init.

## Environment Information

 * plugin version(SHA1): SHA-1: 5f485045f3b55acd168f08c5eeeee91f4ca315e5

 * OS:Windows 10 64 bit

 * neovim/Vim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 24 2022 23:02:44)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-4621
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
autocmd VimEnter * nested call s:do_when_vim_enter()

func! s:do_when_vim_enter()
    execute('silent! source ~/vim.session')
    let t = timer_start(200,'s:starup_show_defx_win')
endfunc

func! s:starup_show_defx_win(timer)
    "use cd to clear all lcd
    windo cd ./
    if exists('g:my_last_time_file')
        call defx#start([['file',fnamemodify(g:my_last_time_file,':p:h')]],
                    \ {'auto_cd':1,'buffer_name':'defx' . tabpagenr()})
    else
        call defx#start([['file',expand('%:p:h')]],{'auto_cd':1,'toggle':1,
                    \ 'buffer_name':'defx' . tabpagenr()})
    endif
    wincmd h
endfunc
```

## The reproduce ways from neovim/Vim starting (Required!)
It only happen sometimes.

## Screen shot (if possible)
![Snipaste_2022-04-01_10-38-38](https://user-images.githubusercontent.com/5162901/161186308-d1c22334-2524-4af9-b684-cdc86fe0220c.jpg)

**Comment by Shougo** [comment]
I think nvim-yarp is not initialized.
You should use `timer_start()` for it.

`autocmd VimEnter * nested call timer_start(100, { -> s:do_when_vim_enter() })`

**Comment by zoumi** [comment]
I'm already call s:starup_show_defx_win in a timer. Is it not enough?

**Comment by Shougo** [comment]
```vim
set rtp+=~/work/defx.nvim
set rtp+=~/src/nvim-yarp
set rtp+=~/src/vim-hug-neovim-rpc

autocmd VimEnter * nested call s:do_when_vim_enter()

func! s:do_when_vim_enter()
  let t = timer_start(2000,'s:starup_show_defx_win')
endfunc

func! s:starup_show_defx_win(timer)
  "use cd to clear all lcd
  windo cd ./
  if exists('g:my_last_time_file')
    call defx#start([['file',fnamemodify(g:my_last_time_file,':p:h')]],
          \ {'auto_cd':1,'buffer_name':'defx' . tabpagenr()})
  else
    call defx#start([['file',expand('%:p:h')]],{'auto_cd':1,'toggle':1,
          \ 'buffer_name':'defx' . tabpagenr()})
  endif
  wincmd h
endfunc
```

I have tested it and it works in Vim 8.2.  But you use Windows environment.
Windows initialization is very very slow!
You need to increase timer value.

**Comment by zoumi** [comment]
OK, thank you. Is there a way to get notified when nvim-yarp is ready?

**Comment by Shougo** [comment]
I have checked the code.
It is `vim-hug-neovim-rpc`'s problem instead of `nvim-yarp` and `defx.nvim`.
`nvim-yarp` waits the initialization.

**Comment by Shougo** [comment]
`vim-hug-neovim-rpc` is deprecated and I cannot support it.
