### ISSUE TITLE
Can i get the path without yank?

### ISSUE THREAD

**Issue by ShiChenCong** [Shougo/defx.nvim#329]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Can i get the path related to my cursor position without yank? i want intergate defx.vim with telescope serach
![image](https://user-images.githubusercontent.com/22486446/169321903-cdc8fd75-44bc-4f2b-a4c6-0576e8f17c70.png)
eg: get the Conf directory path without yank

## Expected
get the path with defx's function eg:  defx#do_action('get_path')

```vim
function telescope_find_word_in_specifeid_file(path)
  vim.api.nvim_command("call defx#call_action('yank_path')")
  local _path = vim.fn.eval('@*')
  require("telescope.builtin").live_grep({ search_dirs = { _path }, file_ignore_patterns = {} })
end

```

**Comment by Shougo** [comment]
You can use `defx#get_candidate()` instead.

**Comment by ShiChenCong** [comment]
@Shougo Thank you! It works
