### ISSUE TITLE
Windows 10 cwd path problem

### ISSUE THREAD

**Issue by rislah** [Shougo/defx.nvim#332]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Thank you for this plugin

Trying to open Defx in the current folder on Windows.

On my Linux system, everything is ok. 

On Windows, for example cwd = `C:\Users\usr\AppData\Local\nvim`, 
doing `Defx C:\Users\usr\AppData\Local\nvim` or `Defx <C-r>=expand('%:p:h')<CR>` will result in error: ` "C:\Users\usr\AppData\Local\nvim\C:UsersusrAppDataLocalnvim" is not a readable directory.`

This is not a problem with nvim on windows, as netrw handles it properly.

## Environment Information

 * plugin version(SHA1): 82ca2c5bdf6dbab6f0f96980b572d44267003841

 * OS: Windows 10 21h2

 * neovim/Vim version:  0.7.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 ```

defx: health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang" }
    Version: clang version 14.0.6
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - go             x x x x x
  - cpp            ✓ ✓ ✓ ✓ ✓
  - javascript     x x x x x
  - typescript     x x x x x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}


provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Users\rsl\AppData\Local\Programs\Python\Python39\python.EXE
  - INFO: Other python executable: C:/Users/rsl/AppData/Local/Programs/Python/Python39/python
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/plugin/
nnoremap ,- :Defx <C-r>=expand('%:p:h')<CR><CR>
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. `:Defx <C-r>=expand('%:p:h')`

## Generate a logfile if appropriate
Nothing in logs

## Screen shot (if possible)

https://i.imgur.com/Ag9eR0k.png

**Comment by rislah** [comment]
turning the slashes around and doing `Defx C:/Users/usr/AppData/Local/nvim` fixes the problem

related issues
https://github.com/neovim/neovim/issues/2471
https://github.com/neovim/neovim/issues/7117

should be fixed on nvim, as i stated netrw handles it properly

**Comment by Shougo** [comment]
You need escape `\` in the path.
Because `\` is special character in defx.nvim command line.

`Defx <C-r>=escape(expand('%:p:h'), '\')`
