### ISSUE TITLE
 close previous buffer when open new buffer

### ISSUE THREAD

**Issue by ShiChenCong** [Shougo/defx.nvim#333]
Hi there, i'd like to close previous buffer when open new buffer
Could this plugin do this? i did not find the way in help.doc

# Problems summary

 close previous buffer when open new buffer
## Expected
 close previous buffer when open new buffer

**Comment by Shougo** [comment]
What is `Close previous buffer` means?
It is `:bdelete` previous buffer?
I think it should not.

If not, please describe it more clearly.

**Comment by ShiChenCong** [comment]
current is buffer a, use Defx open new buffer b, after open buffer b, auto close buffer a.
like open new buffer replace current buffer
@Shougo

**Comment by Shougo** [comment]
You should upload the screenshots.
It is not easy understand.

**Comment by Shougo** [comment]
And you need to upload minimal vimrc like this.
https://github.com/Shougo/defx.nvim/issues/331

**Comment by ShiChenCong** [comment]
sorry for my english,
![Untitled](https://user-images.githubusercontent.com/22486446/187849032-a2d1e824-ce28-4ae2-896b-5eea99300179.gif)

After open new buffer 'constants.ts', i'd like to auto close previous buffer 'index.tsx'

**Comment by Shougo** [comment]
I think you have executed `tabopen` action.
Please upload your defx config.

**Comment by Shougo** [comment]
Hm... I think your tabpage prints buffer list.
It depends on your config.  So I cannot fix it.  Closing.
You can it with minimal config and it cannot be reproduced.
defx works expected.

**Comment by Shougo** [comment]
Note:  I have checked your defx config.

https://github.com/ShiChenCong/.dotfiles/blob/1647b4e427b0768bc3ff3211d7d031891c119d34/nvim/after/plugin/defx.rc.vim

**Comment by ShiChenCong** [comment]
I think I know how to describe it now, like a preview of vscode
![Untitled](https://user-images.githubusercontent.com/22486446/187860124-462465b0-9595-4d5e-8521-745b47c8933b.gif)
open file in same buffer, until i double click

**Comment by lazyzyf** [comment]
use  `drop `instead of `open `like below command.`nnoremap <silent><buffer><expr> <CR> defx#do_action('drop')`

**Comment by Shougo** [comment]
> I think I know how to describe it now, like a preview of vscode

Hm..  If you need preview, you should use `preview` action instead.

**Comment by ShiChenCong** [comment]
after `defx#do_action('open')`,execute `bd#`
