### ISSUE TITLE
[question] just wonder why add trailing spaces at each line of defx buffer

### ISSUE THREAD

**Issue by roachsinai** [Shougo/defx.nvim#335]
Sometimes I can see trailing spaces in defx buffer as I set highlight of trailing spaces.

Found the trailing space was add by

https://github.com/Shougo/defx.nvim/blob/1049fc442e8c35b6eba45ba4be1e21b9acb07010/rplugin/python3/defx/column/filename.py#L114

Just wonder why defx do this. Thanks!

**Comment by Shougo** [comment]
> Sometimes I can see trailing spaces in defx buffer as I set highlight of trailing spaces.

You need to disable the highlight.

> Just wonder why defx do this. Thanks!

It is added to highlight columns.
If I don't add this, the highlight is broken.

Note:  End column highlight does not work if the end column is too short.

**Comment by roachsinai** [comment]
@Shougo Thanks for quick reply!
