### ISSUE TITLE
How to clear column's cache?

### ISSUE THREAD

**Issue by hrsh7th** [Shougo/defx.nvim#36]
# Problems summary
defx-git を fork して、getcwd() ベースで git status を取得するのではなく、
defx の candidate の root directory から git の status を取得する実装を行いました。
（つまり、defx 上でディレクトリ移動しても適切に git status が反映されるということです。）

https://github.com/kristijanhusak/defx-git/pull/1/files

コレ自体はうまくできていそうなのですが、
差分を commit&push したあとなどに Column 内に保持している git status の結果キャッシュを破棄する方法がわかりませんでした。
また、できれば対応したい機能として、Nsec 毎にキャッシュを更新するなども考えられるのかなと思っています。

これらは defx の思想としてはどのように実現すべきでしょうか。

## Expected
- Column が保持するキャッシュを redraw 時に破棄できる
- Column が一定期間毎に内容をリフレッシュできる？

## Environment Information

 * defx version(SHA1):
 ** N/A

 * OS:
** N/A

 * neovim/Vim version:
** N/A

 * `:checkhealth` or `:CheckHealth` result(neovim only):
** N/A

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
** N/A

## The reproduce ways from neovim/Vim starting (Required!)
** N/A

## Generate a logfile if appropriate
** N/A

## Screen shot (if possible)
** N/A

## Upload the log file
** N/A

**Comment by Shougo** [comment]
I have added `on_redraw()` hook in column.

**Comment by hrsh7th** [comment]
Thanks! I'll use this feature.

**Comment by kristijanhusak** [comment]
@Shougo it turned out that this hook is not needed. I updated my code to work without it. You can still leave it in case someone else needs it.

**Comment by Shougo** [comment]
>  You can still leave it in case someone else needs it.

I think it can be useful.  So I don't remove it.
