### ISSUE TITLE
open defx in same window as file

### ISSUE THREAD

**Issue by fab6** [Shougo/defx.nvim#38]
I have often e.g. two windows open, see attachment defx_1.png
![defx_1](https://user-images.githubusercontent.com/3047695/47905443-78985300-de87-11e8-963d-a7fa4576d067.png)

Now usually I would like to start/open defx in the same window as the file (here the left python script) and have the cursor at the file position. This worked before my vacation time.

Now, after an update. Defx will start in the existing defx-window in the right and keeps the python file open.

The same effect occurs with more than two windows and even with tabs.

This is the command I use:
map <silent><leader>d :Defx -auto-cd `expand('%:p:h')` -search=`expand('%:p')` <CR>

but a simple :Defx results in the same behavior.

Do you have an idea?

**Comment by Shougo** [comment]
Please use `drop` action instead.

**Comment by fab6** [comment]
Ok. Maybe, there is a misunderstanding. I understood before, that "drop" is for opening a file within defx, but not to start a defx window.

**Comment by fab6** [comment]
I just checked. My issue is slightly different:
on the example above, I am within the python window (left window) and would like to open a defx window in the same left window.
At the moment, the current defx window on the right gets replaced by the directory of the left window without changing the left python window and the right window is the active window.
Hope this is a bit more clear...
Do you have an idea?

**Comment by Shougo** [comment]
OK.  I get it.  I have changed the behavior recently.
Please read #27.
If you don't want to jump, please use -new option.

**Comment by fab6** [comment]
ok, thanks, I left on this day to vacation...
