### ISSUE TITLE
Defx steals focus from edit buffer in project drawer mode

### ISSUE THREAD

**Issue by azhi** [Shougo/defx.nvim#39]
# Problems summary

Files opened from denite grep buffer sometimes open in defx buffer instead of buffer with a file.

## Expected

Files opened from denite grep buffer always open in active buffer.

## Environment Information

 * defx version(SHA1): f5f577fbe3fe930e0b92eafd8ee792633943110e

 * denite version (SHA1): bfa24860cbca06dc972d96b51a4cf5b1122bb5ee

 * OS: Linux (ArchLinux)

 * neovim/Vim version: neovim 0.3.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):
<details>
  <summary>:checkhealth</summary>
  <pre>
    health#nvim#check
    ========================================================================
    ## Configuration
      - OK: no issues found
    
    ## Performance
      - OK: Build type: Release
    
    ## Remote Plugins
      - OK: Up to date
    
    ## terminal
      - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
      - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
      - INFO: $COLORTERM='rxvt'
    
    health#provider#check
    ========================================================================
    ## Clipboard (optional)
      - OK: Clipboard tool found: xsel
    
    ## Python 2 provider (optional)
      - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
      - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
      - INFO: Executable: /usr/bin/python2
      - INFO: Other python executable: /bin/python2
      - INFO: Python2 version: 2.7.15
      - INFO: python2-neovim version: 0.3.0
      - OK: Latest python2-neovim is installed: 0.3.0
    
    ## Python 3 provider (optional)
      - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
      - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
      - INFO: Executable: /usr/bin/python3
      - INFO: Other python executable: /bin/python3
      - INFO: Python3 version: 3.7.0
      - INFO: python3-neovim version: 0.3.0
      - OK: Latest python3-neovim is installed: 0.3.0
  
    ## Ruby provider (optional)
      - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
      - INFO: Host: ~/.gem/ruby/2.5.0/bin/neovim-ruby-host
      - OK: Latest "neovim" gem is installed: 0.7.1
    
    ## Node.js provider (optional)
      - INFO: Node.js: v10.12.0
      - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
      - OK: Latest "neovim" npm/yarn package is installed: 4.2.1
  
    health#defx#check
    ========================================================================
    ## defx.nvim
      - OK: has("python3") was successful
      - OK: Python 3.6.1+ was successful

  </pre>
</details>

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.local/share/nvim/plugged/defx.nvim/
set runtimepath+=~/.local/share/nvim/plugged/denite.nvim/

nnoremap <C-P> :Defx -toggle -split=vertical -winwidth=40 .<CR>
nnoremap <C-F> :Denite -post-action=suspend -auto-resume grep:::
```

## The reproduce ways from neovim/Vim starting (Required!)
 0. Before starting neovim prepare a directory with 4 files containing 'test', e.g. `'mkdir /tmp/defx; for f in /tmp/defx/t{1,2,3,4}; do echo "test" > $f; done`
 1. Hit `<C-p>` to open Defx in project drawer mode
 2. Switch to right buffer (`<C-w>l`)
 3. cd to your directory with files from 0 - `:cd /tmp/defx`
 4. `<C-f>test<CR>` to open denite grep using 'test'
 5. `<CR>` - t4.txt opens in edit buffer - OK
 6. Open next file: `<C-w>j<C-g><CR>` - t3.txt opens in edit buffer - OK
 6. Open next file: `<C-w>j<C-g><CR>` - t2.txt opens in Defx buffer - NOT OK

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/752698/48104218-83663580-e243-11e8-8b7e-9a1287589fd0.png)

## Upload the log file
https://gist.githubusercontent.com/azhi/55a0af02829a0f508a129cd08ba907d1/raw/6a346ee089d2680004e802b46c58db33a58bdef6/log_py3_rplugin

**Comment by Shougo** [comment]
Fixed.
Please update denite.nvim.

It is not defx.nvim's issue.

**Comment by azhi** [comment]
Yep, it works, thank you!
