### ISSUE TITLE
Show hidden files

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#44]
How can I show/toggle hidden files from within defx?

**Comment by Shougo** [comment]
```
toggle_ignored_files			*defx-action-toggle_ignored_files*
		Toggle the enable state of ignored files.
```

Please read the documentation.

**Comment by petobens** [comment]
I did search but I didn't understand that ignored meant hidden. Thanks!

**Comment by petobens** [comment]
Also, can hidden/ignored files be shown by default?

**Comment by petobens** [comment]
Ok.

**Comment by unblee** [comment]
Hi @petobens 

I added `-show-ignored-files` option. Try it :smile: 
```
:Defx -show-ignored-files
```

**Comment by petobens** [comment]
Thanks for the change! https://github.com/petobens/dotfiles/commit/67f5b54c3a7eb7e872bf9a031e9990a427d56a07
