### ISSUE TITLE
columns option not working

### ISSUE THREAD

**Issue by fab6** [Shougo/defx.nvim#45]
:Defx -columns={makr,filename}
and any other options result in an empty window for me.
I just updated to get the size and time columns...

**Comment by kristijanhusak** [comment]
You wrote it in wrong format. It should be like this:
```
Defx -columns=mark:filename
```
Also, there is no column for size and time available.

**Comment by fab6** [comment]
oh, sorry... thank you!

**Comment by Shougo** [comment]
If you need `size` and `time` columns,

```vim
Defx -columns=mark:filename:size:time
```
