### ISSUE TITLE
Spacing between columns

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#46]
I noticed that you added a space between each column here https://github.com/Shougo/defx.nvim/commit/ef76da64ae272e282e955f8933a76de9102960a1#diff-ad8ff925b1ca4468935e4b5cb0f0ec22R250. This makes custom columns a bit too wide now (I included space by myself there). Should i update my custom columns to account for that?

**Comment by Shougo** [comment]
Yes.  Please fix your custom column.

The custom column API is not stable yet.

Note:  So I have not added the feature until your PR.
