### ISSUE TITLE
On Win10 dot files does not show

### ISSUE THREAD

**Issue by akiya64** [Shougo/defx.nvim#48]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
On Windows10, Defx does not show dot files example `.gitignore` .

# Expected
Defx does not show dot files `.gitignore`, `.editorconfig` etc.
I want find and edit dot files via defx, example `.gitignore`,  `.stylelintrc.json` or another.
I tried `:call defx#do_action('toggle_ignored_files')`.
But change nothing, is it no relation 'toggle_ignored_files' between dot files?

## Environment Information

 * defx version(SHA1):
d50b5ad870706e51566bee087e9cb3cbbc1f3b0d

 * OS:
Windows 10 Pro 1803   OS build 17134.407

 * neovim/Vim version: NeoVim 0.3.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Users\akiya\AppData\Local\Programs\Python\Python37-32\python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:\Users\akiya\AppData\Local\Programs\Python\Python37-32\python"
  - INFO: Executable: C:\Users\akiya\AppData\Local\Programs\Python\Python37-32\python
  - INFO: Python3 version: 3.7.0
  - INFO: python-neovim version: 0.2.6
 (outdated; from ~\AppData\Local\Programs\Python\Python37-32\lib\site-packages\neovim)
  - WARNING: Latest python-neovim is NOT installed: 0.3.1

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - ERROR: Command timed out: node -v
  - INFO: Node.js: 
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

## Screen shot (if possible)
![2018-11-29_15h21_16](https://user-images.githubusercontent.com/14228487/49203141-7e337b00-f3ea-11e8-945e-1b6becce25fa.png)

**Comment by Shougo** [comment]
> But change nothing, is it no relation 'toggle_ignored_files' between dot files?

It should work.  But I don't test the problem.

**Comment by Shougo** [comment]
I tried `:call defx#do_action('toggle_ignored_files')`.

Hm.  It is wrong.
It must be in expr mapping like this:

```
nnoremap <silent><buffer><expr> .
\ defx#do_action('toggle_ignored_files')
```

**Comment by mhartington** [comment]
Seeing this as well in macOS. Calling `defx#do_action('toggle_ignored_files')` does not work, but the expression mapping does work.

**Comment by akiya64** [comment]
Thanks.
Mapping key, Defx show dot files.
