### ISSUE TITLE
Feature: combine new file and new directory into on function

### ISSUE THREAD

**Issue by mhartington** [Shougo/defx.nvim#49]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Having to make multiple files and directories in a defx buffer requires some memorization of different mappings. Would you be interested in a PR that combines the two functions as one? This is similar to what NERDTree does 

Some code to show what it would look like

```python
def _new_node(view: View, defx: Defx, context: Context) -> None:
    """
    Create a new file or directory.
    """

    nodename = cwd_input(view._vim, defx._cwd,'Please input a new file/dir name. Dirs end with a "/": ', '', '')
    if not filename:
        # Input canceled
        return

    if filename.exists():
        error(view._vim, '{filename} already exists')
        return

    # filename is directory
    if filename[-1] is '/':
       filename.mkdir(parents=True)

    # filename is a file
    else: 
      if not filename.parent.exists():
          filename.parent.mkdir(parents=True)
      Path(filename).touch()

    view.redraw(True)
    view.search_file(str(filename), defx._index)
```

**Comment by kristijanhusak** [comment]
You can already do that with `new_file` action, just type in the full path. For example my/awesome/path/file.txt will create folders my,awesome and path, and inside path you will have file.txt.

**Comment by mhartington** [comment]
Yes, but that assumes you're going to create a file. If I do `new_file` and type `some_dir/` and just leave that as is, it will create it as a file, not a directory.

**Comment by kristijanhusak** [comment]
Yeah that's true. In cases when i really need that (which is very rare), i just use new directory.

**Comment by Shougo** [comment]
Hm....  It should be `new_multiple_files` action.

**Comment by Shougo** [comment]
I have added it.

**Comment by kristijanhusak** [comment]
Nice, i'll use this instead of new_file, it's much better.
