### ISSUE TITLE
Default key mappings

### ISSUE THREAD

**Issue by kutsan** [Shougo/defx.nvim#5]
I am sorry Shougo but I would like to say your default key mappings of choices were horrible for vimfiler. I know you can change it but it's not a great experience for first-time users. Like, who would have thought to press <kbd>Shift + K</kbd> to [make a new directory](https://github.com/Shougo/vimfiler.vim/blob/master/doc/vimfiler.txt#L846)? There is no mnemonic and it's not intuitional. So, if you don't mind, can we discuss this before its implementation? They should be easy to remember and well-thought. For example, `cf`, `[c]reate [f]ile` or `cd`, `[c]reate [d]irectory` something like that. Although this can be more intuitive with `dd`, `cut file or directory under cursor` and `yy`, `copy file or directory under cursor`.

**Comment by Shougo** [comment]
> who would have thought to press Shift + K to make a new directory?

It means `maKe directory`.

**Comment by Shougo** [comment]
> So, if you don't mind, can we discuss this before its implementation?

I think it will be bikeshedding.

**Comment by Shougo** [comment]
And `c` is used for `Copy`.  I don't want to change it.

**Comment by lambdalisue** [comment]
> I think it will be bikeshedding.
People think another mapping is better.
No suitable choice.

So I would appreciate if you choose to **not** providing a default mapping for individual features.
I would prefer denite like action **with `<Plug>` mappings** .
So that users can define what they want easily without `unmap <buffer> k` or whatever.

I understand the minimum mappings are required but I think vimfiler provides too many default mappings which I never use.

What do you think about it?

**Comment by kutsan** [comment]
> People think another mapping is better. No suitable choice.

I mean, you (or we) should choose suitable defaults for everyone.

> It means maKe directory.

I don't know others but I think `ma[K]e directory` isn't a good choice.

> And c is used for Copy. I don't want to change it.

Don't you think `yy` is better for copying? It will be already intuitive for most users.

Beside all of them I think @lambdalisue is right. There is so much default ones. Some of them like <kbd>C-k</kbd>, <kbd>C-l</kbd> commonly used by many other folks as pane navigation mappings which requires to unmap at some point.

**Comment by lambdalisue** [comment]
Yes. I would prefer if you choose default key mappings **based on Vim's builtin one** like @kutsan said. But do not get it wrong. I think defx should **NOT** provide mappings for copying files or making directory or these kinds **special** features (features beyond navigation or whatever, I'm not discussing what are "special" features here).

Additionally, this is critical so I would **strongly recommend** you to avoid using `<Tab>` in default mappings. The `<Tab>` in terminal is equal to `<C-i>` so users cannot get back to the previous cursor position on the vimfiler's window currently.

**Comment by Shougo** [comment]
I have decided.

defx.nvim does not provide any default mappings.

**Comment by arstum** [comment]
why not

**Comment by wsdjeg** [comment]
public key binding API is enough.

**Comment by Shougo** [comment]
It is already implemented.
