### ISSUE TITLE
WIP Feature: choose whether to discard when starting defx

### ISSUE THREAD

**Issue by woodyZootopia** [Shougo/defx.nvim#55]
When starting defx on unsaved files, the unsaved changes will be discarded. That is unfriendly.
Therefore, it would be better to let users choose.
It will act like this:

* :Defx
  * unsaved changes. discard? (y / n / s:save and go): 
* :Defx -force-save
  * (save anyway)
* :Defx -force
  * (discard anyway)

**Comment by woodyZootopia** [comment]
#57 
sent a PR. it doesn't have the confirmation of saving, just -save option.

**Comment by woodyZootopia** [comment]
@Shougo contacted me and told that he is also solving this issue.
I will close this issue when he solved.

**Comment by Shougo** [comment]
I have fixed it in the latest version.
