### ISSUE TITLE
Syntax highlight not work

### ISSUE THREAD

**Issue by amikai** [Shougo/defx.nvim#58]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
First i use `:Defx` open the defx. The syntax highlight not work. But when I `:Defx` again it work.
Every time i want  syntax highlight, I need to command twice.

I found that when `vim-precious` plugin enable. Defx syntax highligh will not work (See minimal vimrc file).

## Environment Information

 * defx version(SHA1): lastest

 * OS: macos

 * neovim/Vim version: NVIM v0.3.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
## defx.nvim
health#defx#check
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```vim
et $nvimrc=fnamemodify(expand('<sfile>'), ':h')
let s:dein_dir = expand($nvimrc.'/dein')

if &runtimepath !~# '/dein.vim'
    let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

    " Auto Download
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim ' . s:dein_repo_dir
    endif

    execute 'set runtimepath^=' . s:dein_repo_dir
endif

let g:dein#install_max_processes = 16
let g:dein#install_message_type = 'none'

if !dein#load_state(s:dein_dir)
    finish
endif

call dein#begin(s:dein_dir, expand('<sfile>'))
    if !has('nvim')
        call dein#add('roxma/nvim-yarp')
        call dein#add('roxma/vim-hug-neovim-rpc')
    endif
call dein#add('Shougo/defx.nvim')
call dein#add('osyo-manga/vim-precious')

call dein#end()
call dein#save_state()
if has('vim_starting') && dein#check_install()
    call dein#install()
endif

```

## The reproduce ways from neovim/Vim starting (Required!)
Use above vimrc setting then`:Defx` twice

## Screen shot (if possible)

![GitHub Logo](https://user-images.githubusercontent.com/13815956/50380572-2bc24300-06a6-11e9-8b65-86fa86ad42c3.png)

`:Defx` no syntax highlight

## Upload the log file
https://gist.githubusercontent.com/amikai/5fbdf649a64c3e2e8441b039b4d254dc/raw/ac6417845cfa7d18bd4488bfbc02d680ecd200ec/gistfile1.txt

**Comment by Shougo** [comment]
```vim
let g:precious_enable_switchers = {'*': {'setfiletype': 1}, 'defx': {'setfiletype': 0}}
```

Please disable vim-precious in defx buffer.
It is vim-precious's conflict.  Please read vim-precious's documentation
