### ISSUE TITLE
Adjust content to window width

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#59]
Consider the following minimal init.nvim:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/vimfiler
filetype plugin indent on

nnoremap <silent> ,xf :Defx -split=vertical -winwidth=40
            \ -columns=mark:filename:type:size -show-ignored-files
            \ -direction=topleft `expand('%:p:h')` -search=`expand('%:p')`<CR>
```
Now open nvim and run `,xf`. You can see in the GIF that the file size is not shown in the window and you need to scroll to the right to actually see it. On the other hand on vimfiler this works correctly (i.e the contents of window are adjusted to fit in the window width)

![peek 2019-01-02 02-09](https://user-images.githubusercontent.com/2583971/50580931-7aed3e00-0e33-11e9-9fed-e4f426205682.gif)

**Comment by Shougo** [comment]
Sorry.  I don't want to add the feature.
vimfiler implements it, but it often broken.

**Comment by petobens** [comment]
Mmm that's a pity. Are you willing to reconsider this? It's a nice feature to have and it's terribly annoying having to scroll to see the file sizes.

**Comment by Shougo** [comment]
No.
