### ISSUE TITLE
Global clipboard support

### ISSUE THREAD

**Issue by Shougo** [Shougo/defx.nvim#6]
https://github.com/Shougo/vimfiler.vim/issues/416

**Comment by Shougo** [comment]
I have implemented copy, move and paste actions.

**Comment by kristijanhusak** [comment]
@Shougo is there a way to copy a file with a different name?

**Comment by Shougo** [comment]
It is not supported yet.

**Comment by Shougo** [comment]
> @Shougo is there a way to copy a file with a different name?

I have implemented the feature.
