### ISSUE TITLE
Command for vertical split not working anymore

### ISSUE THREAD

**Issue by oblitum** [Shougo/defx.nvim#61]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Command for vertical split not working anymore:

```vim
:Defx -split=vertical -winwidth=50 -direction=topleft -columns=icons:filename:type
```

It's just opening full window.

## Expected

Open a sidebar as it worked previously

## Environment Information

 * defx version(SHA1): 8cb96ac

 * OS: ArchLinux

 * neovim/Vim version: NeoVim 0.3.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. `:Defx -split=vertical -winwidth=50 -direction=topleft -columns=icons:filename:type`

## Extra

Bad commit: https://github.com/Shougo/defx.nvim/commit/bf78fd809fc8a95d045046617fc6c42cc83eade9

**Comment by sandangel** [comment]
@oblitum I have the same problem. Here is my work around

```
nnoremap <silent> <F3> :call DefxDrawerToggle()<CR>
" nnoremap <silent> <F3> :Defx -columns=git:mark:filename:type -toggle -split=vertical -winwidth=60 -direction=botright<CR>
fun! DefxDrawerToggle()
  if bufwinnr('defx') > 0
    execute "bd! " . bufnr('defx')
  else
    rightbelow vert split
    Defx `expand('%:p:h')`
    vert resize 60
  endif
endfun
```

**Comment by oblitum** [comment]
Looks like the cause is the fix for issue #60. Not sure how `:Defx -split=vertical -winwidth=50 -direction=topleft -columns=icons:filename:type` should be translated to the new way of doing the same, if there's one.

**Comment by oblitum** [comment]
OK, looks like I just needed to:

```
  call defx#custom#option('_', {
  \   'columns': 'icons:filename:type',
  \   'direction': 'topleft',
  \   'split': 'vertical',
  \   'winwidth': 50
  \ })
```

And `:Defx` would open as `:Defx -split=vertical -winwidth=50 -direction=topleft -columns=icons:filename:type` by default.

This will be enough for me but, I was initially using the command as a mapping:

```vim
nnoremap <silent> <leader>D :Defx -split=vertical -winwidth=50 -direction=topleft -columns=icons:filename:type<cr>
```

And I could have a variation  of different mappings with custom settings, this seems not possible anymore as simply as it was before.

**Comment by Shougo** [comment]
Confirmed.
It is the bug of defx.

Please update it.
