### ISSUE TITLE
Wrong split and window positions

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#66]
Consider the following minimal `init.vim`:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/vimfiler
set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/unite.vim

set splitright
set splitbelow

call defx#custom#option('_', {
            \ 'winwidth': 40,
            \ 'split': 'vertical',
            \ 'direction': 'topleft',
            \ })
call vimfiler#custom#profile('default', 'context', {
            \ 'direction' : 'topleft',
            \ 'split': 1,
            \ 'winwidth' : 40,
            \ 'force_quit': 1,
            \ })

nnoremap <silent> ,xfe :Defx<CR>
nnoremap <silent> ,fe :VimFilerBufferDir<CR>

augroup ps_defx_vimfiler
    au!
    au FileType defx call s:defx_settings()
    au FileType vimfiler call s:vimfiler_settings()
augroup END

function! s:defx_settings()
    " nnoremap <silent><buffer><expr> <CR> defx#do_action('open')
    nnoremap <silent><buffer><expr> <CR> defx#do_action('drop')
    nnoremap <silent><buffer><expr> s defx#do_action('open', 'split')
    nnoremap <silent><buffer><expr> v defx#do_action('open', 'vsplit')
    nnoremap <silent><buffer><expr> q defx#do_action('quit')
endfunction
function! s:vimfiler_settings()
    nnoremap <buffer><expr><silent> s vimfiler#do_switch_action('split')
    nnoremap <buffer><expr><silent> v vimfiler#do_switch_action('vsplit')
    nmap <buffer> q <Plug>(vimfiler_exit)
endfunction
```
In the following gif I show vimfiler's behaviour (called via the `,fe` mapping):
i) press `,fe` and open the  `a.txt` file with `<CR>`.
ii) press `,fe` again and open `b.txt` with `v` mapping
iii) press `,fe` again  and open `c.txt` with `<CR>`
iv) press `,fe` and open `b.txt` with `s`
![vimfiler](https://user-images.githubusercontent.com/2583971/50729785-5ab4cc00-111e-11e9-8ef7-5edada58b1b2.gif)

I want to achieve the same behaviour with defx however i find the following problems/differences:
i) press `,xfe` and open the  `a.txt` file with `<CR>` -> the defx buffer doesn't close (if I use `open` instead of `drop` the buffer does close but the file is opened in the defx window (that it's only 40 characters wide))
ii) go back to the defx buffer with `<C-W>h` and  open `b.txt` with `v` mapping -> instead of opening to the right (as per the `splitright` setting) the `b.txt` file is opened to the left
iii) go back to the defx buffer with `<C-W>h` and and open `c.txt` with `<CR>` -> this is correctly opened in the corresponding buffer (where the `b.txt` file was)
iv) close the defx buffer with `q`, move to the right to the `a.txt` file with `<C-W>l`,  press `,fe` and open `c.txt` with `s` -> it's not opened below the `a.txt` buffer (which is the buffer that called defx) but rather on the same defx buffer window
![defx](https://user-images.githubusercontent.com/2583971/50729810-d44cba00-111e-11e9-8d8f-e4522700ead0.gif)

I think vimfiler has the proper predictable behaviour and defx should follow it.

**Comment by Shougo** [comment]
> I think vimfiler has the proper predictable behaviour and defx should follow it.

Sorry.  I don't want to follow the complicated behavior in vimfiler.

**Comment by petobens** [comment]
> Sorry. I don't want to follow the complicated behavior in vimfiler.

But the current behaviour is completely unpredictable now. For instance If I call `:Defx` from one window and press `s` to open the file in a split window then I expect it to open below the window that called defx.

Besides Defx should honor the `splitright` and `splitbelow` settings. Otherwise you never know where files will open.

**Comment by petobens** [comment]
In other words: Defx messes up the window layout and opens windows wherever it wants. This shouldn't be a feature.

**Comment by Shougo** [comment]
> But the current behaviour is completely unpredictable now.

The current behavior is very clearly for me.
In "open", it opens from defx window.
In "drop", it opens from previous window.

**Comment by Shougo** [comment]
>Besides Defx should honor the splitright and splitbelow settings.

Defx already honor `splitright` and `splitbelow` configurations.
Defx opens `right` of defx window.
Because, you have used `open` action.  It opens from defx window.

**Comment by Shougo** [comment]
So you should use `drop` action instead.

**Comment by petobens** [comment]
How I can open from the previous window and close/quit the defx buffer upon opening the file?

**Comment by petobens** [comment]
I want to do something like `defx#do_action('drop', 'quit')` but that doesn't work

**Comment by Shougo** [comment]
> How I can open from the previous window and close/quit the defx buffer upon opening the file?

It is not supported.  It is another feature.  You should create another issue.

**Comment by petobens** [comment]
Ok thanks. I will try the drop action and report if there are problems.
