### ISSUE TITLE
Defx blinking and slowly rerendering when focused

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#73]
# Problems summary
Since latest commit https://github.com/Shougo/defx.nvim/commit/ec512a6aca968427258efe75b31de734c9295179 where you added async action for opening defx, it is behaving strangely. Because of the async nature, it blinks when focused. I didn't had this issue before.

Also, note that i'm using 2 custom columns. When i remove them, it is better, but still noticable when switching focus fast.

## Expected
Expected not to blink.

## Environment Information

 * defx version(SHA1): ec512a6aca968427258efe75b31de734c9295179

 * OS: Manjaro Linux i3

 * neovim/Vim version: NVIM v0.4.0-242-ged0e96cd2

 * `:checkhealth` or `:CheckHealth` result(neovim only): 
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
set runtimepath+=~/path/to/defx-git "https://github.com/kristijanhusak/defx-git
set runtimepath+=~/path/to/defx-icons "https://github.com/kristijanhusak/defx-icons

call defx#custom#option('_', {
      \ 'columns': 'git:icons:filename:size:time',
      \ })

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open neovim
 2. Open defx
 3. Switch focus between Defx and another window

## Screen shot (if possible)
Note the syntax off/on in defx window.

![defx-gif](https://user-images.githubusercontent.com/1782860/52405938-cd71e800-2acc-11e9-9727-fe02e419fa31.gif)

**Comment by kristijanhusak** [comment]
@Shougo i still have very bad performance, especially when using icons column. It add as a lot of syntax highlighting, so i understand why, but switching to async really slowed down everything for me. I also implemented `syntaxes` method in my columns, but it still works really bad. Why you switched this to async? Sync was working really good for me.

**Comment by Shougo** [comment]
Really?  I have improved asynchronous update check(it is updated only when directory is changed) and update behavior.  The problem is gone for me.
Your defx is the latest version?

I will test your columns though.

You should describe the problem in more detailed.  It is very hard to understand.

> Why you switched this to async? Sync was working really good for me.

OK.  I describe.  The asynchronous update is needed for huge items directory.
It is added intentionally.

**Comment by kristijanhusak** [comment]
I understand why you added async implementation, but sync was working really good for me also. For javascript projects `node_modules` folder which has over 1000 folders opens instantly.

I updated my https://github.com/kristijanhusak/defx-icons column to add highlight only on init, not with `highlight()` and `syntaxes()` methods. If you want to check old behavior, check out to older commit https://github.com/kristijanhusak/defx-icons/commit/82c603e32746f2b2f5764d049a53dccbc5324ec4. I am using `syntaxes()` functionality as part of the highlight, because you added `syntaxes()` method recently, and i had duplicates issue before.

Here are steps to reproduce:
1. Use minimal vimrc from the first comment
2. Checkout `defx-icons` column to the commit i put above (i did syntax clearing manually before you added `syntaxes()` method.)
3. Open some file in nested folder in project
4. Try executing `:Defx -winwidth=40 -direction=topleft -split=vertical -search `expand('%:p') `expand('%:p:h')`

It happens randomly, so it's not 100% reproducible with these steps.
My column slows things down because it adds a lot of highlights. When i try disabling it (`let g:defx_icons_enable_syntax_highlight = 0`), it works much better.
This wasn't the issue before while we had sync functionality.

**Comment by Shougo** [comment]
OK.  Please test #74.

**Comment by Shougo** [comment]
>  For javascript projects `node_modules` folder which has over 1000 folders opens instantly.

My huge means over 10000 files.
