### ISSUE TITLE
Sometimes `cd` action clears the defx buffer's syntax highlights.

### ISSUE THREAD

**Issue by notomo** [Shougo/defx.nvim#75]
# Problems summary

`cd` action after `Defx {paths}` clears the syntax highlights.

## Expected

The syntax highlights work.

## Environment Information

 * defx version(SHA1): 5ee5425

 * OS: CentOS7

 * neovim/Vim version: NVIM v0.4.0-286-gece19b459

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.5
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.
```

```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/defx.nvim/
e ~/path/to/defx.nvim/rplugin/python3/defx/__init__.py
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. nvim -u ~/path/to/minimal.vim
 2. execute :Defx \`expand('%:p:h')\`
 3. execute :call defx#call_action('cd', ['..'])

**Comment by Shougo** [comment]
I don't reproduce the problem.
I have fixed some syntax problems.  Please try the latest version.

**Comment by hrsh7th** [comment]
I had same problem.

It solved via latest version in my environment.

**Comment by notomo** [comment]
2c0eff7 seems to resolve this issue :pray:
Thank you!

FYI: On my environment,
- 2c0eff7 works
- 0297657 does not work
- ca9bd75 works
