### ISSUE TITLE
Add highlighting group for current directory

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#82]
Is it possible to add a highlighting group for the current directory? Note that in vimfiler (on the left) we have this in red whereas on defx its in yellow same as any other directory: this makes it difficult to distinguish between the current directory and directories within this current directory:

![screenshot_2019-03-02_10 17 14](https://user-images.githubusercontent.com/2583971/53682458-a629c780-3cd4-11e9-85da-d728b1ec875d.png)

**Comment by petobens** [comment]
Thank you!

**Comment by petobens** [comment]
One minor nit: can you add something like `[in]:` to the root? Using a plain `:` with the new tree feature looks a bit weird (vimfiler on the left and defx on the right):
![screenshot_2019-03-03_23 37 10](https://user-images.githubusercontent.com/2583971/53707367-7500e280-3e0d-11e9-9ed4-b9c78e9522b7.png)

Also it would be really nice to have a blank line between the root directory and the other directories

**Comment by Shougo** [comment]
I have concealed root marker.

**Comment by petobens** [comment]
> I have concealed root marker.

Mmm this looks even worse now (I might not understand the change though):
![screenshot_2019-03-04_10 29 20](https://user-images.githubusercontent.com/2583971/53736418-78758780-3e68-11e9-826d-102684f66102.png)

**Comment by petobens** [comment]
> Also it would be really nice to have a blank line between the root directory and the other directories
I think this will also make it look better

**Comment by Shougo** [comment]
I have changed the root marker.   Because conceal conflicts with current column feature.

> Also it would be really nice to have a blank line between the root directory and the other directories

No.  I don't want to change it.  I think root and candidates should be seemless.

What is the worse?  I don't understand.

**Comment by petobens** [comment]
With the latest change to the root marker it looks good now. Thanks!

**Comment by mhartington** [comment]
Is there a way to disable this? I actually like the older version much better than the `[in]: `

**Comment by Shougo** [comment]
@mhartington I have added `root_marker` option.

**Comment by pwntester** [comment]
Hi, 

I can see in several screenshots that the root element is highlighted differently. I tried to set a diferent highlight using `Defx_filename_root` highlight, but that also affect directories. I cant find any documentation for syntax highlighting. What would be the right highlight?

Thanks,
A

**Comment by petobens** [comment]
I believe the relevant commit is: https://github.com/Shougo/defx.nvim/commit/f5d545a40eee05d56c6bbfd4684d08ca20941bba

**Comment by pwntester** [comment]
@petobens what highlight group did you use to get the root directory in red?

**Comment by petobens** [comment]
I use `Defx_filename_root`. Check the output of `:syntax` from within a defx buffer. AFAICT it will work as far as the root dir ends with `/`.  That's what I have in my config here: https://github.com/Shougo/defx.nvim/commit/f5d545a40eee05d56c6bbfd4684d08ca20941bba

And here is my `:syntax` output:
![Screenshot_2019-03-12_17:39:31](https://user-images.githubusercontent.com/2583971/54234412-d4d24a00-44ed-11e9-90c3-33ae8625b50a.png)

**Comment by pwntester** [comment]
Ok, seems like `root_marker` need to be set to something other than an empty string (default value) for the highlight groups to be applied. 

Also, in my case the colors are applied incorrectly, `Defx_filename_root` is applied for directories and `Defx_filename_directory` is applied for root.

Thanks

**Comment by mhartington** [comment]
I've opened an issue for this here 

https://github.com/Shougo/defx.nvim/issues/100
