### ISSUE TITLE
Highlight whole selected candidates

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#84]
Is possible to highlight the whole defx selected candidates instead of just the mark? In the following image you can see vimfiler on the left (with the desired behaviour) and defx on the right:
![screenshot_2019-03-03_23 53 28](https://user-images.githubusercontent.com/2583971/53707870-8fd45680-3e0f-11e9-90e3-34a8ee0d5bcc.png)

**Comment by Shougo** [comment]
It is not possible.
Closing.
