### ISSUE TITLE
Finding current file with new tree feature not working

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#87]
# Problems summary
With the new tree feature, there is no way to find the current file in defx. Old way works.

## Expected
To find the file using the tree feature from `getcwd()`

## Environment Information

 * defx version(SHA1): dd72ac36da051c4de475a05a9755178fa5fb78bf

 * OS: Manjaro Linux

 * neovim/Vim version:
	```
	NVIM v0.3.4
	Build type: Release
	LuaJIT 2.0.5
	```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
	```
	health#defx#check
	========================================================================
	## defx.nvim
	  - OK: has("python3") was successful
	  - OK: Python 3.6.1+ was successful
	```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open some project, and open some file in nested folder
 2. Execute command:
```
:Defx -search=`expand('%:p')` `getcwd()`
```
 3. None of the folder trees are opened, file is not found.

**Comment by Shougo** [comment]
It works for me.

**Comment by Shougo** [comment]
> Open some project, and open some file in nested folder

I get it.  The nested folder is not supported.

**Comment by kristijanhusak** [comment]
Will it be supported?

**Comment by Shougo** [comment]
Implemented.

**Comment by kristijanhusak** [comment]
Thanks.

**Comment by kristijanhusak** [comment]
@Shougo how to use this new search?

I tried this:
```
:Defx -search=`expand('%:p')` `getcwd()`
```

But it doesn't work for me. For example, when i open `rplugin/python3/defx/action.py` and my `getcwd()` = `/home/kristijan/defx.nvim`, it only opens first level of `rplugin`.

**Comment by Shougo** [comment]
Fixed.

**Comment by kristijanhusak** [comment]
Thanks, it works now.

**Comment by emeentag** [comment]
> @Shougo how to use this new search?
> 
> I tried this:
> 
> ```
> :Defx -search=`expand('%:p')` `getcwd()`
> ```
> 
> But it doesn't work for me. For example, when i open `rplugin/python3/defx/action.py` and my `getcwd()` = `/home/kristijan/defx.nvim`, it only opens first level of `rplugin`.

This solution has some problem. It is working fine when you first open the tree with those commands but if you initiate the tree(toggle) then run > ```:Defx -search=`expand('%:p')` `getcwd()` ``` it is just opening a new tree and not finding the current file. It does not matter how many times to run that command from now on, it opens a new tree all the time.

Should i file a bug for that?

**Comment by Shougo** [comment]
@emeentag Have you read the documentation?
Unfortunately, it is not bug.

If you want to jump exists tree, you need to specify `-resume` option.

```
							*defx-option-resume*
-resume
		Resume existing defx buffer.
		Note: |defx-option-listed| is needed to resume.

		Default: false
```

**Comment by Shougo** [comment]
Hm...  I have tested `Defx -search=`expand('%:p')` `getcwd()` `.
It works for me.

If you don't upload the reproduce instructions like https://github.com/Shougo/defx.nvim/issues/87#issue-417881642, I will ignore your report.

**Comment by emeentag** [comment]
Ok i mapped this `-search` action into <F4> key like 
`        nnoremap <silent> <F4>
                \ :<C-u>Defx -resume -search=`expand('%:p')` `getcwd()`<CR>
`

But getting some error
`Error detected while processing function defx#util#call_defx[2]..defx#start[5]..defx#util#rpcrequest:
line   18:
Error invoking '_defx_start' on channel 5 (python3-rplugin-host):
error caught in request handler '_defx_start [[[], {'columns': 'indent:git:icons:filename', 'auto_cd': 0, 'prev_bufnr': 1, 'root_marker': '[in]: ', 'resume': '', 'auto_recursive_level': 0, 'sort': 'filename', 'listed': 0, 'new': 0, 'ign
ored_files': '.*', 'direction': 'topleft', 'visual_end': 9, 'winheight': 30, 'profile': 0, 'search': '', 'buffer_name': 'default', 'winwidth': 30, 'split': 'vertical', 'visual_start': 8, 'cursor': 8, 'prev_winid': 1000, 'wincol': 59, 'w
inrow': 16, 'show_ignored_files': 0, 'toggle': False}]]':`

Can you help me about it. And i wish to have . abetter documentation.

**Comment by Shougo** [comment]
@emeentag I have tested your mapping.  It works for me.
You have not upload the minimal vimrc and the reproduce instructions.
OK.  I must ignore your report.

> And i wish to have . abetter documentation.

You can improve the documentation.

**Comment by Shougo** [comment]
> 'columns': 'indent:git:icons:filename'

Oh,  you use the custom column.  It is not minimal.
