### ISSUE TITLE
Copy file with rename doesn't copy file to right destination with tree feature

### ISSUE THREAD

**Issue by kristijanhusak** [Shougo/defx.nvim#91]
# Problems summary
Using tree feature there is a problem when you try to paste something into nested tree folder and it requires renaming (both underbar or custom rename)

## Expected
Expected to have file copied to proper destination.

## Environment Information

 * defx version(SHA1): 5739e9de4a12b574d4653a7ddb1b511be13c6019

 * OS: Manjaro Linux

 * neovim/Vim version:
	```
	NVIM v0.3.4
	Build type: Release
	LuaJIT 2.0.5
	```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
	```
	health#defx#check
	========================================================================
	## defx.nvim
	  - OK: has("python3") was successful
	  - OK: Python 3.6.1+ was successful
	```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/defx.nvim/

autocmd FileType defx call s:defx_mappings()

function! s:defx_mappings() abort
  nnoremap <silent><buffer> C defx#do_action('copy')
  nnoremap <silent><buffer> P defx#do_action('paste')
  nnoremap <silent><buffer> o defx#do_action('open_tree')
endfunction

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Have this folder structure:
```
src/
  domain/
    myfile.txt
dist/
  domain/
    myfile.txt
```
 2. Open `/src/domain` using `o` (open_tree action)
 3. select myfile.txt in it, press `C` (copy action)
 4. Open `/dist/domain` using `o` (open_tree action)
 5. select myfile.txt in it, press `P` (paste action)
 6. Use Underbar option (custom rename also doesn't work)
 7. File get's copied to root as `myfile.txt_` instead of `/dist/domain/myfile.txt_`

Also noticed when doing `paste` and selecting `rename`, destination path is not changed (in this case it looks like this 
`src/domain/myfile.txt -> src/domain/myfile.txt`, 
where it should look like this:
`src/domain/myfile.txt -> dist/domain/myfile.txt`
I tried changing the `src` to `dist` in the rename mode, but it didn't work.

**Comment by Shougo** [comment]
I have improved the copy/paste behavior with https://github.com/Shougo/defx.nvim/pull/89.
It does not work well?

@hrsh7th Ping.

**Comment by Shougo** [comment]
I get it.  Paste action is broken.

**Comment by Shougo** [comment]
Fixed

**Comment by Shougo** [comment]
@hrsh7th Don't mind.  It was broken before #89.

**Comment by hrsh7th** [comment]
Oh.,sorry. I did'nt noticed this problem.
Thanks for reporting and fix.
