### ISSUE TITLE
toggle option do not work

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/defx.nvim#94]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

can not toggle defx windows.

## Expected

toggle option works well

## Environment Information

 * defx version(SHA1): master

 * OS: win7

 * neovim/Vim version: master

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set rtp+=C:\Users\Administrator\.cache\vimfiles\repos\github.com\Shougo\defx.nvim

call defx#custom#option('_', {
      \ 'winwidth': 30,
      \ 'split': 'vertical',
      \ 'direction': 'botright',
      \ 'show_ignored_files': 0,
      \ 'buffer_name': '',
      \ 'toggle': 1,
      \ 'resume': 1
      \ })

call defx#custom#column('mark', {
      \ 'readonly_icon': '',
      \ 'selected_icon': '',
      \ })

call defx#custom#column('filename', {
      \ 'directory_icon': '',
      \ 'opened_icon': '',
      \ })
nnoremap <silent> <F3> :Defx<Cr>

```

## The reproduce ways from neovim/Vim starting (Required!)

 1. press `<F3>`
 2. press `<F3>`

## Screen shot (if possible)

![图片](https://user-images.githubusercontent.com/13142418/54082915-a3c01100-4357-11e9-8ada-4ad6e8e8b31c.png)

**Comment by Shougo** [comment]
I don't reproduce it.

```vim
set runtimepath+=~/work/defx.nvim/
set runtimepath+=~/work/vim-hug-neovim-rpc/
set runtimepath+=~/work/nvim-yarp/
" set runtimepath+=~/src/vim-airline/

filetype plugin indent on
syntax enable

colorscheme desert

call defx#custom#option('_', {
      \ 'winwidth': 30,
      \ 'split': 'vertical',
      \ 'direction': 'botright',
      \ 'show_ignored_files': 0,
      \ 'buffer_name': '',
      \ 'toggle': 1,
      \ 'resume': 1
      \ })

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
endfunction

nnoremap <silent> <F3> :Defx<Cr>
```

Fortunately, it is open source.
You can fix the problem.

**Comment by Shougo** [comment]
I think it is Windows specific behavior.
Please test it in Linux environment.

**Comment by wsdjeg** [comment]
I also can not reproduce it in linux.

**Comment by Shougo** [comment]
Please use the latest version.  It is better.
