### ISSUE TITLE
feature-request: add close_tree_recursive and close parent tree from dir leaf

### ISSUE THREAD

**Issue by petobens** [Shougo/defx.nvim#96]
Two related feature requests:
1. Add `close_tree_recursive` action (sister to `open_tree_recursive`)
2. Currently it's possible to close the parent tree (directory) from within a file inside that tree/dir. However it's not possible to close the parent tree/dir from within a directory inside that tree.  In the GIF below if I run `close_tree` action on the `R_settings.vim` file then the `r/` folder tree closes. However if I now run `close_tree` on the `r/` folder then the `ftplugin/` parent tree does not close:
![rclose](https://user-images.githubusercontent.com/2583971/54087134-d570b200-432e-11e9-9a55-b799d15b1aaa.gif)

**Comment by Shougo** [comment]
> Currently it's possible to close the parent tree (directory) from within a file inside that tree/dir. However it's not possible to close the parent tree/dir from within a directory inside that tree.

Fixed.

**Comment by Shougo** [comment]
> Add close_tree_recursive action (sister to open_tree_recursive)

Why it is needed?   Please describe it.
vimfiler does not have this feature.

**Comment by petobens** [comment]
> Fixed.

Thank you!

> Why it is needed? Please describe it.
vimfiler does not have this feature.

Ok. No problem. Closing

**Comment by Shougo** [comment]
OK.  I have tested to implement `close_tree_recursive`. It is hard.
Closing.
