### ISSUE TITLE
Request: Setting to suppress delete confirm prompt

### ISSUE THREAD

**Issue by svermeulen** [Shougo/defx.nvim#99]
Currently, when using either do_action `remove_trash` or do_action `remove`, it always prompts with "Are you sure you want to delete?".  I'd like to be able to suppress this, especially for `remove_trash` and just delete immediately.  Can an option be added for that behaviour?

**Comment by Shougo** [comment]
Why it is needed?
Please describe it more clearly.

**Comment by svermeulen** [comment]
I do not want a confirm prompt because it is faster.  When I use `remote_trash`, it is already backed up so there is no need for a prompt.

**Comment by svermeulen** [comment]
This works great, thank you!
